/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIKBShape.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, NSArray, NSMutableArray, UIKBKeyset;

@interface UIKBKeylayout : UIKBShape <NSCoding, NSCopying> {
	NSString* m_name;
	UIKBKeyset* m_keyset;
	NSMutableArray* m_refs;
}
@property(retain, nonatomic) UIKBKeyset* keyset;	// @synthesize=m_keyset
@property(retain, nonatomic) NSString* name;	// @synthesize=m_name
@property(readonly, assign, nonatomic) NSArray* references;
+(id)keylayout;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)description;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(id)keyset;
-(void)layoutInRect:(CGRect)rect;
// declared property getter: -(id)name;
-(id)referenceWithName:(id)name;
// declared property getter: -(id)references;
// declared property setter: -(void)setKeyset:(id)keyset;
// declared property setter: -(void)setName:(id)name;
-(void)setRef:(id)ref;
-(void)setReferenceWithName:(id)name value:(id)value flags:(unsigned)flags;
@end

