/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UINavigationController.h"

@class NSArray, UIMoreListController;

@interface UIMoreNavigationController : UINavigationController {
	UIMoreListController* _moreListController;
	UINavigationController* _originalNavigationController;
	UIViewController* _originalRootViewController;
}
@property(assign, nonatomic) BOOL allowsCustomizing;
@property(assign, nonatomic) UIViewController* displayedViewController;
@property(retain, nonatomic) NSArray* moreViewControllers;
@property(assign, nonatomic) BOOL moreViewControllersChanged;
-(id)init;
-(id)_preparedViewController:(id)controller;
-(void)_restoreOriginalNavigationController;
// declared property getter: -(BOOL)allowsCustomizing;
-(void)dealloc;
-(void)didShowViewController:(id)controller animated:(BOOL)animated;
// declared property getter: -(id)displayedViewController;
// declared property getter: -(id)moreViewControllers;
// declared property getter: -(BOOL)moreViewControllersChanged;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
// declared property setter: -(void)setAllowsCustomizing:(BOOL)customizing;
// declared property setter: -(void)setDisplayedViewController:(id)controller;
// declared property setter: -(void)setMoreViewControllers:(id)controllers;
// declared property setter: -(void)setMoreViewControllersChanged:(BOOL)changed;
@end

