/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"


__attribute__((visibility("hidden")))
@interface UIMovieScrubberTrackOverlayView : UIView {
@private
	double _value;
	double _minimumValue;
	double _maximumValue;
	double _startValue;
	double _endValue;
	UIView* _leftFillView;
	UIView* _rightFillView;
	UIView* _innerShadowView;
	CGRect _leftFillFrame;
	CGRect _rightFillFrame;
	unsigned _editingHandle;
	unsigned _editing : 1;
	unsigned _zoomed : 1;
}
-(id)initWithFrame:(CGRect)frame;
-(void)_clampValueAndLayout;
-(void)_updateLeftFill;
-(void)_updateRightFill;
-(void)animateFillFramesAway;
-(void)layoutSubviews;
-(void)setEditing:(BOOL)editing;
-(void)setEditingHandle:(int)handle;
-(void)setEndValue:(double)value;
-(void)setFrame:(CGRect)frame;
-(void)setIsZoomed:(BOOL)zoomed;
-(void)setMaximumValue:(double)value;
-(void)setMinimumValue:(double)value;
-(void)setStartValue:(double)value;
-(void)setValue:(double)value;
@end

