/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIStoryboardSegue.h"


__attribute__((visibility("hidden")))
@interface UIStoryboardReplaceSegue : UIStoryboardSegue {
@private
	int _destinationContainmentContext;
	int _splitViewControllerIndex;
}
@property(assign, nonatomic) int destinationContainmentContext;	// @synthesize=_destinationContainmentContext
@property(assign, nonatomic) int splitViewControllerIndex;	// @synthesize=_splitViewControllerIndex
// declared property getter: -(int)destinationContainmentContext;
-(void)perform;
// declared property setter: -(void)setDestinationContainmentContext:(int)context;
// declared property setter: -(void)setSplitViewControllerIndex:(int)index;
// declared property getter: -(int)splitViewControllerIndex;
@end

