/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "NSCoding.h"
#import "UIKit-Structs.h"
#import "UIControl.h"
#import "UITextInput.h"
#import "UITextSelectingContainer.h"
#import "UIPopoverControllerDelegate.h"
#import "UITextField.h"

@class UIPopoverController, UIButton, UITextInputTraits, UITextFieldLabel, UITextFieldBorderView, UITextFieldAtomBackgroundView, UITextRange, NSDictionary, UITextPosition, UITextFieldBackgroundView, UIViewController, UITextSelectionView, UITextInteractionAssistant, UIFont, UILabel, UIColor, UIImageView, UIImage, NSString;
@protocol UITextFieldDelegate, UITextInputDelegate, UITextInputTokenizer, UITextSelectingContent;

@interface UITextField : UIControl <UITextSelectingContainer, UIPopoverControllerDelegate, UITextInput, NSCoding> {
@private
	NSString* _text;
	UIColor* _textColor;
	int _borderStyle;
	float _minimumFontSize;
	id _delegate;
	UIImage* _background;
	UIImage* _disabledBackground;
	int _clearButtonMode;
	UIView* _leftView;
	int _leftViewMode;
	UIView* _rightView;
	int _rightViewMode;
	UITextInputTraits* _traits;
	UITextInputTraits* _nonAtomTraits;
	float _fullFontSize;
	float _paddingLeft;
	float _paddingTop;
	float _paddingRight;
	float _paddingBottom;
	NSString* _textFont;
	NSRange _selectionRange;
	int _scrollXOffset;
	int _scrollYOffset;
	int _suffixWidth;
	float _progress;
	NSString* _style;
	double _mouseDownTime;
	UIButton* _clearButton;
	CGSize _clearButtonOffset;
	CGSize _leftViewOffset;
	CGSize _rightViewOffset;
	UITextFieldBorderView* _backgroundView;
	UITextFieldBorderView* _disabledBackgroundView;
	UITextFieldBackgroundView* _systemBackgroundView;
	UITextFieldLabel* _textLabel;
	UITextFieldLabel* _placeholderLabel;
	UITextFieldLabel* _suffixLabel;
	UITextFieldLabel* _prefixLabel;
	UIImageView* _iconView;
	UILabel* _label;
	float _labelOffset;
	UITextInteractionAssistant* _interactionAssistant;
	UITextSelectionView* _selectionView;
	UIView* _inputView;
	UIView* _inputAccessoryView;
	UITextFieldAtomBackgroundView* _atomBackgroundView;
	UIPopoverController* _definitionPopoverController;
	UIViewController* _definitionModalViewController;
	UIColor* _shadowColor;
	CGSize _shadowOffset;
	float _shadowBlur;
	struct {
		unsigned secureTextChanged : 1;
		unsigned guard : 1;
		unsigned delegateRespondsToHandleKeyDown : 1;
		unsigned verticallyCenterText : 1;
		unsigned isAnimating : 4;
		unsigned inactiveHasDimAppearance : 1;
		unsigned becomesFirstResponderOnClearButtonTap : 1;
		unsigned clearsOnBeginEditing : 1;
		unsigned clearsPlaceholderOnBeginEditing : 1;
		unsigned adjustsFontSizeToFitWidth : 1;
		unsigned fieldEditorAttached : 1;
		unsigned canBecomeFirstResponder : 1;
		unsigned shouldSuppressShouldBeginEditing : 1;
		unsigned inResignFirstResponder : 1;
		unsigned undoDisabled : 1;
		unsigned contentsRTL : 1;
		unsigned explicitAlignment : 1;
		unsigned implementsCustomDrawing : 1;
		unsigned needsClearing : 1;
	} _textFieldFlags;
}
@property(assign, nonatomic) BOOL adjustsFontSizeToFitWidth;
@property(assign, nonatomic) int autocapitalizationType;	// @dynamic
@property(assign, nonatomic) int autocorrectionType;	// @dynamic
@property(retain, nonatomic) UIImage* background;	// @synthesize=_background
@property(readonly, assign, nonatomic) UITextPosition* beginningOfDocument;
@property(assign, nonatomic) int borderStyle;	// @synthesize=_borderStyle
@property(assign, nonatomic) int clearButtonMode;	// @synthesize=_clearButtonMode
@property(assign, nonatomic) BOOL clearsOnBeginEditing;
@property(readonly, assign, nonatomic) UIView<UITextSelectingContent>* content;
@property(assign, nonatomic) id<UITextFieldDelegate> delegate;	// @synthesize=_delegate
@property(retain, nonatomic) UIImage* disabledBackground;	// @synthesize=_disabledBackground
@property(readonly, assign, nonatomic, getter=isEditable) BOOL editable;
@property(readonly, assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;	// @dynamic
@property(readonly, assign, nonatomic) UITextPosition* endOfDocument;
@property(retain, nonatomic) UIFont* font;
@property(retain) UIView* inputAccessoryView;
@property(assign, nonatomic) id<UITextInputDelegate> inputDelegate;
@property(retain) UIView* inputView;	// @synthesize=_inputView
@property(readonly, assign, nonatomic) UITextInteractionAssistant* interactionAssistant;
@property(assign, nonatomic) int keyboardAppearance;	// @dynamic
@property(assign, nonatomic) int keyboardType;	// @dynamic
@property(retain, nonatomic) UIView* leftView;	// @synthesize=_leftView
@property(assign, nonatomic) int leftViewMode;	// @synthesize=_leftViewMode
@property(readonly, assign, nonatomic) UITextRange* markedTextRange;
@property(copy, nonatomic) NSDictionary* markedTextStyle;
@property(assign, nonatomic) float minimumFontSize;	// @synthesize=_minimumFontSize
@property(copy, nonatomic) NSString* placeholder;
@property(assign, nonatomic) int returnKeyType;	// @dynamic
@property(retain, nonatomic) UIView* rightView;	// @synthesize=_rightView
@property(assign, nonatomic) int rightViewMode;	// @synthesize=_rightViewMode
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;	// @dynamic
@property(copy) UITextRange* selectedTextRange;
@property(assign, nonatomic) int selectionAffinity;
@property(assign, nonatomic) int selectionGranularity;
@property(readonly, assign, nonatomic) UITextSelectionView* selectionView;
@property(assign, nonatomic) int spellCheckingType;	// @dynamic
@property(copy, nonatomic) NSString* text;
@property(assign, nonatomic) int textAlignment;
@property(retain, nonatomic) UIColor* textColor;
@property(readonly, assign, nonatomic) UIResponder<UITextSelection>* textDocument;
@property(readonly, assign, nonatomic) UIView* textInputView;
@property(readonly, assign, nonatomic) id<UITextInputTokenizer> tokenizer;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(CGRect)_atomBackgroundViewFrame;
-(void)_becomeFirstResponder;
-(void)_becomeFirstResponderAndMakeVisible;
-(BOOL)_canDrawContent;
-(void)_clearBackgroundViews;
-(id)_clearButton;
-(void)_clearButtonClicked:(id)clicked;
-(id)_clearButtonImageForState:(unsigned)state;
-(void)_clearSelectionUI;
-(void)_clearStyle;
-(id)_copyFont:(id)font newSize:(float)size maxSize:(float)size3;
-(id)_createCSSStyleDeclarationForWebView:(id)webView;
-(void)_define:(id)define;
-(id)_dictationInterpretations;
-(void)_drawTextInRect:(CGRect)rect forLabel:(id)label;
-(void)_encodeBackgroundColorWithCoder:(id)coder;
-(void)_endedEditing;
-(id)_fieldEditor;
-(BOOL)_fieldEditorAttached;
-(id)_findWebViewWordBoundaryFromPosition:(id)position;
-(CGSize)_fontMetrics:(id)metrics;
-(CGRect)_frameForLabel:(id)label inTextRect:(CGRect)textRect;
-(BOOL)_hasContent;
-(BOOL)_implementsCustomDrawing;
-(BOOL)_isDisplayingReferenceLibraryViewController;
-(BOOL)_isShowingPlaceholder;
-(BOOL)_isShowingPrefix;
-(id)_keyboardResponder;
-(CGSize)_leftViewOffset;
-(float)_marginTopForText:(id)text;
-(id)_placeholderColor;
-(id)_placeholderLabel;
-(id)_placeholderView;
-(void)_populateArchivedSubviews:(id)subviews;
-(CGRect)_prefixFrame;
-(void)_promptForReplace:(id)replace;
-(void)_removeDefinitionController;
-(BOOL)_requiresKeyboardResetOnReload;
-(void)_resetSelectionUI;
-(void)_resignFirstResponder;
-(CGSize)_rightViewOffset;
-(CGPoint)_scrollOffset;
-(void)_setImplicitAlignment;
-(void)_setLeftViewOffset:(CGSize)offset;
-(void)_setNeedsStyleRecalc;
-(void)_setPrefix:(id)prefix;
-(void)_setRightViewOffset:(CGSize)offset;
-(void)_setSuffix:(id)suffix withColor:(id)color;
-(void)_setSystemBackgroundViewActive:(BOOL)active;
-(BOOL)_shouldEndEditing;
-(BOOL)_shouldSendContentChangedNotificationsIfOnlyMarkedTextChanged;
-(BOOL)_showsAtomBackground;
-(BOOL)_showsClearButton:(BOOL)button;
-(BOOL)_showsClearButtonWhenEmpty;
-(BOOL)_showsClearButtonWhenNonEmpty:(BOOL)empty;
-(BOOL)_showsLeftView;
-(BOOL)_showsRightView;
-(void)_sizeChanged:(BOOL)changed;
-(id)_style;
-(CGRect)_suffixFrame;
-(Class)_systemBackgroundViewClass;
-(id)_text;
-(id)_textLabelView;
-(CGRect)_textRectExcludingButtonsForBounds:(CGRect)bounds;
-(CGRect)_textRectForBounds:(CGRect)bounds forEditing:(BOOL)editing;
-(CGSize)_textSize;
-(void)_updateAtomBackground;
-(void)_updateAutosizeStyleIfNeeded;
-(void)_updateBackgroundViews;
-(void)_updateButtons;
-(void)_updateLabel;
-(void)_updateTextColor;
-(void)_updateTextLabel;
-(void)_windowBecameKey;
-(id)actualFont;
-(float)actualMinimumFontSize;
-(CGRect)adjustedCaretRectForCaretRect:(CGRect)caretRect;
// declared property getter: -(BOOL)adjustsFontSizeToFitWidth;
-(int)atomStyle;
-(void)attachFieldEditor:(id)editor;
// declared property getter: -(id)background;
-(id)backgroundColor;
-(int)baseWritingDirectionForPosition:(id)position inDirection:(int)direction;
-(void)beginSelectionChange;
// declared property getter: -(id)beginningOfDocument;
-(CGRect)borderRectForBounds:(CGRect)bounds;
// declared property getter: -(int)borderStyle;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canResignFirstResponder;
-(void)cancelAutoscroll;
-(BOOL)caretBlinks;
-(CGRect)caretRectForPosition:(id)position;
-(unsigned)characterOffsetAtPoint:(CGPoint)point;
-(id)characterRangeAtPoint:(CGPoint)point;
-(id)characterRangeByExtendingPosition:(id)position inDirection:(int)direction;
-(id)clearButton;
// declared property getter: -(int)clearButtonMode;
-(CGSize)clearButtonOffset;
-(CGRect)clearButtonRect;
-(CGRect)clearButtonRectForBounds:(CGRect)bounds;
-(void)clearText;
// declared property getter: -(BOOL)clearsOnBeginEditing;
-(BOOL)clearsPlaceholderOnBeginEditing;
-(CGRect)closestCaretRectInMarkedTextRangeForPoint:(CGPoint)point;
-(id)closestPositionToPoint:(CGPoint)point;
-(id)closestPositionToPoint:(CGPoint)point withinRange:(id)range;
-(int)comparePosition:(id)position toPosition:(id)position2;
-(CGPoint)constrainedPoint:(CGPoint)point;
// declared property getter: -(id)content;
-(void)copy:(id)copy;
-(id)createPlaceholderLabelWithFont:(id)font andTextAlignment:(int)alignment;
-(id)createTextLabelWithTextColor:(id)textColor;
-(id)customOverlayContainer;
-(void)cut:(id)cut;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)deleteBackward;
// declared property getter: -(id)disabledBackground;
-(id)documentFragmentForPasteboardItemAtIndex:(int)index;
-(void)drawBorder:(CGRect)border;
-(void)drawPlaceholderInRect:(CGRect)rect;
-(void)drawPrefixInRect:(CGRect)rect;
-(void)drawRect:(CGRect)rect;
-(void)drawSuffixInRect:(CGRect)rect;
-(void)drawTextInRect:(CGRect)rect;
-(BOOL)drawsAsAtom;
-(CGRect)editRect;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(id)endOfDocument;
-(void)endSelectionChange;
-(BOOL)fieldEditor:(id)editor shouldInsertText:(id)text replacingRange:(NSRange)range;
-(BOOL)fieldEditor:(id)editor shouldReplaceWithText:(id)text;
-(NSRange)fieldEditor:(id)editor willChangeSelectionFromCharacterRange:(NSRange)characterRange toCharacterRange:(NSRange)characterRange3;
-(void)fieldEditorDidChange:(id)fieldEditor;
-(void)fieldEditorDidChangeSelection:(id)fieldEditor;
-(CGRect)firstRectForRange:(id)range;
// declared property getter: -(id)font;
-(void)forwardInvocation:(id)invocation;
-(CGRect)frameForDictationResultPlaceholder:(id)dictationResultPlaceholder;
-(BOOL)hasMarkedText;
-(BOOL)hasSelection;
-(BOOL)hasText;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(CGRect)iconRect;
// declared property getter: -(id)inputAccessoryView;
// declared property getter: -(id)inputDelegate;
// declared property getter: -(id)inputView;
-(void)insertDictationResult:(id)result withCorrectionIdentifier:(id)correctionIdentifier;
-(id)insertDictationResultPlaceholder;
-(void)insertText:(id)text;
// declared property getter: -(id)interactionAssistant;
// declared property getter: -(BOOL)isEditable;
// declared property getter: -(BOOL)isEditing;
-(BOOL)isUndoEnabled;
-(BOOL)keyboardInput:(id)input shouldInsertText:(id)text isMarkedText:(BOOL)text3;
-(BOOL)keyboardInput:(id)input shouldReplaceTextInRange:(NSRange)range replacementText:(id)text;
-(BOOL)keyboardInputChanged:(id)changed;
-(void)keyboardInputChangedSelection:(id)selection;
-(BOOL)keyboardInputShouldDelete:(id)keyboardInput;
-(void)layoutSubviews;
-(void)layoutTilesNow;
// declared property getter: -(id)leftView;
// declared property getter: -(int)leftViewMode;
-(CGRect)leftViewRectForBounds:(CGRect)bounds;
-(void)makeTextWritingDirectionLeftToRight:(id)right;
-(void)makeTextWritingDirectionRightToLeft:(id)left;
// declared property getter: -(id)markedTextRange;
// declared property getter: -(id)markedTextStyle;
-(id)metadataDictionariesForDictationResults;
-(id)methodSignatureForSelector:(SEL)selector;
// declared property getter: -(float)minimumFontSize;
-(int)offsetFromPosition:(id)position toPosition:(id)position2;
-(unsigned)offsetInMarkedTextForSelection:(id)selection;
-(float)paddingBottom;
-(float)paddingLeft;
-(float)paddingRight;
-(float)paddingTop;
-(void)paste:(id)paste;
// declared property getter: -(id)placeholder;
-(CGRect)placeholderRectForBounds:(CGRect)bounds;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(id)positionFromPosition:(id)position inDirection:(int)direction offset:(int)offset;
-(id)positionFromPosition:(id)position offset:(int)offset;
-(id)positionWithinRange:(id)range farthestInDirection:(int)direction;
-(id)rectsForRange:(id)range;
-(void)removeDictationResultPlaceholder:(id)placeholder willInsertResult:(BOOL)result;
-(void)replace:(id)replace;
-(void)replaceRange:(id)range withText:(id)text;
-(BOOL)resignFirstResponder;
-(BOOL)respondsToSelector:(SEL)selector;
// declared property getter: -(id)rightView;
// declared property getter: -(int)rightViewMode;
-(CGRect)rightViewRectForBounds:(CGRect)bounds;
-(id)searchText;
-(void)select:(id)select;
-(void)selectAll;
-(void)selectAll:(id)all;
-(void)selectAllFromFieldEditor:(id)fieldEditor;
-(id)selectedText;
// declared property getter: -(id)selectedTextRange;
// declared property getter: -(int)selectionAffinity;
-(CGRect)selectionClipRect;
// declared property getter: -(int)selectionGranularity;
-(NSRange)selectionRange;
-(id)selectionRectsForRange:(id)range;
// declared property getter: -(id)selectionView;
-(BOOL)selectionVisible;
// declared property setter: -(void)setAdjustsFontSizeToFitWidth:(BOOL)fitWidth;
-(void)setAnimating:(BOOL)animating;
-(void)setAtomStyle:(int)style;
-(void)setAutoresizesTextToFit:(BOOL)fit;
// declared property setter: -(void)setBackground:(id)background;
-(void)setBackgroundColor:(id)color;
-(void)setBaseWritingDirection:(int)direction forRange:(id)range;
-(void)setBecomesFirstResponderOnClearButtonTap:(BOOL)tap;
// declared property setter: -(void)setBorderStyle:(int)style;
-(void)setBounds:(CGRect)bounds;
-(void)setCaretBlinks:(BOOL)blinks;
// declared property setter: -(void)setClearButtonMode:(int)mode;
-(void)setClearButtonOffset:(CGSize)offset;
-(void)setClearButtonStyle:(int)style;
// declared property setter: -(void)setClearsOnBeginEditing:(BOOL)editing;
-(void)setClearsPlaceholderOnBeginEditing:(BOOL)editing;
-(void)setContentVerticalAlignment:(int)alignment;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setDisabledBackground:(id)background;
-(void)setDrawsAsAtom:(BOOL)atom;
-(void)setEnabled:(BOOL)enabled;
// declared property setter: -(void)setFont:(id)font;
-(void)setFont:(id)font fullFontSize:(float)size;
-(void)setFrame:(CGRect)frame;
-(void)setIcon:(id)icon;
-(void)setInactiveHasDimAppearance:(BOOL)appearance;
// declared property setter: -(void)setInputAccessoryView:(id)view;
// declared property setter: -(void)setInputDelegate:(id)delegate;
// declared property setter: -(void)setInputView:(id)view;
-(void)setLabel:(id)label;
-(void)setLabelOffset:(float)offset;
// declared property setter: -(void)setLeftView:(id)view;
// declared property setter: -(void)setLeftViewMode:(int)mode;
-(void)setMarkedText:(id)text selectedRange:(NSRange)range;
// declared property setter: -(void)setMarkedTextStyle:(id)style;
// declared property setter: -(void)setMinimumFontSize:(float)size;
-(void)setPaddingBottom:(float)bottom;
-(void)setPaddingLeft:(float)left;
-(void)setPaddingRight:(float)right;
-(void)setPaddingTop:(float)top;
-(void)setPaddingTop:(float)top paddingLeft:(float)left;
// declared property setter: -(void)setPlaceholder:(id)placeholder;
-(void)setProgress:(float)progress;
// declared property setter: -(void)setRightView:(id)view;
// declared property setter: -(void)setRightViewMode:(int)mode;
// declared property setter: -(void)setSecureTextEntry:(BOOL)entry;
// declared property setter: -(void)setSelectedTextRange:(id)range;
// declared property setter: -(void)setSelectionAffinity:(int)affinity;
// declared property setter: -(void)setSelectionGranularity:(int)granularity;
-(void)setSelectionRange:(NSRange)range;
-(void)setSelectionVisible:(BOOL)visible;
-(void)setShadowBlur:(float)blur;
-(void)setShadowColor:(id)color;
-(void)setShadowOffset:(CGSize)offset;
// declared property setter: -(void)setText:(id)text;
// declared property setter: -(void)setTextAlignment:(int)alignment;
-(void)setTextAutorresizesToFit:(BOOL)fit;
-(void)setTextCentersHorizontally:(BOOL)horizontally;
-(void)setTextCentersVertically:(BOOL)vertically;
// declared property setter: -(void)setTextColor:(id)color;
-(void)setTextFont:(id)font;
-(void)setUndoEnabled:(BOOL)enabled;
-(float)shadowBlur;
-(id)shadowColor;
-(CGSize)shadowOffset;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)startAutoscroll:(CGPoint)autoscroll;
-(id)supportedPasteboardTypes;
-(id)supportedPasteboardTypesForCurrentSelection;
// declared property getter: -(id)text;
// declared property getter: -(int)textAlignment;
// declared property getter: -(id)textColor;
// declared property getter: -(id)textDocument;
-(id)textInRange:(id)range;
-(id)textInputTraits;
-(id)textLabel;
-(id)textRangeFromPosition:(id)position toPosition:(id)position2;
-(CGRect)textRect;
-(CGRect)textRectForBounds:(CGRect)bounds;
// declared property getter: -(id)tokenizer;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id)undoManager;
-(void)unmarkText;
-(id)webView;
-(void)willAttachFieldEditor:(id)editor;
-(void)willDetachFieldEditor:(id)editor;
@end

@interface UITextField (SyntheticEvents)
-(id)_scriptingInfo;
@end

@interface UITextField (UIKitAccessibilityInterfaceBuilderSupport)
-(BOOL)isAccessibilityElementByDefault;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

