/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, NSString;

__attribute__((visibility("hidden")))
@interface UIViewAnimationState : XXUnknownSuperclass {
@private
	UIViewAnimationState* _nextState;
	NSString* _animationID;
	void* _context;
	id _delegate;
	double _duration;
	double _delay;
	double _frameInterval;
	double _start;
	int _curve;
	float _repeatCount;
	int _transition;
	UIView* _transitionView;
	int _filter;
	UIView* _filterView;
	float _filterValue;
	SEL _willStartSelector;
	SEL _didEndSelector;
	int _didEndCount;
	CGPoint _position;
	unsigned _willStartSent : 1;
	unsigned _useCurrentLayerState : 1;
	unsigned _cacheTransition : 1;
	unsigned _autoreverses : 1;
	unsigned _roundsToInteger : 1;
	unsigned _layoutSubviews : 1;
}
@property(readonly, assign, nonatomic) BOOL _allowsUserInteraction;
+(void)popAnimationState;
+(void)pushViewAnimationState:(id)state context:(void*)context;
// declared property getter: -(BOOL)_allowsUserInteraction;
-(void)animationDidStart:(id)animation;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)dealloc;
-(void)sendDelegateAnimationDidStop:(id)sendDelegateAnimation finished:(BOOL)finished;
-(void)setAnimationAttributes:(id)attributes;
@end

