/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIWebSelectionBlock.h"
#import "UIKeyInput.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIKit-Structs.h"
#import "UITextInputTokenizer.h"
#import "UIKeyboardInput.h"

@class UITextRange, NSDictionary, UITextPosition, UIView, UITextSelectionView, UITextInteractionAssistant, UIResponder, UIColor, UIImage, NSString;
@protocol UITextInputDelegate, UITextSelectingContent;

@interface XXUnknownSuperclass (UISafeInstantiators)
-(id)_initWithUTF8String:(const char*)utf8String maxLength:(unsigned)length;
@end

@interface XXUnknownSuperclass (NSValueUIGeometryExtensions)
+(id)valueWithCGAffineTransform:(CGAffineTransform)cgaffineTransform;
+(id)valueWithCGPoint:(CGPoint)cgpoint;
+(id)valueWithCGRect:(CGRect)cgrect;
+(id)valueWithCGSize:(CGSize)cgsize;
+(id)valueWithUIEdgeInsets:(UIEdgeInsets)uiedgeInsets;
+(id)valueWithUIOffset:(UIOffset)uioffset;
-(CGAffineTransform)CGAffineTransformValue;
-(CGPoint)CGPointValue;
-(CGRect)CGRectValue;
-(CGSize)CGSizeValue;
-(UIEdgeInsets)UIEdgeInsetsValue;
-(UIOffset)UIOffsetValue;
@end

@interface XXUnknownSuperclass (UIGeometryKeyedCoding)
-(CGAffineTransform)decodeCGAffineTransformForKey:(id)key;
-(CGPoint)decodeCGPointForKey:(id)key;
-(CGRect)decodeCGRectForKey:(id)key;
-(CGSize)decodeCGSizeForKey:(id)key;
-(UIEdgeInsets)decodeUIEdgeInsetsForKey:(id)key;
-(UIOffset)decodeUIOffsetForKey:(id)key;
-(void)encodeCGAffineTransform:(CGAffineTransform)transform forKey:(id)key;
-(void)encodeCGPoint:(CGPoint)point forKey:(id)key;
-(void)encodeCGRect:(CGRect)rect forKey:(id)key;
-(void)encodeCGSize:(CGSize)size forKey:(id)key;
-(void)encodeUIEdgeInsets:(UIEdgeInsets)insets forKey:(id)key;
-(void)encodeUIOffset:(UIOffset)offset forKey:(id)key;
@end

@interface XXUnknownSuperclass (UIKitAdditions)
-(id)initWithImage:(id)image;
-(id)initWithImage:(id)image options:(id)options;
@end

@interface XXUnknownSuperclass (UIStringDrawing)
+(void)_popAscentRoundingEnabled;
+(void)_popWordRoundingAllowed;
+(void)_pushAscentRoundingEnabled:(BOOL)enabled;
+(void)_pushWordRoundingAllowed:(BOOL)allowed;
-(CGSize)_drawInRect:(CGRect)rect withFont:(id)font lineBreakMode:(int)mode alignment:(int)alignment lineSpacing:(int)spacing includeEmoji:(BOOL)emoji truncationRect:(CGRect*)rect7;
-(void)_makeNeededAdjustmentsToAttributes:(id)attributes andPoint:(CGPoint*)point forWidth:(float)width;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withAttributes:(id)attributes;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font fontSize:(float)size lineBreakMode:(int)mode baselineAdjustment:(int)adjustment;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font fontSize:(float)size lineBreakMode:(int)mode baselineAdjustment:(int)adjustment includeEmoji:(BOOL)emoji;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font lineBreakMode:(int)mode;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font lineBreakMode:(int)mode letterSpacing:(float)spacing;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font lineBreakMode:(int)mode letterSpacing:(float)spacing includeEmoji:(BOOL)emoji;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font minFontSize:(float)size actualFontSize:(float*)size5 lineBreakMode:(int)mode baselineAdjustment:(int)adjustment;
-(CGSize)drawAtPoint:(CGPoint)point forWidth:(float)width withFont:(id)font minFontSize:(float)size actualFontSize:(float*)size5 lineBreakMode:(int)mode baselineAdjustment:(int)adjustment includeEmoji:(BOOL)emoji;
-(CGSize)drawAtPoint:(CGPoint)point withFont:(id)font;
-(CGSize)drawInRect:(CGRect)rect withAttributes:(id)attributes;
-(CGSize)drawInRect:(CGRect)rect withFont:(id)font;
-(CGSize)drawInRect:(CGRect)rect withFont:(id)font lineBreakMode:(int)mode;
-(CGSize)drawInRect:(CGRect)rect withFont:(id)font lineBreakMode:(int)mode alignment:(int)alignment;
-(CGSize)drawInRect:(CGRect)rect withFont:(id)font lineBreakMode:(int)mode alignment:(int)alignment lineSpacing:(int)spacing;
-(CGSize)drawInRect:(CGRect)rect withFont:(id)font lineBreakMode:(int)mode alignment:(int)alignment lineSpacing:(int)spacing includeEmoji:(BOOL)emoji;
-(id)securedStringIncludingLastCharacter:(BOOL)character;
-(CGSize)sizeForWidth:(float)width withAttributes:(id)attributes;
-(CGSize)sizeInRect:(CGRect)rect withAttributes:(id)attributes;
-(CGSize)sizeWithFont:(id)font;
-(CGSize)sizeWithFont:(id)font constrainedToSize:(CGSize)size;
-(CGSize)sizeWithFont:(id)font constrainedToSize:(CGSize)size lineBreakMode:(int)mode;
-(CGSize)sizeWithFont:(id)font constrainedToSize:(CGSize)size lineBreakMode:(int)mode lineSpacing:(int)spacing;
-(CGSize)sizeWithFont:(id)font forWidth:(float)width lineBreakMode:(int)mode;
-(CGSize)sizeWithFont:(id)font forWidth:(float)width lineBreakMode:(int)mode letterSpacing:(float)spacing;
-(CGSize)sizeWithFont:(id)font minFontSize:(float)size actualFontSize:(float*)size3 forWidth:(float)width lineBreakMode:(int)mode;
-(id)stringWithFont:(id)font forWidth:(float)width lineBreakMode:(int)mode;
@end

@interface XXUnknownSuperclass (UIStringDrawingPrivate)
-(CGSize)_drawComponentsJoinedByString:(id)string atPoint:(CGPoint*)point forWidth:(float)width withFont:(id)font lineBreakMode:(int)mode;
-(CGSize)drawComponentsJoinedByString:(id)string atPoint:(CGPoint)point forWidth:(float)width withFont:(id)font lineBreakMode:(int)mode;
-(CGSize)sizeOfComponentsJoinedByString:(id)componentsJoinedByString withFont:(id)font forWidth:(float)width lineBreakMode:(int)mode;
@end

@interface XXUnknownSuperclass (UICollectionAdditions)
-(id)_nextToLastObject;
@end

@interface XXUnknownSuperclass (UICollectionAdditions_Performance)
-(id)_initWithObjectsFromArray:(id)array range:(NSRange)range;
-(void)_makeObjectsPerformSelector:(SEL)selector object:(id)object range:(NSRange)range;
@end

@interface XXUnknownSuperclass (UICollectionAdditions_Performance)
-(void)_addObjectsFromArray:(id)array range:(NSRange)range;
@end

@interface XXUnknownSuperclass (UICollectionAdditions)
-(BOOL)_boolForKey:(id)key;
@end

@interface XXUnknownSuperclass (UICalloutViewAdditions)
-(id)stringByStandardizingWhitespace;
@end

@interface XXUnknownSuperclass (UICalloutViewAdditions)
-(void)standardizeWhitespace;
@end

@interface XXUnknownSuperclass (UIWebFormExtensions)
-(id)createPeripheral;
-(id)createPickerCell;
-(id)createSelectedItem;
-(id)itemTitle;
-(void)populateCell:(id)cell;
@end

@interface XXUnknownSuperclass (UIWebFormExtensions)
-(void)getTextWritingDirection:(int*)direction override:(BOOL*)override;
@end

@interface XXUnknownSuperclass (UIWebFormExtensions)
-(id)createPickerCell;
-(id)createSelectedItem;
-(id)itemTitle;
-(void)populateCell:(id)cell;
@end

@interface XXUnknownSuperclass (UIWebFormExtensions)
-(id)createPickerCell;
-(id)createSelectedItem;
-(id)itemTitle;
-(void)populateCell:(id)cell;
@end

@interface XXUnknownSuperclass (UIWebFormPeripheral)
-(id)createPeripheral;
@end

@interface XXUnknownSuperclass (UIWebFormPeripheral)
-(id)createPeripheral;
@end

@interface XXUnknownSuperclass (UIKBExtras)
+(id)_stringWithUnichar:(unsigned long)unichar;
+(id)stringWithUnichar:(unsigned long)unichar;
-(BOOL)_containsSubstring:(id)substring;
-(unsigned)_editDistanceFrom:(id)from;
-(BOOL)_endsSentence;
-(BOOL)_endsWord;
-(BOOL)_isDelete;
-(BOOL)_isLeftAssociative;
-(BOOL)_isNaturallyRTL;
-(BOOL)_isNewlineOrReturn;
-(BOOL)_isPlainSpace;
-(BOOL)_isSpace;
-(BOOL)_isSpaceOrReturn;
-(BOOL)_isTripledPunctuation;
-(BOOL)_looksLikeEmailAddress;
-(BOOL)_looksLikeNumberInput;
-(BOOL)_looksLikeURL;
-(id)_stringByReplacingCharacter:(unsigned long)character withCharacter:(unsigned long)character2;
-(id)_stringByReplacingCharactersInSet:(CFCharacterSetRef)set withCharacter:(unsigned long)character;
-(id)_stringByTrimmingCharactersInCFCharacterSet:(CFCharacterSetRef)cfcharacterSet;
-(id)_stringByTrimmingLastCharacter;
-(BOOL)containsSubstring:(id)substring;
-(unsigned)editDistanceFrom:(id)from;
-(BOOL)endsSentence;
-(BOOL)endsWord;
-(BOOL)isDelete;
-(BOOL)isLeftAssociative;
-(BOOL)isNaturallyRTL;
-(BOOL)isNewlineOrReturn;
-(BOOL)isPlainSpace;
-(BOOL)isSpace;
-(BOOL)isSpaceOrReturn;
-(BOOL)isTripledPunctuation;
-(BOOL)looksLikeEmailAddress;
-(BOOL)looksLikeNumberInput;
-(BOOL)looksLikeURL;
-(id)stringByReplacingCharacter:(unsigned long)character withCharacter:(unsigned long)character2;
-(id)stringByReplacingCharactersInSet:(CFCharacterSetRef)set withCharacter:(unsigned long)character;
-(id)stringByTrimmingCharactersInCFCharacterSet:(CFCharacterSetRef)cfcharacterSet;
-(id)stringByTrimmingLastCharacter;
@end

@interface XXUnknownSuperclass (UIKBExtras)
-(id)_intersectionWithArray:(id)array;
-(id)_kb_firstObject;
-(BOOL)_kb_firstObjectsEqual:(unsigned)equal;
-(BOOL)_kb_firstTwoObjectsEqual;
-(NSRange)_rangeWithStartIndex:(int)startIndex endIndex:(int)index;
-(id)intersectionWithArray:(id)array;
-(NSRange)rangeWithStartIndex:(int)startIndex endIndex:(int)index;
@end

@interface XXUnknownSuperclass (UIKBExtras)
-(void)_kb_reverse;
@end

@interface XXUnknownSuperclass (UIKitAdditions)
+(id)URLWithDisplayIdentifier:(id)displayIdentifier forSearchResultDomain:(int)searchResultDomain andIdentifier:(unsigned long long)identifier;
+(id)URLWithTelephoneNumber:(id)telephoneNumber;
+(id)URLWithTelephoneNumber:(id)telephoneNumber addressBookUID:(int)uid;
+(id)URLWithTelephoneNumber:(id)telephoneNumber addressBookUID:(int)uid forceAssist:(BOOL)assist suppressAssist:(BOOL)assist4 wasAssisted:(BOOL)assisted;
+(id)URLWithTelephoneNumber:(id)telephoneNumber promptUser:(BOOL)user;
+(id)mapsURLWithAddress:(id)address;
+(id)mapsURLWithQuery:(id)query;
+(id)mapsURLWithSourceAddress:(id)sourceAddress destinationAddress:(id)address;
+(id)videoCallPromptURLWithURL:(id)url;
-(void)_domain:(id*)domain subdomain:(id*)subdomain;
-(BOOL)_isGoogleMapsDomain:(id)domain subdomain:(id)subdomain path:(id)path queryKeysAndValues:(id)values;
-(id)_queryParameters;
-(id)appleStoreURL;
-(id)fmfURL;
-(id)gamecenterURL;
-(void)getPhoneNumber:(id*)number addressBookUID:(int*)uid;
-(void)getPhoneNumber:(id*)number addressBookUID:(int*)uid forceAssist:(BOOL*)assist suppressAssist:(BOOL*)assist4 wasAlreadyAssisted:(BOOL*)assisted;
-(BOOL)hasTelephonyScheme;
-(BOOL)isGoogleMapsURL;
-(BOOL)isJavaScriptURL;
-(BOOL)isSpringboardHandledURL;
-(BOOL)isVideoCallURL;
-(BOOL)isWebSafeTelephoneURL;
-(BOOL)isWebcalURL;
-(id)itmsURL;
-(id)mapsURL;
-(id)phobosURL;
-(id)phoneNumber;
-(id)radarWebURL;
-(id)searchResultDomain;
-(id)searchResultIdentifier;
-(id)webSafeTelephoneURL;
-(id)youTubeURL;
@end

@interface XXUnknownSuperclass (UIKitAdditions)
-(id)queryKeysAndValues;
-(id)unescapedQueryValue;
@end

@interface XXUnknownSuperclass (UIKitPrivateAdditions)
-(BOOL)isInternalUIKitURL;
@end

@interface XXUnknownSuperclass (UIKit_DOMExtras)
-(id)tagName;
-(id)urlScheme;
@end

@interface XXUnknownSuperclass (UIFontPrivate)
-(id)stringByStrippingLeadingAndTrailingWhitespace;
@end

@interface XXUnknownSuperclass (UIKitAdditions)
-(id)initWithColor:(id)color;
@end

@interface XXUnknownSuperclass (UIWebViewAdditions)
-(CGRect)convertRect:(CGRect)rect toView:(id)view;
-(BOOL)isSecure;
-(BOOL)isTextControl;
-(int)keyboardType;
@end

@interface XXUnknownSuperclass (UITextInputAdditions) <UIKeyboardInput, UIKeyInput, UITextInputTokenizer>
@property(assign, nonatomic) BOOL acceptsEmoji;
@property(assign, nonatomic) BOOL acceptsFloatingKeyboard;
@property(assign, nonatomic) BOOL acceptsSplitKeyboard;
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) int autocorrectionType;
@property(readonly, assign, nonatomic) UITextPosition* beginningOfDocument;
@property(readonly, assign, nonatomic) UIView<UITextSelectingContent>* content;
@property(assign, nonatomic) BOOL contentsIsSingleValue;
@property(assign, nonatomic) BOOL displaySecureTextUsingPlainText;
@property(readonly, assign, nonatomic, getter=isEditable) BOOL editable;
@property(readonly, assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) int emptyContentReturnKeyType;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(readonly, assign, nonatomic) UITextPosition* endOfDocument;
@property(assign, nonatomic) BOOL forceEnableDictation;
@property(assign, nonatomic) id<UITextInputDelegate> inputDelegate;
@property(retain, nonatomic) UIColor* insertionPointColor;
@property(assign, nonatomic) unsigned insertionPointWidth;
@property(readonly, assign, nonatomic) UITextInteractionAssistant* interactionAssistant;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) BOOL learnsCorrections;
@property(readonly, assign, nonatomic) UITextRange* markedTextRange;
@property(copy, nonatomic) NSDictionary* markedTextStyle;
@property(assign, nonatomic) BOOL returnKeyGoesToNextResponder;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic, getter=isRichText) BOOL richText;
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(copy) UITextRange* selectedTextRange;
@property(assign, nonatomic) int selectionAffinity;
@property(retain, nonatomic) UIColor* selectionBarColor;
@property(retain, nonatomic) UIImage* selectionDragDotImage;
@property(assign, nonatomic) int selectionGranularity;
@property(retain, nonatomic) UIColor* selectionHighlightColor;
@property(readonly, assign, nonatomic) UITextSelectionView* selectionView;
@property(assign, nonatomic) int shortcutConversionType;
@property(assign, nonatomic) int spellCheckingType;
@property(assign, nonatomic) BOOL suppressReturnKeyStyling;
@property(readonly, assign, nonatomic) UIResponder<UITextSelection>* textDocument;
@property(readonly, assign, nonatomic) UIView* textInputView;
@property(assign, nonatomic) int textLoupeVisibility;
@property(assign, nonatomic) int textSelectionBehavior;
@property(assign, nonatomic) id textSuggestionDelegate;
@property(assign, nonatomic) CFCharacterSetRef textTrimmingSet;
@property(readonly, assign, nonatomic) id<UITextInputTokenizer> tokenizer;
-(CGRect)_lastRectForRange:(id)range;
-(NSRange)_markedTextNSRange;
-(id)_textSelectingContainer;
-(void)acceptedAutoFillWord:(id)word;
-(id)automaticallySelectedOverlay;
-(int)baseWritingDirectionForPosition:(id)position inDirection:(int)direction;
-(BOOL)becomesEditableWithGestures;
-(void)beginSelectionChange;
// declared property getter: -(id)beginningOfDocument;
-(CGRect)caretRect;
-(CGRect)caretRectForPosition:(id)position;
-(unsigned short)characterAfterCaretSelection;
-(unsigned short)characterBeforeCaretSelection;
-(unsigned short)characterInRelationToCaretSelection:(int)caretSelection;
-(id)characterRangeAtPoint:(CGPoint)point;
-(id)characterRangeByExtendingPosition:(id)position inDirection:(int)direction;
-(id)closestPositionToPoint:(CGPoint)point;
-(id)closestPositionToPoint:(CGPoint)point withinRange:(id)range;
-(int)comparePosition:(id)position toPosition:(id)position2;
-(void)confirmMarkedText:(id)text;
-(CGPoint)constrainedPoint:(CGPoint)point;
-(CGPoint)constrainedPoint:(CGPoint)point withInset:(float)inset;
// declared property getter: -(id)content;
// declared property getter: -(BOOL)contentsIsSingleValue;
-(CGRect)convertCaretRect:(CGRect)rect;
-(id)delegate;
-(void)deleteBackward;
-(void)detachInteractionAssistant;
-(void)detachSelectionView;
-(BOOL)editable;
-(BOOL)editing;
// declared property getter: -(id)endOfDocument;
-(void)endSelectionChange;
-(void)expandSelectionToStartOfWordContainingCaretSelection;
-(void)extendCurrentSelection:(int)selection;
-(CGRect)firstRectForRange:(id)range;
-(id)fontForCaretSelection;
-(CGRect)frameForDictationResultPlaceholder:(id)dictationResultPlaceholder;
-(void)handleKeyWebEvent:(id)event;
-(BOOL)hasContent;
-(BOOL)hasSelection;
-(BOOL)hasText;
-(int)initialSelectionBehavior;
// declared property getter: -(id)inputDelegate;
-(void)insertDictationResult:(id)result withCorrectionIdentifier:(id)correctionIdentifier;
-(id)insertDictationResultPlaceholder;
-(void)insertText:(id)text;
// declared property getter: -(id)interactionAssistant;
-(BOOL)isAutoFillMode;
// declared property getter: -(BOOL)isEditable;
// declared property getter: -(BOOL)isEditing;
-(BOOL)isPosition:(id)position atBoundary:(int)boundary inDirection:(int)direction;
-(BOOL)isPosition:(id)position withinTextUnit:(int)unit inDirection:(int)direction;
-(BOOL)isShowingPlaceholder;
-(id)markedText;
// declared property getter: -(id)markedTextRange;
// declared property getter: -(id)markedTextStyle;
-(id)metadataDictionariesForDictationResults;
-(void)moveBackward:(unsigned)backward;
-(void)moveDown;
-(void)moveForward:(unsigned)forward;
-(void)moveLeft;
-(void)moveRight;
-(void)moveUp;
-(id)nextUnperturbedDictationResultBoundaryFromPosition:(id)position;
-(int)offsetFromPosition:(id)position toPosition:(id)position2;
-(id)positionFromPosition:(id)position inDirection:(int)direction offset:(int)offset;
-(id)positionFromPosition:(id)position offset:(int)offset;
-(id)positionFromPosition:(id)position toBoundary:(int)boundary inDirection:(int)direction;
-(id)positionWithinRange:(id)range farthestInDirection:(int)direction;
-(id)previousUnperturbedDictationResultBoundaryFromPosition:(id)position;
-(id)rangeByExtendingCurrentSelection:(int)selection;
-(id)rangeByMovingCurrentSelection:(int)selection;
-(id)rangeEnclosingPosition:(id)position withGranularity:(int)granularity inDirection:(int)direction;
-(id)rangeOfEnclosingWord:(id)enclosingWord;
-(CGRect)rectContainingCaretSelection;
-(CGRect)rectForNSRange:(NSRange)nsrange;
-(id)rectsForNSRange:(NSRange)nsrange;
-(id)rectsForRange:(id)range;
-(void)removeDictationResultPlaceholder:(id)placeholder willInsertResult:(BOOL)result;
-(void)replaceCurrentWordWithText:(id)text;
-(void)replaceRange:(id)range withText:(id)text;
-(void)replaceRangeWithText:(NSRange)text replacementText:(id)text2;
-(void)replaceRangeWithTextWithoutClosingTyping:(id)textWithoutClosingTyping replacementText:(id)text;
-(BOOL)requiresKeyEvents;
// declared property getter: -(int)returnKeyType;
-(void)selectAll;
-(id)selectedDOMRange;
// declared property getter: -(id)selectedTextRange;
// declared property getter: -(int)selectionAffinity;
-(BOOL)selectionAtDocumentStart;
-(BOOL)selectionAtWordStart;
-(CGRect)selectionClipRect;
-(NSRange)selectionRange;
-(int)selectionState;
// declared property getter: -(id)selectionView;
-(void)setBaseWritingDirection:(int)direction forRange:(id)range;
-(void)setBecomesEditableWithGestures:(BOOL)gestures;
// declared property setter: -(void)setContentsIsSingleValue:(BOOL)value;
-(void)setInitialSelectionBehavior:(int)behavior;
// declared property setter: -(void)setInputDelegate:(id)delegate;
-(void)setMarkedText:(id)text;
-(void)setMarkedText:(id)text selectedRange:(NSRange)range;
// declared property setter: -(void)setMarkedTextStyle:(id)style;
// declared property setter: -(void)setReturnKeyType:(int)type;
-(void)setSecure:(BOOL)secure;
-(void)setSelectedDOMRange:(id)range affinityDownstream:(BOOL)downstream;
// declared property setter: -(void)setSelectedTextRange:(id)range;
-(void)setSelectedTextRange:(id)range withAffinityDownstream:(BOOL)affinityDownstream;
// declared property setter: -(void)setSelectionAffinity:(int)affinity;
-(void)setSelectionWithPoint:(CGPoint)point;
-(void)setSelectionWithPoint:(CGPoint)point inset:(float)inset;
-(void)setText:(id)text;
// declared property setter: -(void)setTextLoupeVisibility:(int)visibility;
// declared property setter: -(void)setTextSuggestionDelegate:(id)delegate;
// declared property setter: -(void)setTextTrimmingSet:(CFCharacterSetRef)set;
-(void)setupPlaceholderTextIfNeeded;
-(void)takeTraitsFrom:(id)from;
-(id)text;
-(id)textColorForCaretSelection;
// declared property getter: -(id)textDocument;
-(id)textInRange:(id)range;
-(id)textInputTraits;
// declared property getter: -(int)textLoupeVisibility;
-(id)textRangeFromPosition:(id)position toPosition:(id)position2;
// declared property getter: -(id)textSuggestionDelegate;
// declared property getter: -(CFCharacterSetRef)textTrimmingSet;
// declared property getter: -(id)tokenizer;
-(id)uiWebDocumentView;
-(void)unmarkText;
-(void)updateAutoscroll:(id)autoscroll;
-(void)updateSelection;
-(id)wordContainingCaretSelection;
-(int)wordOffsetInRange:(id)range;
-(id)wordRangeContainingCaretSelection;
@end

@interface XXUnknownSuperclass (UITextInputAdditions)
-(BOOL)isEditing;
-(BOOL)isSecure;
-(BOOL)isTextControl;
-(int)keyboardType;
-(void)setSelectionWithPoint:(CGPoint)point;
-(id)text;
-(id)textInputTraits;
@end

@interface XXUnknownSuperclass (UITextInputAdditions)
-(BOOL)isEditing;
-(BOOL)isTextControl;
-(void)setSelectionWithPoint:(CGPoint)point;
-(id)textInputTraits;
@end

@interface XXUnknownSuperclass (UINibLoadingActionEstablishing)
-(void)_connectInterfaceBuilderEventConnection:(id)connection;
@end

@interface XXUnknownSuperclass (UINSBundleAdditions)
-(id)loadNibNamed:(id)named owner:(id)owner options:(id)options;
@end

@interface XXUnknownSuperclass (UINibLoadingAdditions)
-(void)awakeFromNib;
@end

@interface XXUnknownSuperclass (TextEffectsLayerOrdering)
-(int)compareTextEffectsOrdering:(id)ordering;
@end

@interface XXUnknownSuperclass (UIAccessibility)
@property(assign, nonatomic) CGPoint accessibilityActivationPoint;	// @dynamic
@property(assign, nonatomic) BOOL accessibilityElementsHidden;	// @dynamic
@property(assign, nonatomic) CGRect accessibilityFrame;	// @dynamic
@property(copy, nonatomic) NSString* accessibilityHint;	// @dynamic
@property(copy, nonatomic) NSString* accessibilityLabel;	// @dynamic
@property(retain, nonatomic) NSString* accessibilityLanguage;	// @dynamic
@property(assign, nonatomic) unsigned long long accessibilityTraits;	// @dynamic
@property(copy, nonatomic) NSString* accessibilityValue;	// @dynamic
@property(assign, nonatomic) BOOL accessibilityViewIsModal;	// @dynamic
@property(assign, nonatomic) BOOL isAccessibilityElement;	// @dynamic
// declared property getter: -(CGPoint)accessibilityActivationPoint;
-(id)accessibilityContainer;
// declared property getter: -(BOOL)accessibilityElementsHidden;
// declared property getter: -(CGRect)accessibilityFrame;
// declared property getter: -(id)accessibilityHint;
-(id)accessibilityIdentifier;
// declared property getter: -(id)accessibilityLabel;
// declared property getter: -(id)accessibilityLanguage;
// declared property getter: -(unsigned long long)accessibilityTraits;
// declared property getter: -(id)accessibilityValue;
// declared property getter: -(BOOL)accessibilityViewIsModal;
// declared property getter: -(BOOL)isAccessibilityElement;
// declared property setter: -(void)setAccessibilityActivationPoint:(CGPoint)point;
-(void)setAccessibilityContainer:(id)container;
// declared property setter: -(void)setAccessibilityElementsHidden:(BOOL)hidden;
// declared property setter: -(void)setAccessibilityFrame:(CGRect)frame;
// declared property setter: -(void)setAccessibilityHint:(id)hint;
-(void)setAccessibilityIdentifier:(id)identifier;
// declared property setter: -(void)setAccessibilityLabel:(id)label;
// declared property setter: -(void)setAccessibilityLanguage:(id)language;
// declared property setter: -(void)setAccessibilityTraits:(unsigned long long)traits;
// declared property setter: -(void)setAccessibilityValue:(id)value;
// declared property setter: -(void)setAccessibilityViewIsModal:(BOOL)modal;
// declared property setter: -(void)setIsAccessibilityElement:(BOOL)element;
-(id)storedAccessibilityActivationPoint;
-(id)storedAccessibilityElementsHidden;
-(id)storedAccessibilityFrame;
-(id)storedAccessibilityTraits;
-(id)storedAccessibilityViewIsModal;
-(id)storedIsAccessibilityElement;
@end

@interface XXUnknownSuperclass (UIAccessibilityFocus)
-(void)accessibilityElementDidBecomeFocused;
-(void)accessibilityElementDidLoseFocus;
-(BOOL)accessibilityElementIsFocused;
@end

@interface XXUnknownSuperclass (UIAccessibilityAction)
-(void)accessibilityDecrement;
-(void)accessibilityIncrement;
-(BOOL)accessibilityPerformEscape;
-(BOOL)accessibilityScroll:(int)scroll;
@end

@interface XXUnknownSuperclass (UIAccessibilityContainer)
-(id)accessibilityElementAtIndex:(int)index;
-(int)accessibilityElementCount;
-(int)indexOfAccessibilityElement:(id)accessibilityElement;
@end

@interface XXUnknownSuperclass (UIAccessibilityPrivate)
-(void)_accessibilityFinalize;
-(void)accessibilitySetIdentification:(id)identification;
@end

@interface XXUnknownSuperclass (UIKitAccessibilityInterfaceBuilderSupport)
-(unsigned long long)defaultAccessibilityTraits;
-(BOOL)isAccessibilityElementByDefault;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
@end

@interface XXUnknownSuperclass (UITableView)
@property(readonly, assign, nonatomic) int row;
@property(readonly, assign, nonatomic) int section;
+(id)indexPathForRow:(int)row inSection:(int)section;
// declared property getter: -(int)row;
// declared property getter: -(int)section;
@end

@interface XXUnknownSuperclass (UIMovieScrubberTrackViewAdditions)
-(void)removeViewsFromSuperview;
@end

@interface XXUnknownSuperclass (UIThreadSafeNodeAdditions)
-(id)_realNode;
@end

@interface XXUnknownSuperclass (UIWebViewAdditions)
-(id)_uikit_stringByTrimmingWhitespaceAndNewlines;
-(id)_uikit_stringWithWritingDirection:(int)writingDirection asOverride:(BOOL)override;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(id)absoluteQuadsAtPoint:(CGPoint)point;
-(BOOL)isLikelyToBeginPageLoad;
-(BOOL)nodeCanBecomeFirstResponder;
-(BOOL)showsTapHighlight;
-(id)tapHighlightColor;
-(BOOL)touchCalloutEnabled;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(id)tapHighlightColor;
-(BOOL)touchCalloutEnabled;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)showsTapHighlight;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)showsTapHighlight;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)showsTapHighlight;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)showsTapHighlight;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)isLikelyToBeginPageLoad;
-(BOOL)nodeCanBecomeFirstResponder;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)nodeCanBecomeFirstResponder;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(BOOL)nodeCanBecomeFirstResponder;
@end

@interface XXUnknownSuperclass (UIWebInteraction)
-(id)absoluteQuadsAtPoint:(CGPoint)point;
@end

@interface XXUnknownSuperclass (BrowserExtras)
-(BOOL)inDocument;
-(BOOL)isHidden;
@end

@interface XXUnknownSuperclass (BrowserAdditions)
-(void)_collectFormFieldElementsIntoArray:(id)array upToLimit:(unsigned)limit onlyIncludeFocusedElements:(BOOL)elements;
-(id)_topFrame;
-(id)allFormFields;
-(BOOL)containsAnyFocusedFormFields;
-(BOOL)containsAnyFormFields;
-(BOOL)isMainFrame;
-(BOOL)isOrphaned;
@end

@interface XXUnknownSuperclass (CreditCardAutoFillExtras)
-(BOOL)formElementLooksLikeCreditCardNumberField:(id)field;
-(BOOL)formElementLooksLikeSecurityCodeField:(id)field;
@end

@interface XXUnknownSuperclass (UIWebFormDelegate)
-(void)_safari_setObject:(id)object forUncopiedKey:(id)uncopiedKey;
@end

@interface XXUnknownSuperclass (UIWebDocumentViewTextSelecting)
-(BOOL)isTexty;
@end

@interface XXUnknownSuperclass (UIWebDocumentViewTextSelecting)
-(BOOL)exceedsStructuralComplexity:(int)complexity;
@end

@interface XXUnknownSuperclass (UITextRangeViewScrollerSupport)
-(void)_disableScrollingIfNecessary;
-(void)_enableScrollingIfNecessary;
@end

@interface XXUnknownSuperclass (UIWebSelectionAdditions) <UIWebSelectionBlock>
-(id)asDomNode;
-(id)asDomRange;
-(id)asElement;
-(CGRect)boundingRect;
-(CGRect)boundingRectAndInsideFixedPosition:(int*)position;
-(BOOL)canShrinkDirectlyToTextOnly;
-(BOOL)containsBlock:(id)block;
-(BOOL)containsNode:(id)node;
-(BOOL)containsRange:(id)range;
-(id)enclosingDocument;
-(id)enclosingElementIncludingSelf;
-(id)firstDescendantOfAboutTheSameWidthOrHeight;
-(id)firstDescendantOfAboutTheSameWidthOrHeightAsRect:(CGRect)aboutTheSameWidthOrHeightAsRect withDescentDirection:(int)descentDirection;
-(BOOL)hasCustomLineHeight;
-(BOOL)isSameBlock:(id)block;
-(id)largerParent;
-(id)lastDescendantOfAboutTheSameWidthOrHeight;
-(id)parentBlock;
-(id)rangeOfContents;
-(BOOL)rendersAsBlock;
-(BOOL)selectable;
-(BOOL)strictlyContainsBlock:(id)block;
-(BOOL)strictlyContainsNode:(id)node;
-(id)webFrame;
@end

@interface XXUnknownSuperclass (UIWebSelectionAdditions) <UIWebSelectionBlock>
-(id)asDomNode;
-(id)asDomRange;
-(CGRect)boundingRect;
-(CGRect)boundingRectAndInsideFixedPosition:(int*)position;
-(BOOL)canShrinkDirectlyToTextOnly;
-(BOOL)containsBlock:(id)block;
-(BOOL)containsRange:(id)range;
-(id)enclosingDocument;
-(BOOL)isSameBlock:(id)block;
-(id)largerParent;
-(id)parentBlock;
-(id)rangeOfContents;
-(BOOL)rendersAsBlock;
-(BOOL)selectable;
-(BOOL)strictlyContainsBlock:(id)block;
-(void)unionWithRange:(id)range;
-(id)webFrame;
@end

@interface XXUnknownSuperclass (UIWebSelectionAdditions)
-(BOOL)hasCustomLineHeight;
-(BOOL)selectable;
@end

@interface XXUnknownSuperclass (UIWebSelectionAdditions)
-(BOOL)containsOnlySelectableElements;
@end

@interface XXUnknownSuperclass (UITextInput_Internal)
@property(readonly, assign, nonatomic) UIView<UITextSelectingContainer>* _textSelectingContainer;
-(unsigned long)_characterAfterCaretSelection;
-(unsigned long)_characterBeforeCaretSelection;
-(unsigned long)_characterInRelationToCaretSelection:(int)caretSelection;
-(unsigned long)_characterInRelationToRangedSelection:(int)rangedSelection;
-(id)_clampedpositionFromPosition:(id)position offset:(int)offset;
-(void)_deleteBackwardAndNotify:(BOOL)notify;
-(void)_deleteByWord;
-(void)_deleteForwardAndNotify:(BOOL)notify;
-(void)_deleteToEndOfLine;
-(void)_deleteToStartOfLine;
-(void)_expandSelectionToStartOfWordBeforeCaretSelection;
-(void)_expandSelectionToStartOfWordsBeforeCaretSelection:(int)wordsBeforeCaretSelection;
-(void)_extendCurrentSelection:(int)selection;
-(id)_findPleasingWordBoundaryFromPosition:(id)position;
-(id)_fontForCaretSelection;
-(id)_fullRange;
-(id)_fullText;
-(BOOL)_hasMarkedTextOrRangedSelection;
-(int)_indexForTextPosition:(id)textPosition;
-(BOOL)_isEmptySelection;
-(id)_keyInput;
-(CGRect)_lastRectForRange:(id)range;
-(void)_moveCurrentSelection:(int)selection;
-(id)_moveDown:(BOOL)down withHistory:(id)history;
-(id)_moveLeft:(BOOL)left withHistory:(id)history;
-(id)_moveRight:(BOOL)right withHistory:(id)history;
-(id)_moveToEndOfDocument:(BOOL)document withHistory:(id)history;
-(id)_moveToEndOfLine:(BOOL)line withHistory:(id)history;
-(id)_moveToEndOfParagraph:(BOOL)paragraph withHistory:(id)history;
-(id)_moveToEndOfWord:(BOOL)word withHistory:(id)history;
-(id)_moveToStartOfDocument:(BOOL)document withHistory:(id)history;
-(id)_moveToStartOfLine:(BOOL)line withHistory:(id)history;
-(id)_moveToStartOfParagraph:(BOOL)paragraph withHistory:(id)history;
-(id)_moveToStartOfWord:(BOOL)word withHistory:(id)history;
-(id)_moveUp:(BOOL)up withHistory:(id)history;
-(id)_newPhraseBoundaryGestureRecognizer;
-(NSRange)_nsrangeForTextRange:(id)textRange;
-(void)_phraseBoundaryGesture:(id)gesture;
-(id)_positionFromPosition:(id)position inDirection:(int)direction offset:(int)offset withAffinityDownstream:(BOOL)affinityDownstream;
-(id)_rangeOfEnclosingWord:(id)enclosingWord;
-(id)_rangeOfLineEnclosingPosition:(id)lineEnclosingPosition;
-(id)_rangeOfParagraphEnclosingPosition:(id)paragraphEnclosingPosition;
-(CGRect)_rectContainingCaretSelection;
-(void)_replaceCurrentWordWithText:(id)text;
-(void)_scrollRectToVisible:(CGRect)visible animated:(BOOL)animated;
-(id)_selectableText;
-(int)_selectionAffinity;
-(NSRange)_selectionAsNSRange;
-(BOOL)_selectionAtDocumentEnd;
-(BOOL)_selectionAtDocumentStart;
-(BOOL)_selectionAtWordStart;
-(void)_setCaretSelectionAtEndOfSelection;
-(void)_setGestureRecognizers;
-(id)_setHistory:(id)history withExtending:(BOOL)extending withAnchor:(int)anchor withAffinityDownstream:(BOOL)affinityDownstream;
-(void)_setMarkedText:(id)text selectedRange:(NSRange)range;
-(void)_setSelectedTextRange:(id)range withAffinityDownstream:(BOOL)affinityDownstream;
-(id)_setSelectionRangeWithHistory:(id)history;
-(id)_textColorForCaretSelection;
// declared property getter: -(id)_textSelectingContainer;
-(void)_unmarkText;
-(void)_updateSelectionWithTextRange:(id)textRange withAffinityDownstream:(BOOL)affinityDownstream;
-(id)_wordContainingCaretSelection;
-(int)selectionAffinity;
@end

@interface XXUnknownSuperclass (UITextInputView)
-(id)textInputView;
@end

@interface XXUnknownSuperclass (UIKBCandidateViewAdditions)
-(unsigned)countOfComposedCharacterSequences;
@end

@interface XXUnknownSuperclass (UIWebBrowserViewPrivate)
-(void)_accessoryClear;
-(id)_nextAssistedNode;
-(id)_previousAssistedNode;
-(BOOL)_requiresAccessoryView;
-(BOOL)_requiresInputView;
-(void)_startAssistingDocumentView:(id)view;
-(void)_stopAssistingDocumentView:(id)view;
-(BOOL)_supportsAccessoryClear;
-(BOOL)_supportsAutoFill;
-(id)_textFormElement;
@end

@interface XXUnknownSuperclass (UIWebBrowserViewPrivate)
-(void)_accessoryClear;
-(BOOL)_isAssistedDateType;
-(BOOL)_requiresAccessoryView;
-(BOOL)_requiresInputView;
-(void)_startAssistingDocumentView:(id)view;
-(void)_stopAssistingDocumentView:(id)view;
-(BOOL)_supportsAccessoryClear;
-(BOOL)_supportsAutoFill;
-(id)_textFormElement;
@end

@interface XXUnknownSuperclass (UIWebBrowserViewPrivate)
-(BOOL)_requiresAccessoryView;
-(BOOL)_requiresInputView;
-(void)_startAssistingDocumentView:(id)view;
-(void)_stopAssistingDocumentView:(id)view;
-(BOOL)_supportsAutoFill;
@end

@interface XXUnknownSuperclass (UIWebBrowserViewPrivate)
-(BOOL)_requiresAccessoryView;
-(BOOL)_requiresInputView;
-(void)_startAssistingDocumentView:(id)view;
-(void)_stopAssistingDocumentView:(id)view;
-(BOOL)_supportsAutoFill;
-(id)_textFormElement;
@end

@interface XXUnknownSuperclass (UIWebBrowserViewPrivate)
-(int)_web_messageLineNumber;
-(id)_web_messageSourceURL;
-(id)_web_messageText;
-(int)_web_messageType;
@end

@interface XXUnknownSuperclass (NSCalendarUnit)
+(unsigned)largerComponentsRelativeToComponent:(unsigned)component;
+(id)namesForComponents:(unsigned)components;
+(unsigned)smaller:(BOOL)smaller componentsRelativeToComponent:(unsigned)component;
+(unsigned)smallerComponentsRelativeToComponent:(unsigned)component;
-(id)conciseDescription;
-(void)setComponents:(id)components;
-(void)setValue:(int)value forComponent:(unsigned)component;
-(int)valueForComponent:(unsigned)component;
@end

@interface XXUnknownSuperclass (UITypeSafety)
-(id)_copyDecodedObjectForKey:(id)key ofClass:(Class)aClass;
@end

@interface XXUnknownSuperclass (UIPrinterBrowserViewController)
-(BOOL)isEqual:(id)equal;
@end

@interface XXUnknownSuperclass (UIPrintStatusViewController)
-(BOOL)isEqual:(id)equal;
@end

@interface XXUnknownSuperclass (UIKeyboardFactoryAdditions)
+(id)_rivenBundle;
+(id)_rivenFactory;
+(id)_textInputFactory;
+(id)_typologyBundle;
@end

@interface XXUnknownSuperclass (UIKitPrivate)
+(CGSize)_applicationIconCanvasSize;
+(int)_compareApplicationIconCanvasSize:(CGSize)size withSize:(CGSize)size2;
-(CGSize)_defaultStyleSize:(id)size;
-(id)_iconForStyle:(id)style;
-(id)_iconForStyle:(id)style size:(CGSize)size;
@end

@interface XXUnknownSuperclass (LSResourceProxyIconPrivate)
-(XXStruct_G3qrpA*)_iconDefinitionForSize:(CGSize)size style:(id)style;
-(XXStruct_G3qrpA*)_iconVariantDefinitions:(id)definitions;
-(CGSize)_largestImageSize:(id)size;
@end

@interface XXUnknownSuperclass (LSResourceProxyIconPrivate)
-(CGSize)_defaultStyleSize:(id)size;
-(XXStruct_G3qrpA*)_iconVariantDefinitions:(id)definitions;
@end

@interface XXUnknownSuperclass (LSResourceProxyIconPrivate)
-(CGSize)_defaultStyleSize:(id)size;
-(XXStruct_G3qrpA*)_iconVariantDefinitions:(id)definitions;
@end

@interface XXUnknownSuperclass (UIAppearanceAdditions)
+(void)_installAppearanceSwizzleForSetter:(id)setter;
@end

@interface XXUnknownSuperclass (UIPageCurlAdditions)
-(BOOL)uiHasFilterWithName:(id)name;
@end

@interface XXUnknownSuperclass (UIPageCurlAdditions)
+(id)uiFunctionWithControlPoints:(const CGPoint*)controlPoints;
@end

@interface XXUnknownSuperclass (UIKitQueueAdditions)
-(id)uiDequeue;
-(void)uiEnqueue:(id)enqueue;
-(id)uiPeek;
@end

@interface XXUnknownSuperclass (UIPageViewControllerArrayAdditions)
-(id)uiFirstObject;
-(id)uiOnlyObject;
@end

