/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSError.h"


__attribute__((visibility("hidden")))
@interface NSCFError : NSError {
}
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(BOOL)allowsWeakReference;
-(Class)classForCoder;
-(int)code;
-(id)domain;
-(void)finalize;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
-(BOOL)retainWeakReference;
-(id)userInfo;
@end

