/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSFileCoordinator.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL;

@interface NSFileCoordinator : XXUnknownSuperclass {
@private
	id _accessArbiter;
	id _fileReactor;
	id _purposeID;
	NSURL* _recentFilePresenterURL;
	id _accessClaimIDOrIDs;
	BOOL _isCancelled;
	id _reserved;
}
+(id)_canonicalURLForURL:(id)url;
+(void)addFilePresenter:(id)presenter;
+(id)filePresenters;
+(void)removeFilePresenter:(id)presenter;
-(id)init;
-(id)initWithFilePresenter:(id)filePresenter;
-(void)cancel;
-(void)coordinateReadingItemAtURL:(id)url options:(unsigned)options error:(id*)error byAccessor:(id)accessor;
-(void)coordinateReadingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 error:(id*)error byAccessor:(id)accessor;
-(void)coordinateWritingItemAtURL:(id)url options:(unsigned)options error:(id*)error byAccessor:(id)accessor;
-(void)coordinateWritingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 error:(id*)error byAccessor:(id)accessor;
-(void)dealloc;
-(void)itemAtURL:(id)url didMoveToURL:(id)url2;
-(void)prepareForReadingItemsAtURLs:(id)urls options:(unsigned)options writingItemsAtURLs:(id)urls3 options:(unsigned)options4 error:(id*)error byAccessor:(id)accessor;
@end

@interface NSFileCoordinator (NSPrivate)
+(void)__itemAtURL:(id)url didGainVersionWithClientID:(id)clientID name:(id)name purposeID:(id)anId;
+(void)__itemAtURL:(id)url didLoseVersionWithClientID:(id)clientID name:(id)name purposeID:(id)anId;
+(void)__itemAtURL:(id)url didMoveToURL:(id)url2 purposeID:(id)anId;
+(void)__itemAtURL:(id)url didResolveConflictVersionWithClientID:(id)clientID name:(id)name purposeID:(id)anId;
+(void)_addFileProvider:(id)provider;
+(id)_fileProviders;
+(void)_removeFileProvider:(id)provider;
+(BOOL)_skipCoordinationWork;
-(void)__coordinateReadingItemAtURL:(id)url options:(unsigned)options purposeID:(id)anId byAccessor:(id)accessor;
-(void)__coordinateReadingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 purposeID:(id)anId byAccessor:(id)accessor;
-(void)__coordinateWritingItemAtURL:(id)url options:(unsigned)options purposeID:(id)anId byAccessor:(id)accessor;
-(void)__coordinateWritingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 purposeID:(id)anId byAccessor:(id)accessor;
-(void)__prepareForReadingItemsAtURLs:(id)urls options:(unsigned)options writingItemsAtURLs:(id)urls3 options:(unsigned)options4 byAccessor:(id)accessor;
-(void)_blockOnAccessClaim:(id)claim;
-(void)_coordinateReadingItemAtURL:(id)url options:(unsigned)options error:(id*)error byAccessor:(id)accessor;
-(void)_coordinateReadingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 error:(id*)error byAccessor:(id)accessor;
-(void)_coordinateWritingItemAtURL:(id)url options:(unsigned)options error:(id*)error byAccessor:(id)accessor;
-(void)_coordinateWritingItemAtURL:(id)url options:(unsigned)options writingItemAtURL:(id)url3 options:(unsigned)options4 error:(id*)error byAccessor:(id)accessor;
-(void)_forgetAccessClaimForID:(id)anId;
-(void)_invokeAccessor:(id)accessor orDont:(BOOL)dont thenRelinquishAccessClaimForID:(id)anId;
-(void)_itemAtURL:(id)url didMoveToURL:(id)url2;
-(void)_requestAccessClaim:(id)claim withProcedure:(id)procedure;
-(void)_setFileProvider:(id)provider;
-(id)purposeIdentifier;
-(void)setPurposeIdentifier:(id)identifier;
@end

