/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSKeyValueContainerClass : XXUnknownSuperclass {
@private
	Class _originalClass;
	/*function-pointer*/ void* _cachedObservationInfoImplementation;
	/*function-pointer*/ void* _cachedSetObservationInfoImplementation;
	BOOL _cachedSetObservationInfoTakesAnObject;
	XXStruct_MCKcIA* _notifyingInfo;
}
-(id)initWithOriginalClass:(Class)originalClass;
-(id)description;
@end

