/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "CoreFoundation-Structs.h"
#import "NSDate.h"


__attribute__((visibility("hidden")))
@interface __NSDate : NSDate {
@private
	double _time;
}
+(id)__new:(double)aNew;
+(id)allocWithZone:(NSZone*)zone;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(id)initWithTimeIntervalSinceReferenceDate:(double)timeIntervalSinceReferenceDate;
-(void)dealloc;
-(double)timeIntervalSinceReferenceDate;
@end

