/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "NSOrderedSet.h"


__attribute__((visibility("hidden")))
@interface __NSOrderedSetReversed : NSOrderedSet {
@private
	id _orderedSet;
	unsigned _cnt;
}
-(id)initWithOrderedSet:(id)orderedSet;
-(unsigned)count;
-(void)dealloc;
-(unsigned)indexOfObject:(id)object;
-(id)objectAtIndex:(unsigned)index;
@end

