/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSRecursiveLock, PFUbiquityMetadataQueryMonitor;

__attribute__((visibility("hidden")))
@interface PFUbiquitySwitchboard : XXUnknownSuperclass {
@private
	PFUbiquityMetadataQueryMonitor* _queryMonitor;
	NSMutableDictionary* _rootPathToEntry;
	NSRecursiveLock* _registrationLock;
}
+(void)initialize;
+(id)sharedSwitchboard;
+(id)ubiquitousExternalReferenceLocationForUUID:(id)uuid inStore:(id)store;
+(id)urlForUbiquitousExternalReferenceLocation:(id)ubiquitousExternalReferenceLocation;
-(id)init;
-(id)createSetOfCoordinatorsForPersistentStoreName:(id)persistentStoreName andLocalPeerID:(id)anId atUbiquityRootLocation:(id)ubiquityRootLocation;
-(void)dealloc;
-(id)description;
-(id)entryForUbiquityRootLocation:(id)ubiquityRootLocation andLocalPeerID:(id)anId;
-(void)registerUbiquitizedPersistentStore:(id)store forLocalPeerID:(id)localPeerID;
-(void)releaseAllEntriesForRootLocation:(id)rootLocation andPeer:(id)peer;
-(void)unregisterCoordinator:(id)coordinator;
@end

