/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString, NSSet;

__attribute__((visibility("hidden")))
@interface PFUbiquityExportContext : XXUnknownSuperclass {
@private
	NSSet* _storesToExportFrom;
	NSMutableDictionary* _storeNameToStoreExportContext;
	NSMutableDictionary* _ubiquityRootPathToStack;
	NSString* _localPeerID;
}
@property(readonly, assign, nonatomic) NSString* localPeerID;	// @synthesize=_localPeerID
@property(retain, nonatomic) NSSet* storesToExportFrom;	// @synthesize=_storesToExportFrom
-(id)initWithLocalPeerID:(id)localPeerID;
-(void)dealloc;
-(id)description;
// declared property getter: -(id)localPeerID;
// declared property setter: -(void)setStoresToExportFrom:(id)from;
-(id)storeExportContextForStore:(id)store;
-(id)storeExportContextForStoreName:(id)storeName;
// declared property getter: -(id)storesToExportFrom;
@end

