/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/StoreKit.framework/StoreKit
 */

#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "StoreKit-Structs.h"

@class NSString, NSNumber;

@interface SKPaymentQueueClient : XXUnknownSuperclass <NSCopying> {
@private
	NSString* _bundleIdentifier;
	NSString* _bundleVersion;
	NSNumber* _storeExternalVersion;
	NSNumber* _storeItemIdentifier;
}
@property(copy, nonatomic) NSString* bundleIdentifier;	// @synthesize=_bundleIdentifier
@property(copy, nonatomic) NSString* bundleVersion;	// @synthesize=_bundleVersion
@property(copy, nonatomic) NSNumber* storeExternalVersion;	// @synthesize=_storeExternalVersion
@property(copy, nonatomic) NSNumber* storeItemIdentifier;	// @synthesize=_storeItemIdentifier
-(id)initWithXPCEncoding:(id)xpcencoding;
// declared property getter: -(id)bundleIdentifier;
// declared property getter: -(id)bundleVersion;
-(id)copyWithZone:(NSZone*)zone;
-(id)copyXPCEncoding;
-(void)dealloc;
// declared property setter: -(void)setBundleIdentifier:(id)identifier;
// declared property setter: -(void)setBundleVersion:(id)version;
// declared property setter: -(void)setStoreExternalVersion:(id)version;
// declared property setter: -(void)setStoreItemIdentifier:(id)identifier;
// declared property getter: -(id)storeExternalVersion;
// declared property getter: -(id)storeItemIdentifier;
@end

