/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import "CoreImage-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface RedEyeRepair : XXUnknownSuperclass {
@private
	BOOL ownLF;
	XXStruct_kb0fHB* lf;
	int imageSourceType;
	CGImageBlockSetRef blockSet;
	void* releaseMe;
	CFDataRef dataRef;
	NSArray* faces;
	int nRepairs;
	int nextRepairTag;
	XXStruct_WqZPoA repairs[32];
	int lastRepairTag;
	float lastRepairIOD;
	XXStruct_ck5uzC standardTemplate;
	int iFaceIndex;
	BOOL iLeft;
	BOOL debugRedEye;
	BOOL logRepairs;
	int redEyeThresholdKind;
	BOOL renderAlpha;
	BOOL infillBackground;
	BOOL renderSpecularShine;
	float specularSize;
	float specularSoftness;
	BOOL pupilShadeAlignment;
	BOOL autoPupilTonality;
	BOOL forceLoValue;
	int loValue;
	XXStruct_7sjjeB lastClickYBitmap;
	XXStruct_7sjjeB lastClickCbCrBitmap;
	int lastClickBitmapMinX;
	int lastClickBitmapMaxX;
	int lastClickBitmapMinY;
	int lastClickBitmapMaxY;
	XXStruct_7sjjeB lastClickYBitmaps[3];
	XXStruct_7sjjeB lastClickCbCrBitmaps[3];
	XXStruct_ck5uzC lastClickIRects[3];
	XXStruct_7sjjeB lastSearchYBitmap;
	XXStruct_7sjjeB lastSearchCbCrBitmap;
	int lastSearchBitmapMinX;
	int lastSearchBitmapMaxX;
	int lastSearchBitmapMinY;
	int lastSearchBitmapMaxY;
	int nPolyPoints;
	BOOL polyClosed;
	CGPoint polyPoints[20];
	struct {
		float a;
		float b;
		float c;
	} polyLines[20];
	BOOL polyPointConcave[20];
	unsigned char CbCrDistanceTable[65536];
	int nLinears;
	int linearCoefficients[8][3];
}
+(CGRect)supportRectangleWithFaceArray:(id)faceArray imageSize:(CGSize)size;
+(CGRect)supportRectangleWithPoint:(CGPoint)point imageSize:(CGSize)size IOD:(float)iod;
+(CGRect)supportRectangleWithRepair:(id)repair imageSize:(CGSize)size;
+(float)upperRepairDistance:(float)distance;
+(float)upperRepairDistanceFraction:(float)fraction;
-(id)initWithCGImage:(CGImageRef)cgimage cameraModel:(id)model;
-(id)initWithDeskView:(id)deskView andFrame:(XXStruct_kb0fHB*)frame;
-(id)initWithExternalBuffer:(char*)externalBuffer size:(CGSize)size rowBytes:(unsigned long)bytes;
-(id)initWithExternalBuffer:(char*)externalBuffer subRectangle:(CGRect)rectangle fullSize:(CGSize)size rowBytes:(unsigned long)bytes cameraModel:(id)model;
-(id)initWithFrameExternalBuffer:(XXStruct_kb0fHB*)frameExternalBuffer;
-(id)initWithIOSurface:(IOSurfaceRef)iosurface format:(int)format colorSpace:(CGColorSpaceRef)space cameraModel:(id)model;
-(BOOL)autoPupilTonality;
-(void)autoRepairExtractAndSearchLeft:(XXStruct_ck5uzC)left right:(XXStruct_ck5uzC)right data:(XXStruct_$ifKmC*)data repairSize:(float)size autoPupilTonality:(BOOL)tonality faceIndex:(int)index;
-(void)autoRepairWithFaceArray:(id)faceArray;
-(int)averageValueFromY:(XXStruct_7sjjeB*)y withinSkinMask:(XXStruct_7sjjeB*)mask butOutsideAlpha:(XXStruct_7sjjeB*)alpha;
-(BOOL)computeTrimmedBitmaps:(XXStruct_7sjjeB*)bitmaps newY:(XXStruct_7sjjeB*)y newCbCr:(XXStruct_7sjjeB*)cr IR:(XXStruct_ck5uzC)ir newTrimY:(XXStruct_7sjjeB*)y5 newTrimCbCr:(XXStruct_7sjjeB*)cr6 returningYR:(XXStruct_ck5uzC*)yr andCbCrR:(XXStruct_ck5uzC*)r;
-(float)confidenceWithIOD:(float)iod repair:(int)repair andProminenceDifference:(int)difference;
-(CGImageRef)createRepairedImage;
-(void)dealloc;
-(BOOL)debug;
-(int)distanceMaskFromPolyToCb:(int)cb Cr:(int)cr;
-(void)executeRepair:(id)repair;
-(void)executeRepairArray:(id)array;
-(float)extractAverageFaceY:(XXStruct_$ifKmC*)y contrast:(float*)contrast faceIndex:(int)index;
-(BOOL)extractReusableAlignedBitmapsAroundPoint:(XXStruct_7sjjeB*)point YR:(XXStruct_ck5uzC)yr subYBitmap:(XXStruct_7sjjeB*)bitmap subCbCrBitmap:(XXStruct_7sjjeB*)bitmap4;
-(id)faces;
-(BOOL)forceLoValue;
-(int)format;
-(BOOL)gatherProminencesWithC:(XXStruct_7sjjeB*)c MC:(XXStruct_7sjjeB*)mc altC:(XXStruct_7sjjeB*)c3 altMC:(XXStruct_7sjjeB*)mc4 maxwindowsize:(int)maxwindowsize repairsize:(int)repairsize IR:(XXStruct_ck5uzC)ir fr:(XXStruct_$ifKmC*)fr intoHopper:(XXStruct_2IQLbD*)hopper faceIndex:(int)index left:(BOOL)left;
-(BOOL)getBlockSetWithImage:(CGImageRef)image into:(XXStruct_7sjjeB*)into width:(unsigned long)width height:(unsigned long)height;
-(BOOL)getBool:(BOOL*)aBool d:(id)d s:(id)s;
-(BOOL)getDataProviderBytePtrWithImage:(CGImageRef)image into:(XXStruct_7sjjeB*)into width:(unsigned long)width height:(unsigned long)height;
-(BOOL)getDataProviderCopyWithImage:(CGImageRef)image into:(XXStruct_7sjjeB*)into;
-(BOOL)getFloat:(float*)aFloat d:(id)d s:(id)s;
-(BOOL)getInt:(int*)int d:(id)d s:(id)s;
-(BOOL)infillBackground;
-(void)initializeNonDebugVariables;
-(void)insertIntoProminenceVettingHopper:(XXStruct_2IQLbD*)hopper max:(int)max outside:(int)outside confidence:(float)confidence distance:(float)distance row:(int)row column:(int)column IOD:(float)iod;
-(int)lastRepairTag;
-(int)loValue;
-(BOOL)logRepairs;
-(float)lowerRepairSize:(float)size;
-(float)lowerRepairSizeFraction:(float)fraction;
-(int)nRepairs;
-(void)prepareLineFunctions;
-(BOOL)pupilShadeAlignment;
-(int)redEyeRemovalWithData:(XXStruct_eP6C5A)data;
-(int)redEyeRemovalWithPoint:(CGPoint)point alignPupilShades:(BOOL)shades matching:(XXStruct_ck5uzC)matching force:(int)force IOD:(float)iod tap:(BOOL)tap;
-(int)redEyeThresholdKind;
-(void)redoLastRepair;
-(int)redoRepairWithTag:(int)tag IOD:(float)iod;
-(BOOL)renderAlpha;
-(BOOL)renderSpecularShine;
-(id)repairArray;
-(void)repairExternalBuffer;
-(XXStruct_WqZPoA*)repairWithTag:(int)tag;
-(XXStruct_WqZPoA*)repairs;
-(void)setAutoPupilTonality:(BOOL)tonality;
-(void)setColorSpace:(CGColorSpaceRef)space;
-(void)setDebug:(BOOL)debug;
-(void)setFaceIndex:(int)index;
-(void)setForceLoValue:(BOOL)value;
-(void)setInfillBackground:(BOOL)background;
-(void)setLeft:(BOOL)left;
-(void)setLoValue:(int)value;
-(void)setLogRepairs:(BOOL)repairs;
-(void)setPupilShadeAlignment:(BOOL)alignment;
-(void)setRedEyeThresholdKind:(int)kind;
-(void)setRenderAlpha:(BOOL)alpha;
-(void)setRenderSpecularShine:(BOOL)shine;
-(void)setSpecularSize:(float)size;
-(void)setSpecularSoftness:(float)softness;
-(void)skinInit;
-(float)specularSize;
-(float)specularSoftness;
-(XXStruct_ck5uzC)standardTemplate;
-(void)undoRepair:(int)repair;
-(float)upperRepairSize:(float)size;
-(float)upperRepairSizeFraction:(float)fraction;
@end

