/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
 */

#import "CBService.h"

@class CBUUID, NSArray, NSNumber;

@interface CBMutableService : CBService {
@private
	NSNumber* _ID;
}
@property(retain) NSNumber* ID;	// @synthesize=_ID
@property(retain, nonatomic) CBUUID* UUID;
@property(retain) NSArray* characteristics;
@property(retain) NSArray* includedServices;
@property(assign, nonatomic) BOOL isPrimary;
-(id)initWithType:(id)type primary:(BOOL)primary;
// declared property getter: -(id)ID;
-(id)description;
// declared property setter: -(void)setCharacteristics:(id)characteristics;
// declared property setter: -(void)setID:(id)anId;
@end

