/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "NSMutableCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "CoreData-Structs.h"

@class NSManagedObjectID;

__attribute__((visibility("hidden")))
@interface _CDSnapshot : XXUnknownSuperclass <NSCopying, NSMutableCopying> {
@private
	int _cd_rc;
	int _cd_version;
	NSManagedObjectID* _cd_objectID;
	snapshotFlags_st _cd_flags;
	unsigned _cd_nullFlags_;
}
+(void)_entityDeallocated;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
+(Class)classForEntity:(id)entity;
+(void)initialize;
+(unsigned)newBatchAllocation:(id*)allocation count:(unsigned)count withOwnedObjectIDs:(id*)ownedObjectIDs;
-(id)initWithObjectID:(id)objectID;
-(id)_descriptionValues;
-(BOOL)_isDeallocating;
-(BOOL)_tryRetain;
-(id)copy;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)description;
-(id)entity;
-(void)finalize;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)mutableCopy;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)objectID;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
-(void)setValue:(id)value forKey:(id)key;
-(id)valueForKey:(id)key;
@end

