/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface _PFManagedObjectReferenceQueue : XXUnknownSuperclass {
@private
	int _cd_rc;
	int _spinLock;
	int _flags;
	int _signalRunloop;
	NSManagedObjectContext* _context;
	CFArrayRef _queue;
	CFRunLoopObserverRef _rlObserver;
}
-(id)initForContext:(id)context;
-(BOOL)_GC_queueForDealloc:(id)dealloc;
-(void)_contextDidDealloc;
-(BOOL)_isDeallocating;
-(void)_processReferenceQueue:(BOOL)queue;
-(BOOL)_queueBatchForDealloc:(CFArrayRef)dealloc;
-(int)_queueCount;
-(BOOL)_queueForDealloc:(id)dealloc;
-(BOOL)_signal;
-(BOOL)_tryRetain;
-(void)_unregisterRunloopObservers;
-(void)dealloc;
-(void)finalize;
-(void)release;
-(id)retain;
-(unsigned)retainCount;
@end

