/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray, NSManagedObjectContext, NSFetchRequest;
@protocol NSFetchedResultsControllerDelegate;

@interface NSFetchedResultsController : XXUnknownSuperclass {
@private
	NSFetchRequest* _fetchRequest;
	NSManagedObjectContext* _managedObjectContext;
	NSString* _sectionNameKeyPath;
	NSString* _sectionNameKey;
	NSString* _cacheName;
	void* _cache;
	fetchResultsControllerFlags _flags;
	id _delegate;
	id _sortKeys;
	id _fetchedObjects;
	id _sections;
	id _sectionsByName;
	id _sectionIndexTitles;
	id _sectionIndexTitlesSections;
}
@property(readonly, assign, nonatomic) NSString* cacheName;	// @synthesize=_cacheName
@property(assign, nonatomic) id<NSFetchedResultsControllerDelegate> delegate;	// @synthesize=_delegate
@property(readonly, assign, nonatomic) NSFetchRequest* fetchRequest;	// @synthesize=_fetchRequest
@property(readonly, assign, nonatomic) NSArray* fetchedObjects;
@property(readonly, assign, nonatomic) NSManagedObjectContext* managedObjectContext;	// @synthesize=_managedObjectContext
@property(readonly, assign, nonatomic) NSArray* sectionIndexTitles;
@property(readonly, assign, nonatomic) NSString* sectionNameKeyPath;	// @synthesize=_sectionNameKeyPath
@property(readonly, assign, nonatomic) NSArray* sections;
+(id)_CoreDataSectionCachesPath;
+(unsigned)_insertIndexForObject:(id)object inArray:(id)array lowIdx:(unsigned)idx highIdx:(unsigned)idx4 sortDescriptors:(id)descriptors;
+(void)deleteCacheWithName:(id)name;
+(void)initialize;
-(id)initWithFetchRequest:(id)fetchRequest managedObjectContext:(id)context sectionNameKeyPath:(id)path cacheName:(id)name;
-(void)_appendAffectedStoreInfoToData:(id)data adjustedOffset:(long long*)offset;
-(BOOL)_computeSectionInfo:(id)info error:(id*)error;
-(BOOL)_computeSectionInfoWithGroupBy:(id)groupBy error:(id*)error;
-(id)_createNewSectionForObject:(id)object;
-(BOOL)_didFailPostprocessing;
-(BOOL)_didUpdateOnlyStoreInfo;
-(BOOL)_didUseCachedSectionInfo;
-(BOOL)_didUseGroupBy;
-(void)_dumpSectionInfo;
-(id)_fetchedObjectsArrayOfObjectIDs;
-(BOOL)_hasFetchedObjects;
-(unsigned)_indexOfFetchedID:(id)fetchedID;
-(id)_indexPathForIndex:(unsigned)index;
-(void)_insertObjectInFetchedObjects:(id)fetchedObjects atIndex:(unsigned)index;
-(BOOL)_keyPathContainsNonPersistedProperties:(id)properties;
-(void)_makeMutableFetchedObjects;
-(void)_managedObjectContextDidChange:(id)_managedObjectContext;
-(void)_managedObjectContextDidSave:(id)_managedObjectContext;
-(BOOL)_objectInResults:(id)results;
-(BOOL)_postprocessDeletedObjects:(id)objects;
-(BOOL)_postprocessInsertedObjects:(id)objects;
-(BOOL)_postprocessUpdatedObjects:(id)objects;
-(void)_preprocessDeletedObjects:(id)objects deletesInfo:(id)info sectionsWithDeletes:(id)deletes;
-(void)_preprocessInsertedObjects:(id)objects insertsInfo:(id)info newSectionNames:(id)names;
-(void)_preprocessUpdatedObjects:(id)objects insertsInfo:(id)info deletesInfo:(id)info3 updatesInfo:(id)info4 sectionsWithDeletes:(id)deletes newSectionNames:(id)names treatAsRefreshes:(BOOL)refreshes;
-(void)_removeObjectInFetchedObjectsAtIndex:(unsigned)index;
-(id)_resolveSectionIndexTitleForSectionName:(id)sectionName;
-(BOOL)_restoreCachedSectionInfo;
-(id)_sectionCachePath;
-(id)_sectionNameForObject:(id)object;
-(unsigned)_sectionNumberForIndex:(unsigned)index;
-(void)_updateCachedStoreInfo;
-(void)_updateSectionOffsetsStartingAtSection:(id)section;
// declared property getter: -(id)cacheName;
-(void)dealloc;
// declared property getter: -(id)delegate;
// declared property getter: -(id)fetchRequest;
// declared property getter: -(id)fetchedObjects;
-(id)indexPathForObject:(id)object;
// declared property getter: -(id)managedObjectContext;
-(id)objectAtIndexPath:(id)indexPath;
-(BOOL)performFetch:(id*)fetch;
-(int)sectionForSectionIndexTitle:(id)sectionIndexTitle atIndex:(int)index;
-(id)sectionIndexTitleForSectionName:(id)sectionName;
// declared property getter: -(id)sectionIndexTitles;
// declared property getter: -(id)sectionNameKeyPath;
// declared property getter: -(id)sections;
// declared property setter: -(void)setDelegate:(id)delegate;
@end

