/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import "NSKnownKeysDictionary.h"

@class NSKnownKeysMappingStrategy;

__attribute__((visibility("hidden")))
@interface NSKnownKeysDictionary1 : NSKnownKeysDictionary {
@private
	int _cd_rc;
	int _count;
	NSKnownKeysMappingStrategy* _keySearch;
	id _values[0];
}
+(id)init;
+(id)initForKeys:(id)keys;
+(id)initWithCapacity:(unsigned)capacity;
+(id)initWithCoder:(id)coder;
+(id)initWithDictionary:(id)dictionary;
+(id)initWithDictionary:(id)dictionary copyItems:(BOOL)items;
+(id)initWithObjects:(id*)objects forKeys:(id*)keys count:(unsigned)count;
+(id)initWithSearchStrategy:(id)searchStrategy;
+(BOOL)accessInstanceVariablesDirectly;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
-(unsigned)_countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count forKeys:(BOOL)keys;
-(BOOL)_isDeallocating;
-(void)_recount;
-(void)_setValues:(id*)values retain:(BOOL)retain;
-(BOOL)_tryRetain;
-(unsigned)_valueCountByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)addEntriesFromDictionary:(id)dictionary;
-(id)allKeys;
-(id)allValues;
-(Class)classForArchiver;
-(Class)classForCoder;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)count;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)getKeys:(id*)keys;
-(void)getObjects:(id*)objects;
-(void)getObjects:(id*)objects andKeys:(id*)keys;
-(BOOL)isEqualToDictionary:(id)dictionary;
-(id)keyEnumerator;
-(const id*)knownKeyValuesPointer;
-(id)mapping;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)objectEnumerator;
-(id)objectForKey:(id)key;
-(oneway void)release;
-(void)removeAllObjects;
-(void)removeObjectForKey:(id)key;
-(id)retain;
-(unsigned)retainCount;
-(void)setObject:(id)object forKey:(id)key;
-(void)setValue:(id)value atIndex:(unsigned)index;
-(void)setValues:(id*)values;
-(id)valueAtIndex:(unsigned)index;
-(const id*)values;
@end

