/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSManagedObjectContext, NSPersistentStore, NSMutableArray, NSPersistentStoreCoordinator, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PFUbiquityPeerRangeReservationContext : XXUnknownSuperclass {
@private
	NSMutableArray* _fakeManagedObjects;
	NSMutableDictionary* _peerEntityNameRangeStartSet;
	NSMutableDictionary* _globalIDToLocalURI;
	NSMutableArray* _unresolvedGlobalObjectIDs;
	NSManagedObjectContext* _moc;
	NSPersistentStore* _store;
	NSPersistentStoreCoordinator* _psc;
	NSMutableDictionary* _storeNameToFetchedMetadata;
	NSArray* _globalObjectIDs;
}
@property(readonly, assign, nonatomic) NSArray* fakeManagedObjects;	// @synthesize=_fakeManagedObjects
@property(readonly, assign, nonatomic) NSArray* globalObjectIDs;	// @synthesize=_globalObjectIDs
@property(readonly, assign, nonatomic) NSManagedObjectContext* moc;	// @synthesize=_moc
@property(readonly, assign, nonatomic) NSPersistentStoreCoordinator* psc;	// @synthesize=_psc
@property(readonly, assign, nonatomic) NSPersistentStore* store;	// @synthesize=_store
-(id)init;
-(id)initWithPersistentStore:(id)persistentStore andStoreSaveSnapshot:(id)snapshot;
-(id)createLocalIDStringForStoreUUID:(id)storeUUID entityName:(id)name andPrimaryKeyString:(id)string;
-(BOOL)createNewPeerRangesWithCache:(id)cache Error:(id*)error;
-(void)dealloc;
// declared property getter: -(id)fakeManagedObjects;
// declared property getter: -(id)globalObjectIDs;
// declared property getter: -(id)moc;
-(void)prepareForRangeReservationWithRangeStart:(id)rangeStart andGlobalID:(id)anId andEntityName:(id)name;
// declared property getter: -(id)psc;
// declared property getter: -(id)store;
@end

