/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Twitter.framework/Twitter
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Twitter-Structs.h"


@interface TWSystemConfigManager : XXUnknownSuperclass {
	void* _prefs;
	BOOL _notifyForExternalChangeOnly;
	int _applySkipCount;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void*)getValueForKey:(id)key;
-(void)initializeSCPrefs:(id)prefs;
-(void)keepAlive;
-(void)notifyTarget:(unsigned)target;
-(void)refresh;
-(void)setCallback:(/*function-pointer*/ void*)callback withContext:(XXStruct_K1psTC*)context;
-(void)setTweetSheetPermissionCacheState:(int)state;
-(void)setValue:(void*)value forKey:(id)key;
-(void)synchronize;
-(void)tearDown;
-(int)tweetSheetPermissionCacheState;
@end

