/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, UITextField, NSNumber, UIAlertView;
@protocol CBPairingAlertDelegate;

@interface CBPairingAlert : XXUnknownSuperclass {
	UIAlertView* _alert;
	UIButton* _doneButton;
	UITextField* _passkeyField;
	NSNumber* _pairingType;
	id<CBPairingAlertDelegate> _delegate;
}
@property(assign, nonatomic) id<CBPairingAlertDelegate> delegate;	// @synthesize=_delegate
-(id)initWithDeviceName:(id)deviceName pairingType:(id)type passkey:(id)passkey;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)dismiss;
// declared property setter: -(void)setDelegate:(id)delegate;
-(void)show;
-(void)textDidChange:(id)text;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

