/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

#import "CoreMotion-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"


@interface CMAccelerometerDataInternal : XXUnknownSuperclass <NSCopying> {
	XXStruct_ZUkpeA fAcceleration;
}
-(id)initWithAcceleration:(XXStruct_ZUkpeA)acceleration;
-(id).cxx_construct;
-(id)copyWithZone:(NSZone*)zone;
-(void)setAcceleration:(XXStruct_ZUkpeA)acceleration;
@end

