/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

#import "CMLogItem.h"
#import "CoreMotion-Structs.h"


@interface CMGyroData : CMLogItem {
@private
	id _internal;
}
@property(readonly, assign, nonatomic) XXStruct_taVrlB rotationRate;
-(id)initWithCoder:(id)coder;
-(id)initWithRotationRate:(XXStruct_ZUkpeA)rotationRate andTimestamp:(double)timestamp;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)description;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(XXStruct_taVrlB)rotationRate;
@end

