/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import "CABehavior.h"

@class NSArray;

@interface CADynamicsBehavior : CABehavior {
}
@property(assign) float angularDrag;
@property(assign) double collisionInterval;
@property(assign) float drag;
@property(copy) NSArray* forceFields;
@property(assign) double minimumTimeStep;
@property(assign) BOOL reactsToCollisions;
@property(assign) float springScale;
@property(copy) NSArray* springs;
@property(assign) float stoppedAngularVelocity;
@property(assign) float stoppedVelocity;
@property(assign) double timeStep;
+(id)defaultValueForKey:(id)key;
-(Object*)CA_copyRenderValue;
// declared property getter: -(float)angularDrag;
// declared property getter: -(double)collisionInterval;
// declared property getter: -(float)drag;
// declared property getter: -(id)forceFields;
// declared property getter: -(double)minimumTimeStep;
// declared property getter: -(BOOL)reactsToCollisions;
// declared property setter: -(void)setAngularDrag:(float)drag;
// declared property setter: -(void)setCollisionInterval:(double)interval;
// declared property setter: -(void)setDrag:(float)drag;
// declared property setter: -(void)setForceFields:(id)fields;
// declared property setter: -(void)setMinimumTimeStep:(double)step;
// declared property setter: -(void)setReactsToCollisions:(BOOL)collisions;
// declared property setter: -(void)setSpringScale:(float)scale;
// declared property setter: -(void)setSprings:(id)springs;
// declared property setter: -(void)setStoppedAngularVelocity:(float)velocity;
// declared property setter: -(void)setStoppedVelocity:(float)velocity;
// declared property setter: -(void)setTimeStep:(double)step;
// declared property getter: -(float)springScale;
// declared property getter: -(id)springs;
// declared property getter: -(float)stoppedAngularVelocity;
// declared property getter: -(float)stoppedVelocity;
// declared property getter: -(double)timeStep;
@end

