/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */



@protocol GKComposeRecipientAtomDelegate
-(void)composeRecipientAtomSelectNext:(id)next;
-(void)composeRecipientAtomSelectPrevious:(id)previous;
-(void)selectComposeRecipientAtom:(id)atom;
@end

