/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKDataRequest.h"

@class GKGame;

@interface GKGetPlayersForGameRequest : GKDataRequest {
@private
	GKGame* _game;
}
@property(retain, nonatomic) GKGame* game;	// @synthesize=_game
-(void)dealloc;
// declared property getter: -(id)game;
-(id)key;
-(id)request;
// declared property setter: -(void)setGame:(id)game;
@end

