/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKDataRequest.h"

@class NSString, NSArray;

@interface GKSetPlayersToInviteDataRequest : GKDataRequest {
@private
	NSString* _bundleIdentifier;
	NSArray* _players;
}
@property(retain, nonatomic) NSString* bundleIdentifier;	// @synthesize=_bundleIdentifier
@property(retain, nonatomic) NSArray* players;	// @synthesize=_players
// declared property getter: -(id)bundleIdentifier;
-(void)dealloc;
-(id)key;
// declared property getter: -(id)players;
-(id)request;
// declared property setter: -(void)setBundleIdentifier:(id)identifier;
// declared property setter: -(void)setPlayers:(id)players;
@end

