/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "NSObject.h"

@class NSDate;

@protocol GKTableViewControllerDataSource <NSObject>
@optional
@property(retain, nonatomic) NSDate* expirationDate;
-(unsigned long long)contextForTableView:(id)tableView updateStatusViewBeforeLoading:(id)loading;
// declared property getter: -(id)expirationDate;
-(BOOL)isExpired;
@required
-(int)numberOfSectionsInTableView:(id)tableView;
@optional
-(void)refreshDataWithCompletionHandlerAndError:(id)completionHandlerAndError;
// declared property setter: -(void)setExpirationDate:(id)date;
-(id)statusTextAfterLoadingTableView:(id)view;
-(void)tableView:(id)view prepareExpensiveContentAtIndexPaths:(id)indexPaths withCompletionHandler:(id)completionHandler;
@required
-(id)tableView:(id)view sectionAtIndex:(int)index;
@optional
-(void)tableView:(id)view updateStatusViewAfterLoading:(id)loading context:(unsigned long long)context withError:(id)error;
-(void)tableView:(id)view updateStatusViewAfterLoading:(id)loading withError:(id)error;
-(void)tableView:(id)view updateStatusViewBeforeLoading:(id)loading;
@end

