/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKInternalRepresentation.h"

@class NSDictionary, GKGameInternal;

@interface GKTopGameInternal : GKInternalRepresentation {
@private
	GKGameInternal* _game;
	NSDictionary* _icons;
}
@property(retain, nonatomic) GKGameInternal* game;	// @synthesize=_game
@property(retain, nonatomic) NSDictionary* icons;	// @synthesize=_icons
+(id)codedPropertyKeys;
-(void)dealloc;
// declared property getter: -(id)game;
-(unsigned)hash;
// declared property getter: -(id)icons;
-(BOOL)isEqual:(id)equal;
// declared property setter: -(void)setGame:(id)game;
// declared property setter: -(void)setIcons:(id)icons;
@end

