/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol GKTurnBasedEventHandlerDelegate;

@interface GKTurnBasedEventHandler : XXUnknownSuperclass {
@private
	NSObject<GKTurnBasedEventHandlerDelegate>* _delegate;
}
@property(assign, nonatomic) NSObject<GKTurnBasedEventHandlerDelegate>* delegate;	// @synthesize=_delegate
+(id)sharedTurnBasedEventHandler;
// declared property getter: -(id)delegate;
-(void)lookForEvent;
// declared property setter: -(void)setDelegate:(id)delegate;
@end

