/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPNowPlayingItemQueueInfoButtonDelegate.h"
#import "MPVideoOverlay.h"

@class MPNowPlayingItemQueueInfoButton, MPInlineTransportControls;

@interface MPInlineVideoOverlay : MPVideoOverlay <MPNowPlayingItemQueueInfoButtonDelegate> {
@private
	MPInlineTransportControls* _transportControls;
	MPNowPlayingItemQueueInfoButton* _itemQueueInfoButton;
	unsigned _layoutSubviewsActive : 1;
}
-(id)initWithFrame:(CGRect)frame;
-(void)_availableRoutesDidChangeNotification:(id)_availableRoutes;
-(void)_configureLinkButtonForCurrentItemTime;
-(unsigned)_convertedPartsMask:(unsigned)mask;
-(BOOL)allowsWirelessPlayback;
-(void)crossedURLTimeMarker:(id)marker;
-(void)dealloc;
-(void)detailSliderTrackingDidBegin:(id)detailSliderTracking;
-(void)detailSliderTrackingDidCancel:(id)detailSliderTracking;
-(void)detailSliderTrackingDidEnd:(id)detailSliderTracking;
-(void)layoutSubviews;
-(int)nowPlayingItemQueueInfoButton:(id)button willDisplayInfoType:(int)type;
-(void)setAllowsWirelessPlayback:(BOOL)playback;
-(void)setDesiredParts:(unsigned)parts animate:(BOOL)animate;
-(void)setDisabledParts:(unsigned)parts;
-(void)setFrame:(CGRect)frame;
-(void)setItem:(id)item;
-(void)setVideoViewController:(id)controller;
-(void)setVisibleParts:(unsigned)parts animate:(BOOL)animate;
@end

