/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SSDownload, MPMediaItem, SSPurchase, NSMutableArray, NSError;

@interface MPSSPurchaseRequest : XXUnknownSuperclass {
@private
	BOOL _completed;
	NSMutableArray* _completionHandlers;
	SSDownload* _purchaseDownload;
	MPMediaItem* _mediaItem;
	NSError* _purchaseError;
	int _purchaseReason;
}
@property(readonly, assign, nonatomic) BOOL completed;	// @synthesize=_completed
@property(readonly, assign, nonatomic) MPMediaItem* mediaItem;	// @synthesize=_mediaItem
@property(readonly, assign, nonatomic) SSPurchase* purchase;
@property(assign, nonatomic) int purchaseReason;	// @synthesize=_purchaseReason
+(id)purchaseForMediaItem:(id)mediaItem purchaseReason:(int)reason;
-(id)initWithMediaItem:(id)mediaItem purchaseReason:(int)reason;
-(void)addCompletionHandler:(id)handler;
// declared property getter: -(BOOL)completed;
-(void)dealloc;
-(id)description;
-(void)invokeAndClearAllCompletionHandlers;
-(void)invokeCompletionHandler:(id)handler;
// declared property getter: -(id)mediaItem;
// declared property getter: -(id)purchase;
// declared property getter: -(int)purchaseReason;
-(void)setCompletedWithDownload:(id)download error:(id)error;
// declared property setter: -(void)setPurchaseReason:(int)reason;
@end

