/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Accounts.framework/Accounts
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Accounts-Structs.h"

@class NSDate, NSString, NSFileHandle;

@interface ACRollableLog : XXUnknownSuperclass {
	NSDate* _lastStatDate;
	NSString* _baseFilename;
	NSString* _generationalFilenameFormat;
	NSFileHandle* _fh;
	dispatch_source_s* _fdWatcher;
	dispatch_queue_s* _logQueue;
	dispatch_queue_s* _logRequestQueue;
}
@property(retain) NSFileHandle* fh;	// @synthesize=_fh
@property(retain) NSDate* lastStatDate;	// @synthesize=_lastStatDate
+(id)_filenameWithBase:(id)base generationalFormat:(id)format generation:(int)generation;
+(id)_generationalFormatFromBase:(id)base;
+(id)allLogFilesForFilename:(id)filename;
+(void)enableLogRolling;
+(id)loggerWithFilename:(id)filename;
-(id)initWithFilename:(id)filename;
-(id)_filenameWithGenerationNumber:(int)generationNumber;
-(id)_fullCompressedFilePathWithGenerationNumber:(int)generationNumber;
-(id)_fullFilePathWithGenerationNumber:(int)generationNumber;
-(void)_loadUpHandle;
-(void)_rollLogs;
-(void)_statFileIfNecessaryForRollingCheck;
-(id)compressFile:(id)file;
-(void)dealloc;
// declared property getter: -(id)fh;
// declared property getter: -(id)lastStatDate;
-(void)logData:(id)data;
-(void)logString:(id)string;
// declared property setter: -(void)setFh:(id)fh;
// declared property setter: -(void)setLastStatDate:(id)date;
-(void)slurpDataFromFile:(id)file;
@end

