/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURLRequest, NSDictionary, AVAssetResourceLoader;

@interface AVAssetResourceLoadingRequestInternal : XXUnknownSuperclass {
	AVAssetResourceLoader* resourceLoader;
	NSDictionary* requestDictionary;
	NSURLRequest* URLRequest;
	BOOL finished;
}
@end

