/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AVFoundation-Structs.h"

@class NSArray, AVOutputSettings, NSString, NSDictionary, AVAssetWriterInputConfigurationState, AVWeakReference;

@interface AVAssetWriterInputHelper : XXUnknownSuperclass {
@private
	AVAssetWriterInputConfigurationState* _configurationState;
	AVWeakReference* _weakReferenceToAssetWriterInput;
}
@property(assign, nonatomic) short alternateGroupID;
@property(readonly, assign, nonatomic) AVAssetWriterInputConfigurationState* configurationState;	// @synthesize=_configurationState
@property(assign, nonatomic) BOOL expectsMediaDataInRealTime;
@property(copy, nonatomic) NSString* extendedLanguageTag;
@property(copy, nonatomic) NSString* languageCode;
@property(assign, nonatomic) BOOL marksOutputTrackAsEnabled;
@property(assign, nonatomic) int mediaTimeScale;
@property(readonly, assign, nonatomic) NSString* mediaType;
@property(copy, nonatomic) NSArray* metadata;
@property(assign, nonatomic) CGSize naturalSize;
@property(readonly, assign, nonatomic) AVOutputSettings* outputSettings;
@property(readonly, assign, nonatomic) CVPixelBufferPoolRef pixelBufferPool;
@property(readonly, assign, nonatomic, getter=isReadyForMoreMediaData) BOOL readyForMoreMediaData;
@property(readonly, assign, nonatomic) opaqueCMFormatDescription* sourceFormatHint;
@property(copy, nonatomic) NSDictionary* sourcePixelBufferAttributes;
@property(readonly, assign, nonatomic) int status;
@property(readonly, assign, nonatomic) int trackID;
@property(readonly, assign, nonatomic) NSDictionary* trackReferences;
@property(assign, nonatomic) CGAffineTransform transform;
@property(retain) AVWeakReference* weakReferenceToAssetWriterInput;	// @synthesize=_weakReferenceToAssetWriterInput
-(id)initWithConfigurationState:(id)configurationState;
-(void)addTrackAssociationWithTrackOfInput:(id)input type:(id)type;
// declared property getter: -(short)alternateGroupID;
-(BOOL)appendPixelBuffer:(CVBufferRef)buffer withPresentationTime:(XXStruct_pwHToB)presentationTime;
-(BOOL)appendSampleBuffer:(opaqueCMSampleBuffer*)buffer;
-(BOOL)canAddTrackAssociationWithTrackOfInput:(id)input type:(id)type;
// declared property getter: -(id)configurationState;
-(void)dealloc;
// declared property getter: -(BOOL)expectsMediaDataInRealTime;
// declared property getter: -(id)extendedLanguageTag;
// declared property getter: -(BOOL)isReadyForMoreMediaData;
// declared property getter: -(id)languageCode;
-(void)markAsFinished;
// declared property getter: -(BOOL)marksOutputTrackAsEnabled;
// declared property getter: -(int)mediaTimeScale;
// declared property getter: -(id)mediaType;
// declared property getter: -(id)metadata;
// declared property getter: -(CGSize)naturalSize;
// declared property getter: -(id)outputSettings;
// declared property getter: -(CVPixelBufferPoolRef)pixelBufferPool;
-(void)prepareToEndSession;
-(BOOL)prepareToFinishWritingReturningError:(id*)finishWritingReturningError;
-(void)requestMediaDataWhenReadyOnQueue:(id)queue usingBlock:(id)block;
// declared property setter: -(void)setAlternateGroupID:(short)anId;
// declared property setter: -(void)setExpectsMediaDataInRealTime:(BOOL)realTime;
// declared property setter: -(void)setExtendedLanguageTag:(id)tag;
// declared property setter: -(void)setLanguageCode:(id)code;
// declared property setter: -(void)setMarksOutputTrackAsEnabled:(BOOL)enabled;
// declared property setter: -(void)setMediaTimeScale:(int)scale;
// declared property setter: -(void)setMetadata:(id)metadata;
// declared property setter: -(void)setNaturalSize:(CGSize)size;
// declared property setter: -(void)setSourcePixelBufferAttributes:(id)attributes;
// declared property setter: -(void)setTransform:(CGAffineTransform)transform;
// declared property setter: -(void)setWeakReferenceToAssetWriterInput:(id)assetWriterInput;
// declared property getter: -(opaqueCMFormatDescription*)sourceFormatHint;
// declared property getter: -(id)sourcePixelBufferAttributes;
// declared property getter: -(int)status;
// declared property getter: -(int)trackID;
// declared property getter: -(id)trackReferences;
// declared property getter: -(CGAffineTransform)transform;
-(void)transitionAssetWriterAndAllInputsToFailedStatusWithError:(id)error;
-(void)transitionToTerminalStatus:(int)terminalStatus;
// declared property getter: -(id)weakReferenceToAssetWriterInput;
@end

