/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, AVMetadataObjectInternal;

@interface AVMetadataObject : XXUnknownSuperclass {
	AVMetadataObjectInternal* _objectInternal;
}
@property(readonly, assign) CGRect bounds;
@property(readonly, assign) XXStruct_pwHToB duration;
@property(readonly, assign) XXStruct_pwHToB time;
@property(readonly, assign) NSString* type;
-(id)init;
// declared property getter: -(CGRect)bounds;
-(void)dealloc;
// declared property getter: -(XXStruct_pwHToB)duration;
-(id)input;
// declared property getter: -(XXStruct_pwHToB)time;
// declared property getter: -(id)type;
@end

