/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AVPlayerItem, AVSynchronizedLayerInternal;

@interface AVSynchronizedLayer : XXUnknownSuperclass {
	AVSynchronizedLayerInternal* _syncLayer;
}
@property(retain, nonatomic) AVPlayerItem* playerItem;
+(id)synchronizedLayerWithPlayerItem:(id)playerItem;
-(id)init;
-(void)dealloc;
-(void)finalize;
-(void)layerDidBecomeVisible:(BOOL)layer;
// declared property getter: -(id)playerItem;
// declared property setter: -(void)setPlayerItem:(id)item;
@end

