/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "CoreFoundation-Structs.h"
#import "NSTimeZone.h"


__attribute__((visibility("hidden")))
@interface __NSTimeZone : NSTimeZone {
@private
	CFStringRef _name;
	CFDataRef _data;
	void** _ucal;
	int _lock;
}
+(id)__new:(CFStringRef)aNew cache:(BOOL)cache;
+(id)__new:(CFStringRef)aNew data:(CFDataRef)data;
+(id)allocWithZone:(NSZone*)zone;
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(id)abbreviationForDate:(id)date;
-(id)data;
-(double)daylightSavingTimeOffsetForDate:(id)date;
-(void)dealloc;
-(void)finalize;
-(BOOL)isDaylightSavingTimeForDate:(id)date;
-(id)localizedName:(int)name locale:(id)locale;
-(id)name;
-(id)nextDaylightSavingTimeTransitionAfterDate:(id)date;
-(int)secondsFromGMTForDate:(id)date;
@end

