/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "NSLocale.h"


__attribute__((visibility("hidden")))
@interface __NSCFLocale : NSLocale {
}
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
-(id)initWithLocaleIdentifier:(id)localeIdentifier;
-(BOOL)_isDeallocating;
-(id)_prefs;
-(BOOL)_tryRetain;
-(id)displayNameForKey:(id)key value:(id)value;
-(void)finalize;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)objectForKey:(id)key;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
@end

