/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Social.framework/Social
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSString;

@interface SLFacebookAlbum : XXUnknownSuperclass <NSCoding> {
@private
	BOOL _canUpload;
	int _count;
	NSString* _identifier;
	NSString* _name;
	NSString* _coverPhotoIdentifier;
}
@property(assign) BOOL canUpload;	// @synthesize=_canUpload
@property(assign) int count;	// @synthesize=_count
@property(retain) NSString* coverPhotoIdentifier;	// @synthesize=_coverPhotoIdentifier
@property(retain) NSString* identifier;	// @synthesize=_identifier
@property(retain) NSString* name;	// @synthesize=_name
+(id)albumWithDataDictionary:(id)dataDictionary;
+(id)albumsWithAlbumDataDictionaries:(id)albumDataDictionaries;
-(id)initWithCoder:(id)coder;
-(void).cxx_destruct;
// declared property getter: -(BOOL)canUpload;
// declared property getter: -(int)count;
// declared property getter: -(id)coverPhotoIdentifier;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(id)identifier;
// declared property getter: -(id)name;
// declared property setter: -(void)setCanUpload:(BOOL)upload;
// declared property setter: -(void)setCount:(int)count;
// declared property setter: -(void)setCoverPhotoIdentifier:(id)identifier;
// declared property setter: -(void)setIdentifier:(id)identifier;
// declared property setter: -(void)setName:(id)name;
@end

