/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Social.framework/Social
 */

#import "SLAttachment.h"


@interface SLImageAttachment : SLAttachment {
}
-(id)initWithAsset:(id)asset preview:(id)preview;
-(id)initWithImage:(id)image preview:(id)preview;
-(BOOL)hasValidPayload;
@end

