/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIPageViewController;

__attribute__((visibility("hidden")))
@interface _UIPageViewControllerContentView : UIView {
@private
	UIPageViewController* _pageViewController;
}
@property(assign, nonatomic, setter=_setPageViewController:) UIPageViewController* _pageViewController;	// @synthesize
-(id)initWithFrame:(CGRect)frame andPageViewController:(id)controller;
// declared property getter: -(id)_pageViewController;
// declared property setter: -(void)_setPageViewController:(id)controller;
-(void)setFrame:(CGRect)frame;
@end

