/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIActionSheetDelegate.h"
#import "UIDocumentInteractionController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSArray, UIActionSheet, _UIPreviewItemProxy, UIPopoverController, NSString, UIBarButtonItem, UIViewController, UIView;
@protocol UIDocumentInteractionControllerDelegate;

@interface UIDocumentInteractionController : XXUnknownSuperclass <UIActionSheetDelegate> {
@private
	id<UIDocumentInteractionControllerDelegate> _delegate;
	id _previewItemProxy;
	NSArray* _icons;
	id _annotation;
	NSString* _uniqueIdentifier;
	UIPopoverController* _popoverController;
	UIViewController* _presentingViewController;
	id _previewController;
	NSArray* _gestureRecognizers;
	CGRect _presentRect;
	UIView* _presentView;
	UIBarButtonItem* _presentItem;
	NSArray* _availableApplications;
	UIViewController* _openInViewController;
	UIActionSheet* _optionsMenu;
	UIActionSheet* _openInMenu;
	int _quickLookButtonIndex;
	int _defaultOpenButtonIndex;
	int _alternateOpenButtonIndex;
	int _copyButtonIndex;
	int _printButtonIndex;
	CGSize _openInTableViewSize;
	BOOL _shouldUnzipDocument;
	NSURL* _unzippedDocumentURL;
	id _applicationToOpen;
	struct {
		unsigned delegateViewControllerForPreview : 1;
		unsigned delegateRectForPreview : 1;
		unsigned delegateViewForPreview : 1;
		unsigned transitionImageForPreview : 1;
		unsigned delegateWillBeginPreview : 1;
		unsigned delegateDidEndPreviewPreview : 1;
		unsigned delegateWillPresentOptionsMenu : 1;
		unsigned delegateDidDismissOptionsMenu : 1;
		unsigned delegateWillPresentOpenInMenu : 1;
		unsigned delegateDidDismissOpenInMenu : 1;
		unsigned delegateWillBeginSendingToApplication : 1;
		unsigned delegateDidEndSendingToApplication : 1;
		unsigned delegateCanPerformAction : 1;
		unsigned delegatePerformAction : 1;
		unsigned delegateUnzipURL : 1;
	} _documentInteractionControllerFlags;
}
@property(retain) NSURL* URL;
@property(copy, nonatomic) NSString* UTI;
@property(retain, nonatomic) id annotation;	// @synthesize=_annotation
@property(assign, nonatomic) id<UIDocumentInteractionControllerDelegate> delegate;	// @synthesize=_delegate
@property(readonly, assign, nonatomic) NSArray* gestureRecognizers;
@property(readonly, assign, nonatomic) NSArray* icons;
@property(copy) NSString* name;
@property(assign, nonatomic) BOOL shouldUnzipDocument;	// @synthesize=_shouldUnzipDocument
@property(retain, nonatomic) NSString* uniqueIdentifier;	// @synthesize=_uniqueIdentifier
+(id)_UTIForFilename:(id)filename;
+(void)initialize;
+(id)interactionControllerWithURL:(id)url;
-(id)initWithURL:(id)url;
// declared property getter: -(id)URL;
// declared property getter: -(id)UTI;
-(BOOL)_canPreviewUnzippedDocument;
-(BOOL)_canUnzipDocumentAndPresentOptions;
-(void)_presentOpenInForPhoneInView:(id)view;
// declared property getter: -(id)annotation;
-(unsigned)applicationCount;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)dismissMenuAnimated:(BOOL)animated;
-(void)dismissPreviewAnimated:(BOOL)animated;
// declared property getter: -(id)gestureRecognizers;
// declared property getter: -(id)icons;
// declared property getter: -(id)name;
-(void)openDocumentWithDefaultApplication;
-(BOOL)presentOpenInMenuFromBarButtonItem:(id)barButtonItem animated:(BOOL)animated;
-(BOOL)presentOpenInMenuFromRect:(CGRect)rect inView:(id)view animated:(BOOL)animated;
-(BOOL)presentOptionsMenuFromBarButtonItem:(id)barButtonItem animated:(BOOL)animated;
-(BOOL)presentOptionsMenuFromRect:(CGRect)rect inView:(id)view animated:(BOOL)animated;
-(BOOL)presentPreviewAnimated:(BOOL)animated;
-(id)presentingNavigationController;
// declared property setter: -(void)setAnnotation:(id)annotation;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setName:(id)name;
-(void)setPreviewURLOverride:(id)override;
// declared property setter: -(void)setShouldUnzipDocument:(BOOL)unzipDocument;
// declared property setter: -(void)setURL:(id)url;
// declared property setter: -(void)setUTI:(id)uti;
// declared property setter: -(void)setUniqueIdentifier:(id)identifier;
// declared property getter: -(BOOL)shouldUnzipDocument;
// declared property getter: -(id)uniqueIdentifier;
-(void)updatePopoverContentSizeForPresentationOfTableViewHack;
@end

@interface UIDocumentInteractionController (QLPreviewController)
-(CGRect)previewController:(id)controller frameForPreviewItem:(id)previewItem inSourceView:(id*)sourceView;
-(id)previewController:(id)controller transitionImageForPreviewItem:(id)previewItem contentRect:(CGRect*)rect;
-(void)previewControllerDidDismiss:(id)previewController;
@end

@interface UIDocumentInteractionController (QLPreviewControllerDataSource)
-(int)numberOfPreviewItemsInPreviewController:(id)previewController;
-(id)previewController:(id)controller previewItemAtIndex:(int)index;
@end

@interface UIDocumentInteractionController (UIActionSheetDelegate)
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)actionSheetCancel:(id)cancel;
@end

@interface UIDocumentInteractionController (UIPopoverControllerDelegate)
-(void)popoverControllerDidDismissPopover:(id)popoverController;
@end

@interface UIDocumentInteractionController (Private)
@property(readonly, assign, nonatomic) UIPopoverController* popoverController;
@property(readonly, assign, nonatomic) id previewController;
@property(readonly, assign, nonatomic) _UIPreviewItemProxy* previewItemProxy;
+(id)_applicationsForFilename:(id)filename UTI:(id)uti;
+(dispatch_queue_s*)_unzippingQueue;
-(id)_applicationToOpen;
-(id)_applications:(BOOL)applications;
-(BOOL)_canUnzipDocument;
-(BOOL)_delegateExistsAndImplementsRequiredMethods:(id*)methods;
-(BOOL)_documentNeedsHelpUnzippingForPreview;
-(void)_finishedCopyingResource;
-(void)_interfaceOrientationWillChange:(id)_interfaceOrientation;
-(void)_invalidate;
-(BOOL)_isFilenameValidForUnzipping:(id)unzipping;
-(BOOL)_isValidURL:(id)url;
-(void)_openDocumentWithApplication:(id)application;
-(void)_openDocumentWithCurrentApplication;
-(void)_presentOpenIn:(id)anIn;
-(void)_presentOptionsMenu:(id)menu;
-(void)_presentPreview:(id)preview;
-(void)_setApplicationToOpen:(id)open;
-(void)_setUnzippedDocumentURL:(id)url;
-(BOOL)_setupForOpenInMenu;
-(BOOL)_setupForOptionsMenu;
-(BOOL)_setupPreviewController;
-(void)_unzipFileAndSetupPayload:(id)payload;
-(id)_unzippedDocumentURL;
-(void)openResourceOperation:(id)operation didFinishCopyingResource:(id)resource;
// declared property getter: -(id)popoverController;
// declared property getter: -(id)previewController;
// declared property getter: -(id)previewItemProxy;
@end

