/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"

@class NSMutableArray, UIImage;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoriesControl : UIControl {
@private
	int _selected;
	int _total;
	UIImage* _darkDivider;
	UIImage* _plainDivider;
	UIImage* _selectedDivider;
	NSMutableArray* _segmentViews;
	NSMutableArray* _dividerViews;
}
@property(readonly, assign) int numSegments;	// @dynamic
@property(assign) int selectedIndex;	// @dynamic
+(id)categoryControl;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
// declared property getter: -(int)numSegments;
-(void)releaseImagesAndViews;
// declared property getter: -(int)selectedIndex;
-(void)setFrame:(CGRect)frame;
// declared property setter: -(void)setSelectedIndex:(int)index;
@end

