/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITextField.h"


@interface UISearchField : UITextField {
}
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)frame;
-(id)_scriptingInfo;
-(BOOL)_shouldSendContentChangedNotificationsIfOnlyMarkedTextChanged;
-(Class)_systemBackgroundViewClass;
-(CGRect)_textRectExcludingButtonsForBounds:(CGRect)bounds;
-(CGRect)iconRect;
-(CGRect)rightViewRectForBounds:(CGRect)bounds;
@end

