/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "NSCoding.h"
#import "UISegmentedControl.h"
#import "UIControl.h"

@class UISegment, UIColor, NSMutableArray;

@interface UISegmentedControl : UIControl <NSCoding> {
@private
	NSMutableArray* _segments;
	int _selectedSegment;
	int _highlightedSegment;
	UIView* _removedSegment;
	id _delegate;
	UIColor* _tintColor;
	int _barStyle;
	id _appearanceStorage;
	UIView* _backgroundBarView;
	float _enabledAlpha;
	struct {
		unsigned style : 3;
		unsigned size : 2;
		unsigned showsDisclosure : 1;
		unsigned delegateSelectedSegmentChanged : 1;
		unsigned delegateDisclosureButtonClicked : 1;
		unsigned delegateAlwaysNotifiesDelegateOfSegmentClicks : 1;
		unsigned momentaryClick : 1;
		unsigned dontAlwaysToggleForTwoSegments : 1;
		unsigned tracking : 1;
		unsigned mouseInside : 1;
		unsigned autosizeToFitSegments : 1;
		unsigned isSizingToFit : 1;
		unsigned autosizeText : 1;
		unsigned transparentBackground : 1;
		unsigned useProportionalWidthSegments : 1;
		unsigned translucentBackground : 1;
	} _segmentedControlFlags;
}
@property(assign, nonatomic) BOOL apportionsSegmentWidthsByContent;
@property(assign, nonatomic, getter=isMomentary) BOOL momentary;	// @dynamic
@property(readonly, assign, nonatomic) unsigned numberOfSegments;	// @dynamic
@property(assign, nonatomic) int segmentedControlStyle;	// @dynamic
@property(assign, nonatomic) int selectedSegmentIndex;	// @dynamic
@property(retain, nonatomic) UIColor* tintColor;	// @synthesize=_tintColor
+(BOOL)automaticallyNotifiesObserversForKey:(id)key;
+(float)defaultHeightForStyle:(int)style;
+(float)defaultHeightForStyle:(int)style size:(int)size;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithItems:(id)items;
-(float)_backgroundVerticalPositionAdjustmentForBarMetrics:(int)barMetrics;
-(void)_commonSegmentedControlInit;
-(void)_didMoveFromWindow:(id)window toWindow:(id)window2;
-(id)_optionsBackgroundImage;
-(void)_populateArchivedSubviews:(id)subviews;
-(void)_resetForAppearanceChange;
-(void)_setAppearanceIsTiled:(BOOL)tiled leftCapWidth:(unsigned)width rightCapWidth:(unsigned)width3;
-(void)_setAutosizeText:(BOOL)text;
-(void)_setBackgroundImage:(id)image forState:(unsigned)state barMetrics:(int)metrics;
-(void)_setBackgroundVerticalPositionAdjustment:(float)adjustment forBarMetrics:(int)barMetrics;
-(void)_setDividerImage:(id)image forLeftSegmentState:(unsigned)leftSegmentState rightSegmentState:(unsigned)state barMetrics:(int)metrics;
-(void)_setEnabled:(BOOL)enabled forcePropagateToSegments:(BOOL)segments;
-(void)_setOptionsBackgroundImage:(id)image;
-(void)_setSegmentedControlAppearance:(XXStruct_wXTbsB*)appearance;
-(void)_setSelectedSegmentIndex:(int)index notify:(BOOL)notify;
-(void)_setTitleTextAttributes:(id)attributes forState:(unsigned)state;
-(void)_setTranslucentOptionsBackground:(BOOL)background;
-(BOOL)_shouldSelectSegmentAtIndex:(int)index;
-(void)_updateOptionsBackground;
// declared property getter: -(BOOL)apportionsSegmentWidthsByContent;
-(id)backgroundImageForState:(unsigned)state barMetrics:(int)metrics;
-(int)barStyle;
-(CGSize)contentOffsetForSegmentAtIndex:(unsigned)index;
-(UIOffset)contentPositionAdjustmentForSegmentType:(int)segmentType barMetrics:(int)metrics;
-(int)controlSize;
-(void)dealloc;
-(id)dividerImageForLeftSegmentState:(unsigned)leftSegmentState rightSegmentState:(unsigned)state barMetrics:(int)metrics;
-(void)encodeWithCoder:(id)coder;
-(void)highlightSegment:(int)segment;
-(id)imageForSegmentAtIndex:(unsigned)index;
-(void)insertSegmentWithImage:(id)image atIndex:(unsigned)index animated:(BOOL)animated;
-(void)insertSegmentWithTitle:(id)title atIndex:(unsigned)index animated:(BOOL)animated;
-(BOOL)isEnabledForSegmentAtIndex:(unsigned)index;
// declared property getter: -(BOOL)isMomentary;
-(void)layoutSubviews;
-(void)mouseDown:(GSEventRef)down;
-(void)mouseDragged:(GSEventRef)dragged;
-(void)mouseUp:(GSEventRef)up;
// declared property getter: -(unsigned)numberOfSegments;
-(BOOL)pointMostlyInside:(CGPoint)inside forEvent:(GSEventRef)event;
-(BOOL)pointMostlyInside:(CGPoint)inside withEvent:(id)event;
-(void)removeAllSegments;
-(void)removeSegmentAtIndex:(unsigned)index animated:(BOOL)animated;
-(int)segmentControlStyle;
// declared property getter: -(int)segmentedControlStyle;
// declared property getter: -(int)selectedSegmentIndex;
-(void)setAlpha:(float)alpha;
-(void)setAlwaysToggleForTwoSegments:(BOOL)twoSegments;
// declared property setter: -(void)setApportionsSegmentWidthsByContent:(BOOL)content;
-(void)setBackgroundImage:(id)image forState:(unsigned)state barMetrics:(int)metrics;
-(void)setBarStyle:(int)style;
-(void)setContentOffset:(CGSize)offset forSegmentAtIndex:(unsigned)index;
-(void)setContentPositionAdjustment:(UIOffset)adjustment forSegmentType:(int)segmentType barMetrics:(int)metrics;
-(void)setControlSize:(int)size;
-(void)setDividerImage:(id)image forLeftSegmentState:(unsigned)leftSegmentState rightSegmentState:(unsigned)state barMetrics:(int)metrics;
-(void)setEnabled:(BOOL)enabled;
-(void)setEnabled:(BOOL)enabled forSegmentAtIndex:(unsigned)index;
-(void)setFrame:(CGRect)frame;
-(void)setImage:(id)image forSegmentAtIndex:(unsigned)index;
// declared property setter: -(void)setMomentary:(BOOL)momentary;
-(void)setSegmentControlStyle:(int)style;
// declared property setter: -(void)setSegmentedControlStyle:(int)style;
// declared property setter: -(void)setSelectedSegmentIndex:(int)index;
// declared property setter: -(void)setTintColor:(id)color;
-(void)setTitle:(id)title forSegmentAtIndex:(unsigned)index;
-(void)setTitleTextAttributes:(id)attributes forState:(unsigned)state;
-(void)setTransparentBackground:(BOOL)background;
-(void)setWidth:(float)width forSegmentAtIndex:(unsigned)index;
-(BOOL)shouldTrack;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)sizeToFit;
// declared property getter: -(id)tintColor;
-(id)titleForSegmentAtIndex:(unsigned)index;
-(id)titleTextAttributesForState:(unsigned)state;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(BOOL)transparentBackground;
-(void)updateForMiniBarState:(BOOL)miniBarState;
-(BOOL)useBlockyMagnificationInClassic;
-(float)widthForSegmentAtIndex:(unsigned)index;
@end

@interface UISegmentedControl (InternalProperties)
@property(retain, nonatomic) UISegment* removedSegment;
// declared property getter: -(id)removedSegment;
// declared property setter: -(void)setRemovedSegment:(id)segment;
@end

@interface UISegmentedControl (Static)
-(float)_barHeight;
-(void)_clearSelectedSegment;
-(void)_createSegmentAtIndex:(int)index position:(unsigned)position withInfo:(id)info;
-(void)_insertSegment:(int)segment withInfo:(id)info animated:(BOOL)animated;
-(BOOL)_isInMiniBar;
-(void)_removeSegmentAnimationFinished:(id)finished finished:(id)finished2 context:(void*)context;
@end

@interface UISegmentedControl (InterfaceBuilderSupport)
-(id)infoViewForSegment:(int)segment;
@end

@interface UISegmentedControl (DeprecatedMethods)
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)frame withStyle:(int)style withItems:(id)items;
-(void)addSegmentWithTitle:(id)title;
-(CGSize)contentOffsetForSegment:(unsigned)segment;
-(id)imageForSegment:(unsigned)segment;
-(void)insertSegment:(unsigned)segment withImage:(id)image animated:(BOOL)animated;
-(void)insertSegment:(unsigned)segment withTitle:(id)title animated:(BOOL)animated;
-(BOOL)isEnabledForSegment:(unsigned)segment;
-(void)removeSegment:(unsigned)segment animated:(BOOL)animated;
-(void)selectSegment:(int)segment;
-(int)selectedSegment;
-(void)setAlwaysNotifiesDelegateOfSegmentClicks:(BOOL)segmentClicks;
-(void)setContentOffset:(CGSize)offset forSegment:(unsigned)segment;
-(void)setDelegate:(id)delegate;
-(void)setEnabled:(BOOL)enabled forSegment:(unsigned)segment;
-(void)setImage:(id)image forSegment:(unsigned)segment;
-(void)setImagePadding:(CGSize)padding forSegment:(unsigned)segment;
-(void)setMomentaryClick:(BOOL)click;
-(void)setSelectedSegment:(int)segment;
-(void)setShowsDisclosure:(BOOL)disclosure;
-(void)setTitle:(id)title forSegment:(unsigned)segment;
-(void)setWidth:(float)width forSegment:(unsigned)segment;
-(id)titleForSegment:(unsigned)segment;
-(float)widthForSegment:(unsigned)segment;
@end

@interface UISegmentedControl (SynthEvents)
-(id)scriptingInfoWithChildren;
@end

