/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MCMediaControlClientRemote : XXUnknownSuperclass {
}
-(void)authorizeWithPICRequest:(id)picrequest completionQueue:(id)queue completionBlock:(id)block;
-(void)dealloc;
-(void)getPlaybackInfoWithOptions:(unsigned)options completionQueue:(id)queue completionBlock:(id)block;
-(void)getPositionWithOptions:(unsigned)options completionQueue:(id)queue completionBlock:(id)block;
-(void)getVolumeWithOptions:(unsigned)options completionQueue:(id)queue completionBlock:(id)block;
-(void)invalidate;
-(void)playRemoteWithParams:(id)params completionQueue:(id)queue completionBlock:(id)block;
-(void)playWithLocalFilePath:(id)localFilePath startPosition:(float)position playInfo:(id)info completionQueue:(id)queue completionBlock:(id)block;
-(void)setEventHandlerQueue:(id)queue eventHandlerBlock:(id)block;
-(void)setHost:(id)host;
-(void)setPassword:(id)password;
-(void)setPosition:(float)position completionQueue:(id)queue completionBlock:(id)block;
-(void)setRate:(float)rate completionQueue:(id)queue completionBlock:(id)block;
-(void)setVolume:(float)volume completionQueue:(id)queue completionBlock:(id)block;
-(void)stopWithOptions:(unsigned)options completionQueue:(id)queue completionBlock:(id)block;
@end

