/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MediaPlayer-Structs.h"


@interface MPButton : XXUnknownSuperclass {
	UIEdgeInsets _hitRectInsets;
	double _holdDelayInterval;
	unsigned _holding : 1;
}
@property(assign, nonatomic) UIEdgeInsets hitRectInsets;	// @synthesize=_hitRectInsets
@property(assign, nonatomic) double holdDelayInterval;	// @synthesize=_holdDelayInterval
+(id)easyTouchButtonWithType:(int)type;
+(float)easyTouchDefaultCharge;
+(UIEdgeInsets)easyTouchDefaultHitRectInsets;
-(id)initWithFrame:(CGRect)frame;
-(void)_delayedTriggerHold;
-(void)_handleTouchCancel;
-(void)_handleTouchDown;
-(void)_handleTouchUp;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)cancelTrackingWithEvent:(id)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(CGRect)hitRect;
// declared property getter: -(UIEdgeInsets)hitRectInsets;
// declared property getter: -(double)holdDelayInterval;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
// declared property setter: -(void)setHitRectInsets:(UIEdgeInsets)insets;
// declared property setter: -(void)setHoldDelayInterval:(double)interval;
@end

