/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "MPFlipTransitionController.h"

@class UINavigationItem, UITextLabel, UINavigationBar;

@interface MPVideoChapterFlipTransitionController : MPFlipTransitionController {
	UINavigationBar* _navigationBar;
	UINavigationItem* _originalNavigationItem;
	UITextLabel* _chapterGuideTitleLabel;
	BOOL _shouldPlayAfterFlip;
	BOOL _tvOutEnabled;
}
@property(assign, nonatomic) BOOL TVOutEnabled;	// @synthesize=_tvOutEnabled
@property(retain, nonatomic) UINavigationBar* navigationBar;	// @synthesize=_navigationBar
@property(assign, nonatomic) BOOL playAfterFlip;	// @synthesize=_shouldPlayAfterFlip
// declared property getter: -(BOOL)TVOutEnabled;
-(id)_chapterGuideTitleLabel;
-(id)_copySwizzledNavigationViews;
-(void)_done:(id)done;
-(void)_hideNavigationAndStatusBars;
-(void)_hideNavigationBarAnimationDidFinish:(id)_hideNavigationBarAnimation;
-(int)_interfaceOrientation;
-(void)_restoreOriginalNavigationViews:(BOOL)views;
-(void)_showChapterGuideNavigationViews;
-(void)dealloc;
// declared property getter: -(id)navigationBar;
-(void)performTransition:(unsigned)transition;
// declared property getter: -(BOOL)playAfterFlip;
// declared property setter: -(void)setNavigationBar:(id)bar;
// declared property setter: -(void)setPlayAfterFlip:(BOOL)flip;
// declared property setter: -(void)setTVOutEnabled:(BOOL)enabled;
@end

