/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import </libxml2.2.h>

@class NSError;

@interface _NSJSONReader : NSObject {
	id input;
	int kind;
	NSError* error;
}
+(BOOL)validForJSON:(id)json depth:(unsigned)depth allowFragments:(BOOL)fragments;
-(id)init;
-(void)dealloc;
-(id)error;
-(unsigned)findEncodingFromData:(id)data withBOMSkipLength:(unsigned*)bomskipLength;
-(id)parseData:(id)data options:(unsigned)options;
-(id)parseStream:(id)stream options:(unsigned)options;
-(id)parseUTF8JSONData:(id)data skipBytes:(unsigned)bytes options:(unsigned)options;
-(void)setError:(id)error;
@end

