/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Foundation-Structs.h"

@class NSCalendar, NSLocale, NSTimeZone, NSDate;

__attribute__((visibility("hidden")))
@interface NSAutoCalendar : XXUnknownSuperclass {
@private
	NSCalendar* cal;
	NSLocale* changedLocale;
	NSTimeZone* changedTimeZone;
	unsigned changedFirstWeekday;
	unsigned changedMinimumDaysinFirstWeek;
	NSDate* changedGregorianStartDate;
}
+(BOOL)supportsSecureCoding;
-(id)init;
-(id)initWithCalendarIdentifier:(id)calendarIdentifier;
-(id)initWithCoder:(id)coder;
-(void)_update:(id)update;
-(id)calendarIdentifier;
-(Class)classForCoder;
-(id)components:(unsigned)components fromDate:(id)date;
-(id)components:(unsigned)components fromDate:(id)date toDate:(id)date3 options:(unsigned)options;
-(id)copyWithZone:(NSZone*)zone;
-(id)dateByAddingComponents:(id)components toDate:(id)date options:(unsigned)options;
-(id)dateFromComponents:(id)components;
-(void)dealloc;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(unsigned)firstWeekday;
-(id)gregorianStartDate;
-(id)locale;
-(NSRange)maximumRangeOfUnit:(unsigned)unit;
-(unsigned)minimumDaysInFirstWeek;
-(NSRange)minimumRangeOfUnit:(unsigned)unit;
-(unsigned)ordinalityOfUnit:(unsigned)unit inUnit:(unsigned)unit2 forDate:(id)date;
-(NSRange)rangeOfUnit:(unsigned)unit inUnit:(unsigned)unit2 forDate:(id)date;
-(BOOL)rangeOfUnit:(unsigned)unit startDate:(id*)date interval:(double*)interval forDate:(id)date4;
-(void)setFirstWeekday:(unsigned)weekday;
-(void)setGregorianStartDate:(id)date;
-(void)setLocale:(id)locale;
-(void)setMinimumDaysInFirstWeek:(unsigned)firstWeek;
-(void)setTimeZone:(id)zone;
-(id)timeZone;
@end

