/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSHashTable.h"


__attribute__((visibility("hidden")))
@interface NSClassicHashTable : NSHashTable {
@private
	struct {
		/*function-pointer*/ void* hash;
		/*function-pointer*/ void* isEqual;
		/*function-pointer*/ void* retain;
		/*function-pointer*/ void* release;
		/*function-pointer*/ void* describe;
	} _callBacks;
	CFBasicHashRef _ht;
}
-(id)init;
-(void)addObject:(id)object;
-(id)allObjects;
-(id)copy;
-(unsigned)count;
-(void)dealloc;
-(id)description;
-(void*)getItem:(const void*)item;
-(void)getKeys:(const void**)keys count:(unsigned*)count;
-(unsigned)hash;
-(void)insertItem:(const void*)item;
-(void)insertKnownAbsentItem:(const void*)item;
-(BOOL)isEqual:(id)equal;
-(void)removeAllItems;
-(void)removeItem:(const void*)item;
@end

