/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSTask.h"

@class NSPort, NSMutableDictionary;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface NSConcreteTask : NSTask {
@private
	NSMutableDictionary* _dictionary;
	BOOL _hasExeced;
	BOOL _isRunning;
	BOOL _hasPostedDeathNotification;
	BOOL _terminationRun;
	int _suspendCount;
	id _terminationHandler;
	int _pid;
	int _platformExitInfo;
	NSObject<OS_dispatch_source>* _dsrc;
	NSPort* _tmpPort;
}
-(id)init;
-(int)_platformExitInformation;
-(int)_procid;
-(id)arguments;
-(id)currentDirectoryPath;
-(void)dealloc;
-(id)environment;
-(void)finalize;
-(void)interrupt;
-(BOOL)isRunning;
-(void)launch;
-(id)launchPath;
-(void)launchWithDictionary:(id)dictionary;
-(id)preferredArchitectures;
-(int)processIdentifier;
-(BOOL)resume;
-(void)setArguments:(id)arguments;
-(void)setCurrentDirectoryPath:(id)path;
-(void)setEnvironment:(id)environment;
-(void)setLaunchPath:(id)path;
-(void)setPreferredArchitectures:(id)architectures;
-(void)setStandardError:(id)error;
-(void)setStandardInput:(id)input;
-(void)setStandardOutput:(id)output;
-(void)setStartsNewProcessGroup:(BOOL)group;
-(void)setTaskDictionary:(id)dictionary;
-(void)setTerminationHandler:(id)handler;
-(id)standardError;
-(id)standardInput;
-(id)standardOutput;
-(BOOL)suspend;
-(int)suspendCount;
-(id)taskDictionary;
-(void)terminate;
-(void)terminateTask;
-(id)terminationHandler;
-(int)terminationReason;
-(int)terminationStatus;
-(void)waitUntilExit;
@end

