/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "NSDecimalNumber.h"


__attribute__((visibility("hidden")))
@interface NSDecimalNumberPlaceholder : NSDecimalNumber {
}
+(id)allocWithZone:(NSZone*)zone;
-(id)init;
-(id)initWithBool:(BOOL)aBool;
-(id)initWithChar:(BOOL)aChar;
-(id)initWithCoder:(id)coder;
-(id)initWithDecimal:(XXStruct_9isexA)decimal;
-(id)initWithDouble:(double)aDouble;
-(id)initWithFloat:(float)aFloat;
-(id)initWithInt:(int)int;
-(id)initWithInteger:(int)integer;
-(id)initWithLong:(long)aLong;
-(id)initWithLongLong:(long long)longLong;
-(id)initWithMantissa:(unsigned long long)mantissa exponent:(short)exponent isNegative:(BOOL)negative;
-(id)initWithShort:(short)aShort;
-(id)initWithString:(id)string;
-(id)initWithString:(id)string locale:(id)locale;
-(id)initWithUnsignedChar:(unsigned char)unsignedChar;
-(id)initWithUnsignedInt:(unsigned)unsignedInt;
-(id)initWithUnsignedInteger:(unsigned)unsignedInteger;
-(id)initWithUnsignedLong:(unsigned long)unsignedLong;
-(id)initWithUnsignedLongLong:(unsigned long long)unsignedLongLong;
-(id)initWithUnsignedShort:(unsigned short)unsignedShort;
-(id)autorelease;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
@end

