/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import </libxml2.2.h>

@class NSArray, NSMutableDictionary, NSData, NSString;

__attribute__((visibility("hidden")))
@interface NSHTTPURLRequestParameters : NSObject {
@private
	NSString* method;
	NSMutableDictionary* fields;
	NSArray* extraCookies;
	NSData* data;
	unsigned pageNotFoundCacheLifetime;
	BOOL shouldHandleCookies;
	BOOL _pad1;
	BOOL _pad2;
	BOOL _pad3;
}
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
@end

