/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import </libxml2.2.h>
#import "Foundation-Structs.h"


@interface NSMetadataItem : NSObject {
@private
	id _item;
	void* _reserved;
}
-(id)_init:(XXUnion_6NHX5C)init;
-(void)_setQuery:(id)query;
-(id)attributes;
-(void)dealloc;
-(id)valueForAttribute:(id)attribute;
-(id)valueForKey:(id)key;
-(id)valuesForAttributes:(id)attributes;
@end

