/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSProgress.h"


__attribute__((visibility("hidden")))
@interface NSProgressProxy : NSProgress {
@private
	id<NSProgressPublisher> _forwarder;
	BOOL _isOld;
	id _unpublishingHandler;
}
-(id)_initWithForwarder:(id)forwarder values:(id)values isOld:(BOOL)old;
-(void)_invokePublishingHandler:(id)handler;
-(void)_invokeUnpublishingHandler;
-(void)acknowledgeWithSuccess:(BOOL)success;
-(void)becomeCurrentWithPendingUnitCount:(long long)pendingUnitCount;
-(void)cancel;
-(void)dealloc;
-(BOOL)isOld;
-(void)pause;
-(void)publish;
-(void)resignCurrent;
-(void)setCancellable:(BOOL)cancellable;
-(void)setCancellationHandler:(id)handler;
-(void)setCompletedUnitCount:(long long)count;
-(void)setKind:(id)kind;
-(void)setLocalizedDescription:(id)description;
-(void)setPausable:(BOOL)pausable;
-(void)setPausingHandler:(id)handler;
-(void)setTotalUnitCount:(long long)count;
-(void)setUserInfoObject:(id)object forKey:(id)key;
-(void)unpublish;
@end

