/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import </libxml2.2.h>

@class NSURLFileTypeMappingsInternal;

@interface NSURLFileTypeMappings : NSObject {
@private
	NSURLFileTypeMappingsInternal* _internal;
}
+(id)sharedMappings;
-(id)MIMETypeForExtension:(id)extension;
-(id)_UTIMIMETypeForExtension:(id)extension;
-(id)_UTIextensionForMIMEType:(id)mimetype;
-(id)_init;
-(id)extensionsForMIMEType:(id)mimetype;
-(id)preferredExtensionForMIMEType:(id)mimetype;
@end

