/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import </libxml2.2.h>


@interface NSValueTransformer : NSObject {
}
+(id)_transformerRegistry;
+(BOOL)allowsReverseTransformation;
+(void)setValueTransformer:(id)transformer forName:(id)name;
+(Class)transformedValueClass;
+(id)valueTransformerForName:(id)name;
+(id)valueTransformerNames;
-(id)reverseTransformedValue:(id)value;
-(id)transformedValue:(id)value;
@end

