/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol CalendarEventAlarmTableDelegate, EKStyleProvider;

@interface CalendarEventAlarmTable : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	int _alarmIdentifier;
	NSString* _customString;
	BOOL _customSelected;
	int _selectedItem;
	id<CalendarEventAlarmTableDelegate> _alarmTableDelegate;
	id<EKStyleProvider> _styleProvider;
	BOOL _useAllDayAlarms;
	BOOL _shouldAllowAlarmsTriggeringAfterStartDate;
}
@property(assign, nonatomic) id<CalendarEventAlarmTableDelegate> alarmTableDelegate;	// @synthesize=_alarmTableDelegate
@property(assign, nonatomic) BOOL shouldAllowAlarmsTriggeringAfterStartDate;	// @synthesize=_shouldAllowAlarmsTriggeringAfterStartDate
@property(retain, nonatomic) id<EKStyleProvider> styleProvider;	// @synthesize=_styleProvider
@property(assign, nonatomic) BOOL useAllDayAlarms;	// @synthesize=_useAllDayAlarms
-(id)initWithFrame:(CGRect)frame;
-(int)_presetIdentifierForRow:(int)row;
-(int)_rowForPresetIdentifier:(int)presetIdentifier;
-(void)_selectRow:(int)row;
// declared property getter: -(id)alarmTableDelegate;
-(int)countOfPresets;
-(BOOL)customSelected;
-(void)dealloc;
-(int)intervalForPresetIdentifier:(int)presetIdentifier;
-(int)presetIdentifier;
-(int)presetIdentifierAtIndex:(int)index;
// declared property setter: -(void)setAlarmTableDelegate:(id)delegate;
-(void)setCustomSelected:(BOOL)selected;
-(void)setCustomString:(id)string;
-(void)setPresetIdentifier:(int)identifier;
// declared property setter: -(void)setShouldAllowAlarmsTriggeringAfterStartDate:(BOOL)allowAlarmsTriggeringAfterStartDate;
// declared property setter: -(void)setStyleProvider:(id)provider;
// declared property setter: -(void)setUseAllDayAlarms:(BOOL)alarms;
// declared property getter: -(BOOL)shouldAllowAlarmsTriggeringAfterStartDate;
// declared property getter: -(id)styleProvider;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
// declared property getter: -(BOOL)useAllDayAlarms;
@end

