/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSPredicate, EKEventStore, NSMutableSet, NSArray;
@protocol CalendarEventLoaderDelegate;

@interface CalendarEventLoader : XXUnknownSuperclass {
	EKEventStore* _store;
	CalFilter* _filter;
	NSPredicate* _predicate;
	id<CalendarEventLoaderDelegate> _delegate;
	NSArray* _occurrences;
	NSArray* _selectedDateOccurrences;
	NSMutableSet* _occurrencesAwaitingRefresh;
	NSMutableSet* _occurrencesAwaitingDeletion;
	dispatch_queue_s* _queue;
	dispatch_queue_s* _lock;
	dispatch_group_s* _group;
	int _seed;
	int _backgroundSeed;
	NSArray* _backgroundResults;
	unsigned _paddingMonthsToLoad;
	BOOL _loadsBlocked;
	BOOL _processingReload;
	NSPredicate* _backgroundPredicate;
	id _backgroundRequest;
	double _selectedDate;
	XXStruct_lQVxyC _selectedDateGr;
	XXStruct_lQVxyC _selectedDateTimeGr;
	double _start;
	double _end;
	XXStruct_lQVxyC _startGr;
	XXStruct_lQVxyC _endGr;
}
@property(assign, nonatomic) id<CalendarEventLoaderDelegate> delegate;	// @synthesize=_delegate
@property(retain, nonatomic) CalFilter* filter;
@property(assign, nonatomic) BOOL loadsBlocked;
@property(assign, nonatomic) unsigned paddingMonthsToLoad;
-(id)initWithEventStore:(id)eventStore;
-(BOOL)_backgroundLoadCompleted:(id)completed;
-(void)_beginBackgroundLoadForPredicate:(id)predicate;
-(void)_clearOccurrences;
-(void)_eventStoreChanged:(id)changed;
-(void)_notifyDelegateThatOccurrencesDidUpdate;
-(void)_reload:(BOOL)reload;
-(void)_reloadOccurrences;
-(void)_setDisplayedDateRange:(XXStruct_lQVxyC)range end:(XXStruct_lQVxyC)end loadMethod:(int)method;
-(void)_updatePredicate;
-(void)addOccurrenceAwaitingDeletion:(id)deletion;
-(void)addOccurrenceAwaitingRefresh:(id)refresh;
-(void)cancelBackgroundLoad;
-(void)dealloc;
// declared property getter: -(id)delegate;
// declared property getter: -(CalFilter*)filter;
// declared property getter: -(BOOL)loadsBlocked;
-(id)occurrencesForDay:(XXStruct_lQVxyC)day waitForLoad:(BOOL)load;
-(id)occurrencesForStartDate:(id)startDate endDate:(id)date waitForLoad:(BOOL)load;
// declared property getter: -(unsigned)paddingMonthsToLoad;
-(XXStruct_lQVxyC)selectedDate;
-(id)selectedDateOccurrences:(BOOL)occurrences;
-(id)selectedDateOccurrences:(BOOL)occurrences loadIsComplete:(BOOL*)complete;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setFilter:(CalFilter*)filter;
// declared property setter: -(void)setLoadsBlocked:(BOOL)blocked;
// declared property setter: -(void)setPaddingMonthsToLoad:(unsigned)load;
-(void)setSelectedDate:(XXStruct_lQVxyC)date loadMethod:(int)method;
-(void)timeZoneChanged;
-(BOOL)waitForBackgroundLoad;
@end

