/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Twitter.framework/Twitter
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, ACAccount, OACredential, NSURL, NSMutableDictionary, NSDictionary;

@interface TWRequest : XXUnknownSuperclass {
@private
	ACAccount* _account;
	OACredential* _credential;
	int _callingPID;
	NSURL* _url;
	NSMutableDictionary* _parameters;
	int _requestMethod;
	NSMutableArray* _multiParts;
}
@property(readonly, assign, nonatomic) NSURL* URL;	// @synthesize=_url
@property(retain, nonatomic) ACAccount* account;	// @synthesize=_account
@property(readonly, assign, nonatomic) NSDictionary* parameters;	// @synthesize=_parameters
@property(readonly, assign, nonatomic) int requestMethod;	// @synthesize=_requestMethod
+(BOOL)shouldRetryAfterCount:(int)count delay:(float*)delay;
-(id)initWithCredential:(id)credential URL:(id)url;
-(id)initWithURL:(id)url;
-(id)initWithURL:(id)url parameters:(id)parameters requestMethod:(int)method;
// declared property getter: -(id)URL;
-(id)_parameterString;
-(id)_urlEncodedString:(id)string;
// declared property getter: -(id)account;
-(void)addMultiPartData:(id)data withName:(id)name type:(id)type;
-(int)callingPID;
-(id)commandName;
-(id)credential;
-(void)dealloc;
-(id)multiPartBodyData;
// declared property getter: -(id)parameters;
-(void)performJSONRequestWithHandler:(id)handler;
-(void)performJSONRequestWithHandler:(id)handler retryCount:(int)count;
-(void)performRequestWithHandler:(id)handler;
// declared property getter: -(int)requestMethod;
-(BOOL)requiresAuthorization;
// declared property setter: -(void)setAccount:(id)account;
-(void)setCallingPID:(int)pid;
-(void)setCredential:(id)credential;
-(void)setParameter:(id)parameter forKey:(id)key;
-(void)setRequestMethod:(int)method;
-(void)sharedPrivateInit;
-(id)signedURLRequest;
@end

