/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/ExternalAccessory.framework/ExternalAccessory
 */

#import <Foundation/NSMutableData.h>
#import "BTDevicePickerDelegate.h"

@class BTDevicePicker;
@protocol EABluetoothAccessoryPickerDelegate;

@interface EABluetoothAccessoryPicker : NSMutableData <BTDevicePickerDelegate> {
	BTDevicePicker* _picker;
	id<EABluetoothAccessoryPickerDelegate> _delegate;
}
@property(assign, nonatomic) id<EABluetoothAccessoryPickerDelegate> delegate;	// @synthesize=_delegate
+(void)wakeSelectedBluetoothAccessories:(id)accessories;
-(id)initWithPredicate:(id)predicate;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)devicePicker:(id)picker didDismissWithResult:(int)result device:(id)device;
-(void)dismissPicker;
// declared property setter: -(void)setDelegate:(id)delegate;
-(void)show;
@end

