/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "NSDate.h"


__attribute__((visibility("hidden")))
@interface __NSPlaceholderDate : NSDate {
}
+(id)immutablePlaceholder;
+(void)initialize;
-(id)init;
-(id)initWithTimeIntervalSinceReferenceDate:(double)timeIntervalSinceReferenceDate;
-(void)dealloc;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
-(double)timeIntervalSinceReferenceDate;
@end

