/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import "CoreFoundation-Structs.h"
#import </libobjc.A.h>
#import "NSCopying.h"
#import "NSMutableCopying.h"
#import "NSSecureCoding.h"
#import "NSFastEnumeration.h"


@interface NSArray : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {
}
+(id)allocWithZone:(NSZone*)zone;
+(id)array;
+(id)arrayWithArray:(id)array;
+(id)arrayWithArray:(id)array copyItems:(BOOL)items;
+(id)arrayWithArray:(id)array range:(NSRange)range;
+(id)arrayWithArray:(id)array range:(NSRange)range copyItems:(BOOL)items;
+(id)arrayWithObject:(id)object;
+(id)arrayWithObjects:(id)objects;
+(id)arrayWithObjects:(const id*)objects count:(unsigned)count;
+(id)arrayWithOrderedSet:(id)orderedSet;
+(id)arrayWithOrderedSet:(id)orderedSet copyItems:(BOOL)items;
+(id)arrayWithOrderedSet:(id)orderedSet range:(NSRange)range;
+(id)arrayWithOrderedSet:(id)orderedSet range:(NSRange)range copyItems:(BOOL)items;
+(id)arrayWithSet:(id)set;
+(id)arrayWithSet:(id)set copyItems:(BOOL)items;
+(id)newArrayWithObjects:(const id*)objects count:(unsigned)count;
+(BOOL)supportsSecureCoding;
-(id)initWithArray:(id)array;
-(id)initWithArray:(id)array copyItems:(BOOL)items;
-(id)initWithArray:(id)array range:(NSRange)range;
-(id)initWithArray:(id)array range:(NSRange)range copyItems:(BOOL)items;
-(id)initWithCoder:(id)coder;
-(id)initWithObject:(id)object;
-(id)initWithObjects:(id)objects;
-(id)initWithObjects:(const id*)objects count:(unsigned)count;
-(id)initWithOrderedSet:(id)orderedSet;
-(id)initWithOrderedSet:(id)orderedSet copyItems:(BOOL)items;
-(id)initWithOrderedSet:(id)orderedSet range:(NSRange)range;
-(id)initWithOrderedSet:(id)orderedSet range:(NSRange)range copyItems:(BOOL)items;
-(id)initWithSet:(id)set;
-(id)initWithSet:(id)set copyItems:(BOOL)items;
-(unsigned long)_cfTypeID;
-(BOOL)_hasObjects;
-(BOOL)_hasStrongReferences;
-(id)allObjects;
-(id)arrayByAddingObject:(id)object;
-(id)arrayByAddingObjectsFromArray:(id)array;
-(id)arrayByApplyingSelector:(SEL)selector;
-(id)arrayByExcludingObjectsInArray:(id)array;
-(id)arrayByExcludingToObjectsInArray:(id)array;
-(id)componentsJoinedByString:(id)string;
-(BOOL)containsObject:(id)object;
-(BOOL)containsObject:(id)object inRange:(NSRange)range;
-(BOOL)containsObjectIdenticalTo:(id)to;
-(BOOL)containsObjectIdenticalTo:(id)to inRange:(NSRange)range;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)count;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(unsigned)countForObject:(id)object;
-(unsigned)countForObject:(id)object inRange:(NSRange)range;
-(id)description;
-(id)descriptionWithLocale:(id)locale;
-(id)descriptionWithLocale:(id)locale indent:(unsigned)indent;
-(void)encodeWithCoder:(id)coder;
-(void)enumerateObjectsAtIndexes:(id)indexes options:(unsigned)options usingBlock:(id)block;
-(void)enumerateObjectsUsingBlock:(id)block;
-(void)enumerateObjectsWithOptions:(unsigned)options usingBlock:(id)block;
-(id)firstObject;
-(id)firstObjectCommonWithArray:(id)array;
-(void)getObjects:(id*)objects;
-(void)getObjects:(id*)objects range:(NSRange)range;
-(unsigned)hash;
-(unsigned)indexOfObject:(id)object;
-(unsigned)indexOfObject:(id)object inRange:(NSRange)range;
-(unsigned)indexOfObject:(id)object inSortedRange:(NSRange)sortedRange options:(unsigned)options usingComparator:(id)comparator;
-(unsigned)indexOfObjectAtIndexes:(id)indexes options:(unsigned)options passingTest:(id)test;
-(unsigned)indexOfObjectIdenticalTo:(id)to;
-(unsigned)indexOfObjectIdenticalTo:(id)to inRange:(NSRange)range;
-(unsigned)indexOfObjectPassingTest:(id)objectPassingTest;
-(unsigned)indexOfObjectWithOptions:(unsigned)options passingTest:(id)test;
-(id)indexesOfObject:(id)object;
-(id)indexesOfObject:(id)object inRange:(NSRange)range;
-(id)indexesOfObjectIdenticalTo:(id)to;
-(id)indexesOfObjectIdenticalTo:(id)to inRange:(NSRange)range;
-(id)indexesOfObjectsAtIndexes:(id)indexes options:(unsigned)options passingTest:(id)test;
-(id)indexesOfObjectsPassingTest:(id)objectsPassingTest;
-(id)indexesOfObjectsWithOptions:(unsigned)options passingTest:(id)test;
-(BOOL)isEqual:(id)equal;
-(BOOL)isEqualToArray:(id)array;
-(BOOL)isNSArray__;
-(id)lastObject;
-(void)makeObjectsPerformSelector:(SEL)selector;
-(void)makeObjectsPerformSelector:(SEL)selector withObject:(id)object;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)objectAtIndex:(unsigned)index;
-(id)objectAtIndexedSubscript:(unsigned)indexedSubscript;
-(id)objectEnumerator;
-(id)objectsAtIndexes:(id)indexes;
-(id)objectsAtIndexes:(id)indexes options:(unsigned)options passingTest:(id)test;
-(id)objectsPassingTest:(id)test;
-(id)objectsWithOptions:(unsigned)options passingTest:(id)test;
-(id)reverseObjectEnumerator;
-(id)reversedArray;
-(id)sortedArrayFromRange:(NSRange)range options:(unsigned)options usingComparator:(id)comparator;
-(id)sortedArrayUsingComparator:(id)comparator;
-(id)sortedArrayUsingFunction:(/*function-pointer*/ void*)function context:(void*)context;
-(id)sortedArrayUsingSelector:(SEL)selector;
-(id)sortedArrayWithOptions:(unsigned)options usingComparator:(id)comparator;
-(id)subarrayWithRange:(NSRange)range;
@end

