/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

#import </libobjc.A.h>
#import "CoreFoundation-Structs.h"
#import "NSCopying.h"
#import "NSCoding.h"
#import "NSFastEnumeration.h"


@interface NSSharedKeySet : NSObject <NSFastEnumeration, NSCopying, NSCoding> {
@private
	char* _g;
	unsigned char _select;
	void* _rankTable;
	double _c;
	unsigned _M;
	unsigned _factor;
	unsigned _numKey;
	unsigned _seeds[2];
	id* _keys;
	NSSharedKeySet* _subSharedKeySet;
}
+(id)keySetWithKeys:(id)keys;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)initWithKeys:(id*)keys count:(unsigned)count;
-(id)allKeys;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)count;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)createSubclassCode:(id)code interface:(const CFStringRef*)interface implementation:(const CFStringRef*)implementation;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)finalize;
-(unsigned)indexForKey:(id)key;
-(BOOL)isEmpty;
-(id)keyAtIndex:(unsigned)index;
-(unsigned)keySetCount;
-(unsigned)maximumIndex;
@end

