/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface MFAddressPickerReformatter : XXUnknownSuperclass {
@private
	NSArray* _addresses;
	NSArray* _reformattedAddresses;
	float _maximumWidth;
	float _fontSize;
	unsigned _context;
}
-(void)_attemptUniquingDisplayedStrings;
-(BOOL)_attemptUniquingDisplayedStringsUsingBlock:(id)block;
-(void)_determineFontSize:(BOOL*)size;
-(void)_expandAllLocalParts;
-(void)_invalidateReformattedAddresses;
-(id)_reformattedAddressesByDisplayedStrings;
-(BOOL)_reformattedAddressesByDisplayedStringsAreUnique:(id)unique;
-(void)_restoreMiddleTruncationRanges:(id)ranges;
-(id)_saveMiddleTruncationRanges;
-(void)_truncateIdenticalLocalPartsWithDifferentDomainParts;
-(void)_truncateIdenticalLocalPartsWithDifferentDomainPartsWithTailLength:(unsigned)tailLength options:(unsigned)options;
-(void)_updateReformattedAddressesIfNecessary;
-(void)dealloc;
-(unsigned)numberOfReformattedAddresses;
-(id)reformattedAddressAtIndex:(unsigned)index;
-(void)setAddresses:(id)addresses;
-(void)setContext:(unsigned)context;
-(void)setMaximumWidth:(float)width;
@end

