/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MFComposeRecipient.h"

@class NSString;

@interface MFCalendarComposeRecipient : MFComposeRecipient {
	NSString* _calAttendeeName;
	id _participant;
}
@property(retain, nonatomic) id participant;
-(id)initWithComposeRecipient:(id)composeRecipient;
-(void)dealloc;
-(id)displayString;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
// declared property getter: -(id)participant;
-(void)setCalAttendeeName:(id)name;
// declared property setter: -(void)setParticipant:(id)participant;
@end

