/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */



@protocol MFComposeTypeFactoryDelegate
-(id)accountProxyGenerator;
-(id)addInlinedElementToStore:(id)store onlyIfNecessary:(BOOL)necessary;
-(id)attachmentStore;
-(id)bccRecipients;
-(id)bodyField;
-(id)ccRecipients;
-(id)savedHeaders;
-(id)sendingAccountProxy;
-(id)sendingEmailAddress;
-(void)setBccRecipients:(id)recipients;
-(void)setCcRecipients:(id)recipients;
-(void)setSavedHeaders:(id)headers;
-(void)setSendingEmailAddress:(id)address addIfNotPresent:(BOOL)present;
-(void)setSubject:(id)subject;
-(void)setToRecipients:(id)recipients;
-(id)subject;
-(id)toRecipients;
@end

