/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "DASearchQueryConsumer.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MessageUI-Structs.h"

@class NSOrderedSet, NSObject, NSMutableDictionary, NSArray, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface MFContactsSearchManager : XXUnknownSuperclass <DASearchQueryConsumer> {
@private
	CFDictionaryRef _taskIDsBySearchQuery;
	NSMutableDictionary* _taskContextsByTaskID;
	void* _addressBook;
	NSOperationQueue* _queue;
	unsigned _genNumber;
	NSOrderedSet* _properties;
	unsigned _searchTypes;
	NSArray* _searchAccountIDs;
	NSObject<OS_dispatch_queue>* _serverSearchQueue;
	BOOL _registeredForAddressBookChanges;
	NSString* _recentsBundleIdentifier;
	NSString* _sendingAddress;
}
@property(copy, nonatomic) NSString* recentsBundleIdentifier;	// @synthesize=_recentsBundleIdentifier
@property(retain) NSArray* searchAccountIDs;	// @synthesize=_searchAccountIDs
@property(copy, nonatomic) NSString* sendingAddress;	// @synthesize=_sendingAddress
-(id)initWithAddressBook:(void*)addressBook properties:(int*)properties propertyCount:(unsigned)count;
-(id)initWithAddressBook:(void*)addressBook properties:(int*)properties propertyCount:(unsigned)count recentsBundleIdentifier:(id)identifier;
-(void)_handleAddressBookChangeNotification;
-(void)_handleLocalSearchResults:(id)results type:(int)type operation:(id)operation taskID:(id)anId;
-(void)_handleRecentsSearchFrequentResults:(id)results infrequentResults:(id)results2 operation:(id)operation taskID:(id)anId;
-(void)_handleSearchQueriesByAccountID:(id)anId operation:(id)operation taskID:(id)anId3;
-(void)_handleSearchQuery:(id)query finishedWithError:(id)error;
-(void)_handleSearchQuery:(id)query returnedResults:(id)results;
-(void)_handleSearchQueryFinished:(id)finished context:(id)context;
-(void)_handleTaskFinished:(id)finished context:(id)context;
-(void)_registerForAddressBookChanges;
-(id)_serverSearchQueue;
-(void)cancelTaskWithID:(id)anId;
-(void)dealloc;
// declared property getter: -(id)recentsBundleIdentifier;
// declared property getter: -(id)searchAccountIDs;
-(id)searchForText:(id)text consumer:(id)consumer;
-(void)searchQuery:(id)query finishedWithError:(id)error;
-(void)searchQuery:(id)query returnedResults:(id)results;
// declared property getter: -(id)sendingAddress;
// declared property setter: -(void)setRecentsBundleIdentifier:(id)identifier;
// declared property setter: -(void)setSearchAccountIDs:(id)ids;
-(void)setSearchTypes:(unsigned)types;
// declared property setter: -(void)setSendingAddress:(id)address;
@end

