/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import "MessageUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIView, MFHeaderLabelView;

@interface MFComposeHeaderView : XXUnknownSuperclass {
	NSString* _label;
	NSString* _navTitle;
	MFHeaderLabelView* _labelView;
	id _delegate;
	UIView* _separator;
@private
	BOOL _drawsLetterpress;
}
@property(assign, nonatomic) BOOL drawsLetterpress;	// @synthesize=_drawsLetterpress
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)frame;
-(id)_automationID;
-(BOOL)_canBecomeFirstResponder;
-(void)dealloc;
// declared property getter: -(BOOL)drawsLetterpress;
-(void)handleTouchesEnded;
-(CGColorRef)labelColor;
-(void)layoutSubviews;
-(float)maxLabelX;
-(id)navTitle;
-(void)setDelegate:(id)delegate;
// declared property setter: -(void)setDrawsLetterpress:(BOOL)letterpress;
-(void)setFrame:(CGRect)frame;
-(void)setLabel:(id)label;
-(void)setLabelHighlighted:(BOOL)highlighted;
-(void)setNavTitle:(id)title;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

