/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "CAAnimation.h"
#import "QuartzCore-Structs.h"

@class NSArray;

@interface CAAnimationGroup : CAAnimation {
}
@property(copy) NSArray* animations;
-(void)CA_prepareRenderValue;
-(Animation*)_copyRenderAnimationForLayer:(id)layer;
-(unsigned)_propertyFlagsForLayer:(id)layer;
// declared property getter: -(id)animations;
-(void)applyForTime:(double)time presentationObject:(id)object modelObject:(id)object3;
// declared property setter: -(void)setAnimations:(id)animations;
-(void)setDefaultDuration:(double)duration;
@end

