/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface MFMailAccountProxy : XXUnknownSuperclass {
	NSDictionary* _properties;
}
+(id)accountContainingEmailAddress:(id)address includingInactive:(BOOL)inactive;
+(id)activeAccounts;
+(id)defaultMailAccountForDelivery;
+(id)mailAccounts;
+(void)reloadAccounts;
-(id)_emailAddressesAndAliases;
-(id)_initWithProperties:(id)properties;
-(BOOL)_isActive;
-(BOOL)_isRestricted;
-(BOOL)allowsEmoji;
-(void)dealloc;
-(id)emailAddresses;
-(id)firstEmailAddress;
-(id)fromEmailAddresses;
-(id)fullUserName;
-(BOOL)isDefaultDeliveryAccount;
-(id)mailAccount;
-(BOOL)restrictsRepliesAndForwards;
-(BOOL)supportsEmoji;
-(id)uniqueID;
-(id)username;
@end

