/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface CalItemMetadata : XXUnknownSuperclass <NSCoding> {
@private
	NSDictionary* _x_props;
	int _classification;
}
@property(assign) int classification;	// @synthesize=_classification
@property(retain) NSDictionary* x_props;	// @synthesize=_x_props
+(id)metadataWithData:(id)data;
+(id)metadataWithICSComponent:(id)icscomponent;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)initWithICSComponent:(id)icscomponent;
-(void)applyToComponent:(id)component;
// declared property getter: -(int)classification;
-(id)dataRepresentationWithExistingMetaData:(id)existingMetaData;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
// declared property setter: -(void)setClassification:(int)classification;
// declared property setter: -(void)setX_props:(id)props;
// declared property getter: -(id)x_props;
@end

