/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSTimeZone, EKObjectID, NSString;

@interface EKAlarmOccurrence : XXUnknownSuperclass {
@private
	EKObjectID* _alarmID;
	EKObjectID* _ownerID;
	NSDate* _ownerDate;
	NSTimeZone* _ownerTimeZone;
	NSDate* _fireDate;
	NSString* _externalID;
	NSDate* _acknowledgedDate;
}
@property(readonly, assign, nonatomic) NSDate* acknowledgedDate;	// @synthesize=_acknowledgedDate
@property(readonly, assign, nonatomic) EKObjectID* alarmID;	// @synthesize=_alarmID
@property(readonly, assign, nonatomic) NSString* externalID;	// @synthesize=_externalID
@property(readonly, assign, nonatomic) NSDate* fireDate;	// @synthesize=_fireDate
@property(readonly, assign, nonatomic) NSDate* ownerDate;	// @synthesize=_ownerDate
@property(readonly, assign, nonatomic) EKObjectID* ownerID;	// @synthesize=_ownerID
@property(readonly, assign, nonatomic) NSTimeZone* ownerTimeZone;	// @synthesize=_ownerTimeZone
+(id)alarmOccurrenceWithAlarmID:(id)alarmID ownerID:(id)anId ownerDate:(id)date ownerTimeZone:(id)zone fireDate:(id)date5 externalID:(id)anId6 acknowledgedDate:(id)date7;
-(id)initWithAlarmID:(id)alarmID ownerID:(id)anId ownerDate:(id)date ownerTimeZone:(id)zone fireDate:(id)date5 externalID:(id)anId6 acknowledgedDate:(id)date7;
-(id)initWithCoder:(id)coder;
-(id)initWithDictionaryRepresentation:(id)dictionaryRepresentation;
// declared property getter: -(id)acknowledgedDate;
// declared property getter: -(id)alarmID;
-(void)dealloc;
-(id)dictionaryRepresentation;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(id)externalID;
// declared property getter: -(id)fireDate;
// declared property getter: -(id)ownerDate;
// declared property getter: -(id)ownerID;
// declared property getter: -(id)ownerTimeZone;
@end

