/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class EKObjectRelation, NSMutableDictionary, NSMutableSet, EKPersistentObject, NSString;

__attribute__((visibility("hidden")))
@interface EKObject : XXUnknownSuperclass {
@private
	NSMutableDictionary* _dirtyProperties;
	NSMutableDictionary* _cachedProperties;
	EKPersistentObject* _persistentObject;
	NSString* _propertyName;
	EKObjectRelation* _owningRelation;
	NSMutableDictionary* _relations;
	NSMutableSet* _weakRelations;
	unsigned long _flags;
}
@property(retain, nonatomic) NSMutableDictionary* cachedProperties;	// @synthesize=_cachedProperties
@property(retain, nonatomic) NSMutableDictionary* dirtyProperties;	// @synthesize=_dirtyProperties
@property(assign, nonatomic) unsigned long flags;	// @synthesize=_flags
@property(assign, nonatomic) EKObjectRelation* owningRelation;	// @synthesize=_owningRelation
@property(retain, nonatomic) EKPersistentObject* persistentObject;	// @synthesize=_persistentObject
@property(copy, nonatomic) NSString* propertyName;	// @synthesize=_propertyName
@property(retain, nonatomic) NSMutableDictionary* relations;	// @synthesize=_relations
@property(retain, nonatomic) NSMutableSet* weakRelations;	// @synthesize=_weakRelations
-(id)initWithPersistentObject:(id)persistentObject;
-(void)addWeakRelation:(id)relation;
-(BOOL)boolPropertyForKey:(id)key withPersistentFallback:(id)persistentFallback;
-(void)cachePropertyValue:(id)value forKey:(id)key;
// declared property getter: -(id)cachedProperties;
-(void)childRelationChanged:(id)changed;
-(void)clearPropertyValueForKey:(id)key;
-(id)committedValueForKey:(id)key;
-(void)dealloc;
-(void)deletePersistentObject;
-(void)didCommit;
// declared property getter: -(id)dirtyProperties;
-(id)eventStore;
-(BOOL)existsInStore;
// declared property getter: -(unsigned long)flags;
-(BOOL)hasChanges;
-(void)insertPersistentObjectIfNeeded;
-(int)intPropertyForKey:(id)key withPersistentFallback:(id)persistentFallback;
-(BOOL)isEqual:(id)equal;
-(BOOL)isNew;
-(BOOL)isPropertyDirty:(id)dirty;
-(id)lazyLoadRelationForKey:(id)key;
-(id)objectID;
-(id)owner;
// declared property getter: -(id)owningRelation;
// declared property getter: -(id)persistentObject;
-(id)persistentOrDirtyPropertyForKey:(id)key;
-(id)propertyForKey:(id)key withPersistentFallback:(id)persistentFallback;
// declared property getter: -(id)propertyName;
-(id)propertyValueForKey:(id)key;
-(BOOL)propertyValueForKey:(id)key value:(id*)value;
-(BOOL)rebase;
-(BOOL)refresh;
-(id)relationForKey:(id)key;
// declared property getter: -(id)relations;
-(void)removeWeakRelation:(id)relation;
-(void)reset;
-(void)rollback;
// declared property setter: -(void)setCachedProperties:(id)properties;
// declared property setter: -(void)setDirtyProperties:(id)properties;
// declared property setter: -(void)setFlags:(unsigned long)flags;
// declared property setter: -(void)setOwningRelation:(id)relation;
// declared property setter: -(void)setPersistentObject:(id)object;
// declared property setter: -(void)setPropertyName:(id)name;
-(void)setPropertyValue:(id)value forKey:(id)key;
// declared property setter: -(void)setRelations:(id)relations;
// declared property setter: -(void)setWeakRelations:(id)relations;
-(void)updatePersistentObject;
-(void)updatePersistentValueForKeyIfNeeded:(id)keyIfNeeded;
-(BOOL)validate:(id*)validate;
// declared property getter: -(id)weakRelations;
@end

