/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import "CIFilter.h"
#import "CoreImage-Structs.h"

@class NSValue, CIImage;

__attribute__((visibility("hidden")))
@interface CIAffineTile : CIFilter {
@private
	CIImage* inputImage;
	NSValue* inputTransform;
}
@property(retain, nonatomic) CIImage* inputImage;	// @synthesize
@property(copy, nonatomic) NSValue* inputTransform;	// @synthesize
+(id)customAttributes;
// declared property getter: -(id)inputImage;
// declared property getter: -(id)inputTransform;
-(id)outputImage;
// declared property setter: -(void)setInputImage:(id)image;
// declared property setter: -(void)setInputTransform:(id)transform;
@end

