/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface CIDetector : XXUnknownSuperclass {
}
+(id)detectorOfType:(id)type context:(id)context options:(id)options;
-(id)init;
-(id)featuresInImage:(id)image;
-(id)featuresInImage:(id)image options:(id)options;
@end

