/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ABChameleonCellBackgroundView : XXUnknownSuperclass {
	int _abCellStyle;
	int _sectionLocation;
}
@property(assign, nonatomic) int abCellStyle;	// @synthesize=_abCellStyle
@property(assign, nonatomic) int sectionLocation;	// @synthesize=_sectionLocation
// declared property getter: -(int)abCellStyle;
// declared property getter: -(int)sectionLocation;
// declared property setter: -(void)setAbCellStyle:(int)style;
// declared property setter: -(void)setSectionLocation:(int)location;
@end

