/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "ABGroupWrapper.h"


@interface ABGlobalGroupWrapper : ABGroupWrapper {
}
+(id)newGlobalGroupWrapperWithAddressBook:(void*)addressBook;
-(BOOL)isEqual:(id)equal;
-(BOOL)isGlobalWrapper;
-(id)name;
@end

