/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AVFoundation-Structs.h"

@class NSMutableArray, NSDictionary;

@interface AVCaptureStillImageOutputInternal : XXUnknownSuperclass {
	NSMutableArray* stillImageRequests;
	CGSize previewImageSize;
	unsigned long imageDataFormatType;
	long long imageMaxDataSize;
	BOOL HDRCaptureEnabled;
	BOOL EV0CaptureEnabled;
	BOOL chromaNoiseReductionEnabled;
	BOOL suspendsVideoProcessingDuringCapture;
	NSDictionary* outputSettings;
	BOOL isCapturingPhoto;
}
-(id)init;
-(void)dealloc;
@end

