/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "NSCopying.h"
#import "AVFoundation-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, AVMediaSelectionGroupInternal;

@interface AVMediaSelectionGroup : XXUnknownSuperclass <NSCopying> {
	AVMediaSelectionGroupInternal* _mediaSelectionGroup;
}
@property(readonly, assign, nonatomic) BOOL allowsEmptySelection;
@property(readonly, assign, nonatomic) NSArray* options;
+(id)mediaSelectionGroupWithAsset:(id)asset alternateTrackIDs:(id)ids;
+(id)mediaSelectionGroupWithAsset:(id)asset dictionary:(id)dictionary;
+(id)mediaSelectionGroupWithAsset:(id)asset trackID:(int)anId;
+(id)mediaSelectionOptionsFromArray:(id)array withLocale:(id)locale;
+(id)mediaSelectionOptionsFromArray:(id)array withMediaCharacteristics:(id)mediaCharacteristics;
+(id)mediaSelectionOptionsFromArray:(id)array withoutMediaCharacteristics:(id)characteristics;
+(id)playableMediaSelectionOptionsFromArray:(id)array;
-(id)init;
-(BOOL)_isAlternateTrackGroup;
-(BOOL)_isKeyValueGroup;
-(id)_weakReference;
// declared property getter: -(BOOL)allowsEmptySelection;
-(id)asset;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)description;
-(void)finalize;
-(id)mediaSelectionOptionWithPropertyList:(id)propertyList;
// declared property getter: -(id)options;
@end

