/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVAudioMix.h"

@class NSArray, AVMutableAudioMixInternal;

@interface AVMutableAudioMix : AVAudioMix {
@private
	AVMutableAudioMixInternal* _mutableAudioMix;
}
@property(copy, nonatomic) NSArray* inputParameters;
+(id)audioMix;
// declared property getter: -(id)inputParameters;
// declared property setter: -(void)setInputParameters:(id)parameters;
@end

