/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import "AVAssetInspector.h"

@class NSArray;

@interface AVPlaybackItemInspector : AVAssetInspector {
	OpaqueFigPlaybackItem* _playbackItem;
	NSArray* _trackIDs;
}
@property(retain, nonatomic, getter=_playbackItem, setter=_setPlaybackItem:) OpaqueFigPlaybackItem* playbackItem;
-(id)initWithPlaybackItem:(OpaqueFigPlaybackItem*)playbackItem trackIDs:(id)ids;
// declared property getter: -(OpaqueFigPlaybackItem*)_playbackItem;
// declared property setter: -(void)_setPlaybackItem:(OpaqueFigPlaybackItem*)item;
-(void*)_valueAsCFTypeForProperty:(CFStringRef)property;
-(id)availableMetadataFormats;
-(id)commonMetadata;
-(id)compatibleTrackForCompositionTrack:(id)compositionTrack;
-(void)dealloc;
-(XXStruct_pwHToB)duration;
-(void)finalize;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)lyrics;
-(id)metadataForFormat:(id)format;
-(CGSize)naturalSize;
-(BOOL)providesPreciseDurationAndTiming;
-(long)trackCount;
-(id)trackIDs;
@end

