/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSMutableArray, CAPackage;

@interface _UICAPackageView : UIView {
@private
	CAPackage* _package;
	NSMutableArray* _rootViews;
}
-(id)initWithContentsOfURL:(id)url publishedObjectViewClassMap:(id)map;
-(id)initWithData:(id)data publishedObjectViewClassMap:(id)map;
-(void)dealloc;
-(id)publishedObjectWithName:(id)name;
-(id)publishedViewWithName:(id)name;
@end

