/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIView.h"
#import "UIKit-Structs.h"

@class UIPickerView;

__attribute__((visibility("hidden")))
@interface _UIPickerWheelView : UIView {
@private
	UIPickerView* _pickerView;
}
-(id)initWithFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(void)setPickerView:(id)view;
@end

