/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSTimer, NSMutableArray;

__attribute__((visibility("hidden")))
@interface _UIViewServiceFencingController : XXUnknownSuperclass {
@private
	int _lock;
	NSMutableSet* _pendingFenceSendRights;
	NSMutableArray* _resumeActions;
	unsigned _expectedParticipatingFencingProxyCount;
	NSTimer* _fencingControlTimeoutTimer;
}
-(id)init;
-(void)_fencingControlTimedOut;
-(void)dealloc;
-(void)fencingControlProxy:(id)proxy didBeginFencingWithSendRight:(id)sendRight expectedParticipatingFencingProxyCount:(unsigned)count;
-(void)fencingControlProxy:(id)proxy didEndFencingWithSendRight:(id)sendRight;
@end

