/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSURL;

__attribute__((visibility("hidden")))
@interface UIActivityItemURLRep : XXUnknownSuperclass {
@private
	NSURL* _URL;
	UIImage* _thumbnail;
}
@property(retain, nonatomic) NSURL* URL;	// @synthesize=_URL
@property(retain, nonatomic) UIImage* thumbnail;	// @synthesize=_thumbnail
// declared property getter: -(id)URL;
-(void)dealloc;
// declared property setter: -(void)setThumbnail:(id)thumbnail;
// declared property setter: -(void)setURL:(id)url;
// declared property getter: -(id)thumbnail;
@end

