/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UIViewController.h"

@class UICollectionView, UICollectionViewLayout;

@interface UICollectionViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource> {
@private
	UICollectionViewLayout* _layout;
	UICollectionView* _collectionView;
	struct {
		unsigned hasAutomaticAnimationItems : 1;
	} _collectionViewControllerFlags;
}
@property(assign, nonatomic) BOOL clearsSelectionOnViewWillAppear;
@property(retain, nonatomic) UICollectionView* collectionView;
-(id)initWithCoder:(id)coder;
-(id)initWithCollectionViewLayout:(id)collectionViewLayout;
-(id)_newCollectionViewWithFrame:(CGRect)frame collectionViewLayout:(id)layout;
-(id)_wrappingView;
// declared property getter: -(BOOL)clearsSelectionOnViewWillAppear;
// declared property getter: -(id)collectionView;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)loadView;
// declared property setter: -(void)setClearsSelectionOnViewWillAppear:(BOOL)appear;
// declared property setter: -(void)setCollectionView:(id)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillUnload;
@end

