/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKeyboardCandidateListDelegate.h"
#import "UIKeyboardCandidateList.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIKit-Structs.h"

@class NSString, UIKeyboardCandidateView, UIView, NSArray;
@protocol UIKeyboardCandidateViewInline;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateInline : XXUnknownSuperclass <UIKeyboardCandidateList, UIKeyboardCandidateListDelegate> {
@private
	NSArray* m_candidates;
	NSString* m_inlineText;
	CGRect m_inlineRect;
	UIView<UIKeyboardCandidateList>* m_inlineView;
	UIKeyboardCandidateView<UIKeyboardCandidateViewInline>* m_extendedView;
	struct {
		unsigned isExtended;
	} _inlineFlags;
	int _promptTextType;
	id<UIKeyboardCandidateListDelegate> _candidateListDelegate;
}
@property(assign, nonatomic) id<UIKeyboardCandidateListDelegate> candidateListDelegate;	// @synthesize=_candidateListDelegate
@property(retain, nonatomic) NSArray* candidates;	// @synthesize=m_candidates
@property(assign, nonatomic) CGRect inlineRect;	// @synthesize=m_inlineRect
@property(retain, nonatomic) NSString* inlineText;	// @synthesize=m_inlineText
@property(assign, nonatomic) int promptTextType;	// @synthesize=_promptTextType
+(unsigned)numberofColumnsForFloatingView;
+(id)sharedInstance;
-(id)init;
-(id)_inlineView;
-(id)activeCandidateList;
-(void)animateInlineCandidate;
-(void)candidateAcceptedAtIndex:(unsigned)index;
-(id)candidateAtIndex:(unsigned)index;
-(void)candidateListAcceptCandidate:(id)candidate;
// declared property getter: -(id)candidateListDelegate;
-(void)candidateListSelectionDidChange:(id)candidateListSelection;
-(void)candidateListShouldBeDismissed:(id)candidateList;
// declared property getter: -(id)candidates;
-(void)candidatesDidChange;
-(void)configureKeyboard:(id)keyboard;
-(unsigned)count;
-(id)currentCandidate;
-(unsigned)currentIndex;
-(void)dealloc;
// declared property getter: -(CGRect)inlineRect;
// declared property getter: -(id)inlineText;
-(void)layout;
-(BOOL)needsWebDocumentViewEventsDirectly;
// declared property getter: -(int)promptTextType;
// declared property setter: -(void)setCandidateListDelegate:(id)delegate;
// declared property setter: -(void)setCandidates:(id)candidates;
-(void)setCandidates:(id)candidates inlineText:(id)text inlineRect:(CGRect)rect maxX:(float)x layout:(BOOL)layout;
-(void)setCandidates:(id)candidates type:(int)type inlineText:(id)text inlineRect:(CGRect)rect maxX:(float)x layout:(BOOL)layout;
-(void)setCompletionContext:(id)context;
// declared property setter: -(void)setInlineRect:(CGRect)rect;
// declared property setter: -(void)setInlineText:(id)text;
-(void)setInlineViewExtended:(BOOL)extended;
// declared property setter: -(void)setPromptTextType:(int)type;
-(void)setUIKeyboardCandidateListDelegate:(id)delegate;
-(void)showCandidate:(id)candidate;
-(void)showCandidateAtIndex:(unsigned)index;
-(void)showNextCandidate;
-(void)showNextPage;
-(void)showPageAtIndex:(unsigned)index;
-(void)showPreviousCandidate;
-(void)showPreviousPage;
@end

