/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class UIKeyboardCandidate, NSString, UIFont;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateGridCell : UIView {
@private
	UIKeyboardCandidate* _candidate;
	NSString* _text;
	NSString* _alternativeText;
	int _textAlignment;
	unsigned _candidateNumber;
	BOOL _showsCandidateNumber;
	CGSize _size;
	UIFont* _font;
	float _fontSize;
	CGSize _textSize;
	UIFont* _alternativeTextFont;
	float _alternativeTextFontSize;
	CGSize _alternativeTextSize;
	CGSize _candidateNumberSize;
	float _cellPadding;
	float _minimumWidth;
	BOOL _highlighted;
	BOOL _onTopEdge;
	BOOL _onLeftEdge;
	BOOL _onRightEdge;
	CGRect _visibleBounds;
	BOOL _usesGroupHeaderAppearance;
	float _rowHeight;
	id _target;
	SEL _action;
	int _visualStyle;
	BOOL _placeholderCell;
	float _rightPadding;
}
@property(assign, nonatomic) SEL action;	// @synthesize=_action
@property(copy, nonatomic) NSString* alternativeText;	// @synthesize=_alternativeText
@property(retain, nonatomic) UIFont* alternativeTextFont;	// @synthesize=_alternativeTextFont
@property(assign, nonatomic) float alternativeTextFontSize;	// @synthesize=_alternativeTextFontSize
@property(assign, nonatomic) CGSize alternativeTextSize;	// @synthesize=_alternativeTextSize
@property(readonly, assign, nonatomic) BOOL canShowCandidateNumber;
@property(copy, nonatomic) UIKeyboardCandidate* candidate;	// @synthesize=_candidate
@property(assign, nonatomic) unsigned candidateNumber;	// @synthesize=_candidateNumber
@property(assign, nonatomic) CGSize candidateNumberSize;	// @synthesize=_candidateNumberSize
@property(assign, nonatomic) float cellPadding;	// @synthesize=_cellPadding
@property(retain, nonatomic) UIFont* font;	// @synthesize=_font
@property(assign, nonatomic) float fontSize;	// @synthesize=_fontSize
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;	// @synthesize=_highlighted
@property(assign, nonatomic) float minimumWidth;	// @synthesize=_minimumWidth
@property(assign, nonatomic) BOOL onLeftEdge;	// @synthesize=_onLeftEdge
@property(assign, nonatomic) BOOL onRightEdge;	// @synthesize=_onRightEdge
@property(assign, nonatomic) BOOL onTopEdge;	// @synthesize=_onTopEdge
@property(assign, nonatomic) BOOL placeholderCell;	// @synthesize=_placeholderCell
@property(assign, nonatomic) float rightPadding;	// @synthesize=_rightPadding
@property(assign, nonatomic) float rowHeight;	// @synthesize=_rowHeight
@property(assign, nonatomic) BOOL showsCandidateNumber;	// @synthesize=_showsCandidateNumber
@property(assign, nonatomic) CGSize size;	// @synthesize=_size
@property(assign, nonatomic) id target;	// @synthesize=_target
@property(copy, nonatomic) NSString* text;	// @synthesize=_text
@property(assign, nonatomic) int textAlignment;	// @synthesize=_textAlignment
@property(assign, nonatomic) CGSize textSize;	// @synthesize=_textSize
@property(assign, nonatomic) BOOL usesGroupHeaderAppearance;	// @synthesize=_usesGroupHeaderAppearance
@property(assign, nonatomic) CGRect visibleBounds;	// @synthesize=_visibleBounds
@property(assign, nonatomic) int visualStyle;	// @synthesize=_visualStyle
+(id)cellWithCandidate:(id)candidate visualStyle:(int)style;
+(id)groupHeaderCellWithTitle:(id)title visualStyle:(int)style;
+(id)placeholderCellWithVisualStyle:(int)visualStyle;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame candidate:(id)candidate text:(id)text alternativeText:(id)text4 groupHeader:(BOOL)header visualStyle:(int)style;
-(CGSize)_sizeForText:(id)text withSize:(float)size font:(id)font;
// declared property getter: -(SEL)action;
-(void)adjustFontForFrame:(CGRect)frame;
// declared property getter: -(id)alternativeText;
// declared property getter: -(id)alternativeTextFont;
// declared property getter: -(float)alternativeTextFontSize;
// declared property getter: -(CGSize)alternativeTextSize;
-(void)calculateCandidateNumberSize;
-(void)calculateSize;
-(void)calculateTextSize;
// declared property getter: -(BOOL)canShowCandidateNumber;
// declared property getter: -(id)candidate;
// declared property getter: -(unsigned)candidateNumber;
// declared property getter: -(CGSize)candidateNumberSize;
// declared property getter: -(float)cellPadding;
-(void)dealloc;
-(void)drawBackgroundAndBorders;
-(void)drawRect:(CGRect)rect;
-(void)drawText;
-(void)drawTextWithCandidateNumber;
// declared property getter: -(id)font;
// declared property getter: -(float)fontSize;
// declared property getter: -(BOOL)isHighlighted;
// declared property getter: -(float)minimumWidth;
// declared property getter: -(BOOL)onLeftEdge;
// declared property getter: -(BOOL)onRightEdge;
// declared property getter: -(BOOL)onTopEdge;
// declared property getter: -(BOOL)placeholderCell;
// declared property getter: -(float)rightPadding;
// declared property getter: -(float)rowHeight;
// declared property setter: -(void)setAction:(SEL)action;
// declared property setter: -(void)setAlternativeText:(id)text;
// declared property setter: -(void)setAlternativeTextFont:(id)font;
// declared property setter: -(void)setAlternativeTextFontSize:(float)size;
// declared property setter: -(void)setAlternativeTextSize:(CGSize)size;
// declared property setter: -(void)setCandidate:(id)candidate;
// declared property setter: -(void)setCandidateNumber:(unsigned)number;
// declared property setter: -(void)setCandidateNumberSize:(CGSize)size;
// declared property setter: -(void)setCellPadding:(float)padding;
// declared property setter: -(void)setFont:(id)font;
// declared property setter: -(void)setFontSize:(float)size;
// declared property setter: -(void)setHighlighted:(BOOL)highlighted;
// declared property setter: -(void)setMinimumWidth:(float)width;
// declared property setter: -(void)setOnLeftEdge:(BOOL)edge;
// declared property setter: -(void)setOnRightEdge:(BOOL)edge;
// declared property setter: -(void)setOnTopEdge:(BOOL)edge;
// declared property setter: -(void)setPlaceholderCell:(BOOL)cell;
// declared property setter: -(void)setRightPadding:(float)padding;
// declared property setter: -(void)setRowHeight:(float)height;
// declared property setter: -(void)setShowsCandidateNumber:(BOOL)number;
// declared property setter: -(void)setSize:(CGSize)size;
// declared property setter: -(void)setTarget:(id)target;
// declared property setter: -(void)setText:(id)text;
// declared property setter: -(void)setTextAlignment:(int)alignment;
// declared property setter: -(void)setTextSize:(CGSize)size;
// declared property setter: -(void)setUsesGroupHeaderAppearance:(BOOL)appearance;
// declared property setter: -(void)setVisibleBounds:(CGRect)bounds;
// declared property setter: -(void)setVisualStyle:(int)style;
// declared property getter: -(BOOL)showsCandidateNumber;
// declared property getter: -(CGSize)size;
// declared property getter: -(id)target;
// declared property getter: -(id)text;
// declared property getter: -(int)textAlignment;
// declared property getter: -(CGSize)textSize;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
// declared property getter: -(BOOL)usesGroupHeaderAppearance;
// declared property getter: -(CGRect)visibleBounds;
// declared property getter: -(int)visualStyle;
@end

