/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"

@class NSAttributedString, UIScrollView, UIColor, _UIRefreshControlContentView;

@interface UIRefreshControl : UIControl {
@private
	int _style;
	_UIRefreshControlContentView* _contentView;
	UIScrollView* _scrollView;
	float _refreshControlHeight;
	float _visibleHeight;
	float _snappingHeight;
	BOOL _insetsApplied;
	BOOL _adjustingInsets;
	UIEdgeInsets _appliedInsets;
	int _refreshControlState;
}
@property(readonly, assign, nonatomic, getter=_isApplyingInsets) BOOL _applyingInsets;
@property(readonly, assign, nonatomic) float _refreshControlHeight;
@property(readonly, assign, nonatomic) float _snappingHeight;
@property(readonly, assign, nonatomic) float _visibleHeight;
@property(readonly, assign, nonatomic, getter=_appliedInsets) UIEdgeInsets appliedInsets;
@property(retain, nonatomic) NSAttributedString* attributedTitle;
@property(readonly, assign, nonatomic) int refreshControlState;	// @synthesize=_refreshControlState
@property(readonly, assign, nonatomic, getter=isRefreshing) BOOL refreshing;
@property(readonly, assign, nonatomic) int style;
@property(retain, nonatomic) UIColor* tintColor;
+(Class)_contentViewClassForStyle:(int)style;
+(id)_defaultColor;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithStyle:(int)style;
-(void)_addInsetHeight:(float)height;
-(void)_addInsets;
// declared property getter: -(UIEdgeInsets)_appliedInsets;
-(id)_attributedTitle;
-(BOOL)_canTransitionFromState:(int)state toState:(int)state2;
-(id)_contentView;
-(void)_didScroll;
// declared property getter: -(BOOL)_isApplyingInsets;
-(CGPoint)_originForContentOffset:(CGPoint)contentOffset;
-(void)_populateArchivedSubviews:(id)subviews;
-(int)_recomputeNewState;
// declared property getter: -(float)_refreshControlHeight;
-(void)_removeInsetHeight:(float)height;
-(void)_removeInsets;
-(void)_resizeToFitContents;
-(void)_setAttributedTitle:(id)title;
-(void)_setRefreshControlState:(int)state notify:(BOOL)notify;
-(void)_setTintColor:(id)color;
-(void)_setVisibleHeight:(float)height;
// declared property getter: -(float)_snappingHeight;
-(id)_tintColor;
-(void)_update;
-(void)_updateSnappingHeight;
// declared property getter: -(float)_visibleHeight;
-(float)_visibleHeightForContentOffset:(CGPoint)contentOffset origin:(CGPoint)origin;
// declared property getter: -(id)attributedTitle;
-(void)beginRefreshing;
-(void)dealloc;
-(void)didMoveToSuperview;
-(void)encodeWithCoder:(id)coder;
-(void)endRefreshing;
// declared property getter: -(BOOL)isRefreshing;
// declared property getter: -(int)refreshControlState;
-(float)revealedFraction;
// declared property setter: -(void)setAttributedTitle:(id)title;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)setRefreshControlState:(int)state;
// declared property setter: -(void)setTintColor:(id)color;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)sizeToFit;
// declared property getter: -(int)style;
// declared property getter: -(id)tintColor;
-(void)willMoveToSuperview:(id)superview;
@end

