/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIActivity.h"

@class SLComposeViewController;

@interface UISocialActivity : UIActivity {
@private
	SLComposeViewController* _socialComposeViewController;
}
@property(retain, nonatomic) SLComposeViewController* socialComposeViewController;	// @synthesize=_socialComposeViewController
-(id)_activityImage;
-(void)_cleanup;
-(int)_maxImageDataSize;
-(id)_serviceType;
-(id)activityTitle;
-(id)activityType;
-(id)activityViewController;
-(BOOL)canPerformWithActivityItems:(id)activityItems;
-(void)dealloc;
-(void)prepareWithActivityItems:(id)activityItems;
// declared property setter: -(void)setSocialComposeViewController:(id)controller;
// declared property getter: -(id)socialComposeViewController;
@end

