/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;

__attribute__((visibility("hidden")))
@interface UIStoryboardScene : XXUnknownSuperclass {
@private
	UIViewController* sceneViewController;
}
@property(retain, nonatomic) UIViewController* sceneViewController;	// @synthesize
-(void)dealloc;
// declared property getter: -(id)sceneViewController;
// declared property setter: -(void)setSceneViewController:(id)controller;
@end

