/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MKUserLocationViewInternal;

__attribute__((visibility("hidden")))
@interface MKHoverAnimation : XXUnknownSuperclass {
	MKUserLocationViewInternal* viewImpl;
}
@property(assign) float restAccuracy;	// @dynamic
@property(assign, nonatomic) MKUserLocationViewInternal* viewImpl;	// @synthesize
+(id)bounceAnimation;
+(id)defaultValueForKey:(id)key;
+(id)fallAnimation;
+(id)hoverAnimation;
-(id)init;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)dealloc;
-(void)drawAccuracyLayer:(float)layer;
-(void)runActionForKey:(id)key object:(id)object arguments:(id)arguments;
-(void)setInitialAccuracy:(float)accuracy restAccuracy:(float)accuracy2 drawAccuracy:(float)accuracy3;
// declared property setter: -(void)setViewImpl:(id)impl;
// declared property getter: -(id)viewImpl;
@end

