/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import "MKPolylineView.h"


__attribute__((visibility("hidden")))
@interface MKShinyRouteOverlayView : MKPolylineView {
	id _activeStep;
}
+(BOOL)_useMiniTiledLayer;
-(id)initWithRouteGroup:(id)routeGroup;
-(void)_displayInMapRect:(XXStruct_Yvvv9D)mapRect zoomScale:(float)scale;
-(void)_drawRouteAtIndex:(unsigned)index mapRect:(XXStruct_Yvvv9D)rect zoomScale:(float)scale inContext:(CGContextRef)context;
-(void)_forceRedisplay;
-(BOOL)canDrawMapRect:(XXStruct_Yvvv9D)rect zoomScale:(float)scale;
-(void)drawMapRect:(XXStruct_Yvvv9D)rect zoomScale:(float)scale inContext:(CGContextRef)context;
-(void)set_levelCrossFade:(BOOL)fade;
@end

