/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GameKit-Structs.h"
#import "GKMultilineCellContentView.h"

@class UIImage;

@interface GKAchievementCellContent : GKMultilineCellContentView {
	BOOL _highlighted;
	BOOL _offsetImage;
@private
	UIImage* _highlightedImage;
	BOOL _largeIcons;
}
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;	// @synthesize=_highlighted
@property(retain, nonatomic) UIImage* highlightedImage;	// @synthesize=_highlightedImage
@property(readonly, assign, nonatomic) BOOL largeIcons;	// @synthesize=_largeIcons
@property(assign, nonatomic) BOOL offsetImage;	// @synthesize=_offsetImage
-(id)initWithLargeIcons:(BOOL)largeIcons;
-(UIEdgeInsets)_gkPopoverPresentationInsets;
-(CGRect)_gkPopoverPresentationRect;
-(void)adjustLineRects:(CGRect*)rects forLines:(id)lines inTextRect:(CGRect)textRect;
-(void)dealloc;
-(void)drawLineIndex:(unsigned)index inRect:(CGRect*)rect highlighted:(BOOL)highlighted;
// declared property getter: -(id)highlightedImage;
-(id)image;
// declared property getter: -(BOOL)isHighlighted;
// declared property getter: -(BOOL)largeIcons;
// declared property getter: -(BOOL)offsetImage;
// declared property setter: -(void)setHighlighted:(BOOL)highlighted;
// declared property setter: -(void)setHighlightedImage:(id)image;
// declared property setter: -(void)setOffsetImage:(BOOL)image;
-(void)setTheme:(id)theme;
@end

