/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKViewController.h"

@class GKRemoteViewController, GKGame;

@interface GKHostedViewController : GKViewController {
@private
	GKGame* _game;
	GKRemoteViewController* _remoteViewController;
	BOOL _presentingRemoteViewController;
	BOOL _shouldPresentRemoteViewController;
	id _remoteViewReadyHandler;
	BOOL _isRequestingRemoteViewController;
	BOOL _gkIsDisappearing;
}
@property(retain, nonatomic) GKGame* game;	// @synthesize=_game
@property(assign, nonatomic) BOOL gkIsDisappearing;	// @synthesize=_gkIsDisappearing
@property(assign, nonatomic) BOOL isRequestingRemoteViewController;	// @synthesize=_isRequestingRemoteViewController
@property(assign, nonatomic) BOOL presentingRemoteViewController;	// @synthesize=_presentingRemoteViewController
@property(retain, nonatomic) GKRemoteViewController* remoteViewController;	// @synthesize=_remoteViewController
@property(copy, nonatomic) id remoteViewReadyHandler;	// @synthesize=_remoteViewReadyHandler
@property(assign, nonatomic) BOOL shouldPresentRemoteViewController;	// @synthesize=_shouldPresentRemoteViewController
-(id)init;
-(id)_presentingViewController;
-(BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
-(void)dealloc;
-(void)didGetRemoteViewController;
-(void)didReceiveMemoryWarning;
-(void)dismissModalViewControllerAnimated:(BOOL)animated;
-(void)dismissViewControllerAnimated:(BOOL)animated completion:(id)completion;
-(void)donePressed:(id)pressed;
// declared property getter: -(id)game;
// declared property getter: -(BOOL)gkIsDisappearing;
-(id)hostSideViewControllerClassName;
// declared property getter: -(BOOL)isRequestingRemoteViewController;
-(void)presentRemoteViewControllerIfNeeded;
// declared property getter: -(BOOL)presentingRemoteViewController;
// declared property getter: -(id)remoteViewController;
// declared property getter: -(id)remoteViewReadyHandler;
-(void)requestRemoteViewControllerIfNeeded;
-(void)resetRemoteViewController;
-(id)serviceSideViewControllerClassName;
// declared property setter: -(void)setGame:(id)game;
// declared property setter: -(void)setGkIsDisappearing:(BOOL)disappearing;
// declared property setter: -(void)setIsRequestingRemoteViewController:(BOOL)controller;
// declared property setter: -(void)setPresentingRemoteViewController:(BOOL)controller;
// declared property setter: -(void)setRemoteViewController:(id)controller;
// declared property setter: -(void)setRemoteViewReadyHandler:(id)handler;
// declared property setter: -(void)setShouldPresentRemoteViewController:(BOOL)presentRemoteViewController;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
// declared property getter: -(BOOL)shouldPresentRemoteViewController;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
@end

