/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKPlayer.h"

@class NSDictionary, GKInvite, NSInvocation, NSArray, GKAuthenticateViewController, UIViewController, NSString, NSSet, UIAlertView, NSDate;

@interface GKLocalPlayer : GKPlayer {
@private
	BOOL _authenticated;
	BOOL _authenticating;
	id _authenticateHandler;
	GKInvite* _acceptedInvite;
	id _authenticationCompletionHandler;
	id _validateAccountCompletionHandler;
	UIAlertView* _loginAlertView;
	UIAlertView* _currentAlert;
	NSString* _lastUsernameAttempted;
	NSInvocation* _currentFriendRequestInvocation;
	BOOL _didAuthenticate;
	BOOL _validatingAccount;
	BOOL _enteringForeground;
	unsigned _failedLogins;
	NSSet* _friendTestSet;
	NSArray* _friendRequests;
	NSDictionary* _authenticateAlertDictionary;
	UIViewController* _rootViewController;
	UIViewController* _activeViewController;
	GKAuthenticateViewController* _authViewController;
	NSString* _lastAuthPlayerID;
	NSDate* _lastAuthDate;
	BOOL _newToGameCenter;
}
@property(retain, nonatomic) GKInvite* acceptedInvite;	// @synthesize=_acceptedInvite
@property(retain, nonatomic) NSString* accountName;	// @dynamic
@property(retain, nonatomic) UIViewController* activeViewController;	// @synthesize=_activeViewController
@property(assign, nonatomic) BOOL allowMultiplayerInvites;	// @dynamic
@property(retain, nonatomic) GKAuthenticateViewController* authViewController;	// @synthesize=_authViewController
@property(retain, nonatomic) NSDictionary* authenticateAlertDictionary;	// @synthesize=_authenticateAlertDictionary
@property(copy, nonatomic) id authenticateHandler;	// @synthesize=_authenticateHandler
@property(readonly, assign, nonatomic, getter=isAuthenticated) BOOL authenticated;	// @synthesize=_authenticated
@property(assign, nonatomic, getter=isAuthenticating) BOOL authenticating;	// @synthesize=_authenticating
@property(copy, nonatomic) id authenticationCompletionHandler;	// @synthesize=_authenticationCompletionHandler
@property(readonly, assign, nonatomic) BOOL canChangePhoto;	// @dynamic
@property(assign, nonatomic) UIAlertView* currentAlert;	// @synthesize=_currentAlert
@property(retain, nonatomic) NSInvocation* currentFriendRequestInvocation;	// @synthesize=_currentFriendRequestInvocation
@property(assign, nonatomic) BOOL didAuthenticate;	// @synthesize=_didAuthenticate
@property(assign, nonatomic) BOOL enteringForeground;	// @synthesize=_enteringForeground
@property(assign, nonatomic) unsigned failedLogins;	// @synthesize=_failedLogins
@property(readonly, assign, nonatomic, getter=isFindable) BOOL findable;	// @dynamic
@property(retain, nonatomic) NSString* firstName;	// @dynamic
@property(retain, nonatomic) NSArray* friendRequests;	// @synthesize=_friendRequests
@property(retain, nonatomic) NSSet* friendTestSet;	// @synthesize=_friendTestSet
@property(readonly, assign, nonatomic) NSArray* friends;
@property(retain, nonatomic) NSDate* lastAuthDate;	// @synthesize=_lastAuthDate
@property(retain, nonatomic) NSString* lastAuthPlayerID;	// @synthesize=_lastAuthPlayerID
@property(retain, nonatomic) NSString* lastName;	// @dynamic
@property(retain, nonatomic) NSString* lastUsernameAttempted;	// @synthesize=_lastUsernameAttempted
@property(retain, nonatomic) UIAlertView* loginAlertView;	// @synthesize=_loginAlertView
@property(assign, nonatomic, getter=isNewToGameCenter) BOOL newToGameCenter;	// @synthesize=_newToGameCenter
@property(assign, nonatomic, getter=isPurpleBuddyAccount) BOOL purpleBuddyAccount;	// @dynamic
@property(retain, nonatomic) UIViewController* rootViewController;	// @synthesize=_rootViewController
@property(readonly, assign, nonatomic, getter=isUnderage) BOOL underage;	// @dynamic
@property(copy, nonatomic) id validateAccountCompletionHandler;	// @synthesize=_validateAccountCompletionHandler
@property(assign, nonatomic) BOOL validatingAccount;	// @synthesize=_validatingAccount
+(id)accountName;
+(BOOL)hasAuthenticatedAccount;
+(id)localPlayer;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)_authenticate;
-(void)_authenticateWithCompletionHandler:(id)completionHandler;
-(void)_showWelcomeBanner;
// declared property getter: -(id)acceptedInvite;
-(void)accountViewControllerForMode:(int)mode completionHandler:(id)handler;
-(void)accountViewControllerForMode:(int)mode email:(id)email completionHandler:(id)handler;
// declared property getter: -(id)activeViewController;
-(void)addEmail:(id)email withCompletionHandler:(id)completionHandler;
-(void)addFriendRequest:(id)request;
-(void)addPlayerAsFriend:(id)aFriend;
-(void)addPlayerIDAsFriend:(id)aFriend;
-(void)alertAndSendFriendRequest:(id)request destination:(id)destination;
-(BOOL)alertUserInStoreDemoModeEnabled;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)applicationWillEnterForeground:(id)application;
-(id)attributedDisplayNameWithIdentifiableName:(BOOL)identifiableName withFont:(id)font;
// declared property getter: -(id)authViewController;
-(void)authenticate;
// declared property getter: -(id)authenticateAlertDictionary;
// declared property getter: -(id)authenticateHandler;
-(void)authenticateWithCompletionHandler:(id)completionHandler;
// declared property getter: -(id)authenticationCompletionHandler;
-(void)callAuthHandlerWithError:(id)error;
// declared property getter: -(BOOL)canChangePhoto;
-(void)cancelAuthentication;
// declared property getter: -(id)currentAlert;
// declared property getter: -(id)currentFriendRequestInvocation;
-(void)daemonCancelledGameInvite:(id)invite;
-(void)daemonFetchGameInvite:(id)invite;
-(void)daemonFetchTurnBasedEvent:(id)event;
-(void)daemonInviteeRespondedToGameInvite:(id)gameInvite;
-(void)dealloc;
-(void)deletePhoto;
-(unsigned)detailPieces;
// declared property getter: -(BOOL)didAuthenticate;
-(id)displayNameWithIdentifiableName:(BOOL)identifiableName quoteAlias:(BOOL)alias;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(BOOL)enteringForeground;
// declared property getter: -(unsigned)failedLogins;
-(void)finishAuthenticationWithError:(id)error;
-(id)friendRequestForPlayerID:(id)playerID;
// declared property getter: -(id)friendRequests;
// declared property getter: -(id)friendTestSet;
// declared property getter: -(id)friends;
-(void)handleUnderlyingErrorForAuthenticateError:(id)authenticateError;
-(BOOL)hasEmailAddress:(id)address;
-(void)invalidatedCache:(id)cache;
// declared property getter: -(BOOL)isAuthenticated;
// declared property getter: -(BOOL)isAuthenticating;
-(BOOL)isFriend;
-(BOOL)isFriendOfPlayer:(id)player;
-(BOOL)isFriendOfPlayerWithID:(id)anId;
-(BOOL)isLocalPlayer;
// declared property getter: -(BOOL)isNewToGameCenter;
// declared property getter: -(id)lastAuthDate;
// declared property getter: -(id)lastAuthPlayerID;
// declared property getter: -(id)lastUsernameAttempted;
-(void)linkAccounts:(BOOL)accounts withAuthToken:(id)authToken forService:(unsigned)service mayAskAgainLater:(BOOL)later handler:(id)handler;
-(void)loadDefaultLeaderboardCategoryIDWithCompletionHandler:(id)completionHandler;
-(void)loadFriendRecommendationsWithCompletionHandler:(id)completionHandler;
-(void)loadFriendRequests:(id)requests;
-(void)loadFriendsWithCompletionHandler:(id)completionHandler;
-(void)loadGameRecommendationsWithCompletionHandler:(id)completionHandler;
-(void)loadProfilePieces:(unsigned)pieces withCompletionHandler:(id)completionHandler;
// declared property getter: -(id)loginAlertView;
-(void)removeActiveViewControllerAnimated:(BOOL)animated completionHandler:(id)handler;
-(void)removeFriend:(id)aFriend block:(id)block;
-(void)removeFriendRequestForPlayerID:(id)playerID;
-(void)reset:(id)reset;
// declared property getter: -(id)rootViewController;
-(void)sendFriendRequest:(id)request toAliases:(id)aliases players:(id)players emailAddresses:(id)addresses twitterScreenNames:(id)names facebookIDs:(id)ids rid:(id)rid block:(id)block;
// declared property setter: -(void)setAcceptedInvite:(id)invite;
// declared property setter: -(void)setActiveViewController:(id)controller;
// declared property setter: -(void)setAuthViewController:(id)controller;
// declared property setter: -(void)setAuthenticateAlertDictionary:(id)dictionary;
// declared property setter: -(void)setAuthenticateHandler:(id)handler;
-(void)setAuthenticated:(BOOL)authenticated oldPlayerID:(id)anId postNotification:(BOOL)notification;
-(void)setAuthenticated:(BOOL)authenticated oldPlayerID:(id)anId postNotification:(BOOL)notification postPlayerDidChangeNotification:(BOOL)postPlayer;
// declared property setter: -(void)setAuthenticating:(BOOL)authenticating;
// declared property setter: -(void)setAuthenticationCompletionHandler:(id)handler;
// declared property setter: -(void)setCurrentAlert:(id)alert;
// declared property setter: -(void)setCurrentFriendRequestInvocation:(id)invocation;
-(void)setDefaultLeaderboardCategoryID:(id)anId completionHandler:(id)handler;
// declared property setter: -(void)setDidAuthenticate:(BOOL)authenticate;
// declared property setter: -(void)setEnteringForeground:(BOOL)foreground;
// declared property setter: -(void)setFailedLogins:(unsigned)logins;
// declared property setter: -(void)setFriendRequests:(id)requests;
// declared property setter: -(void)setFriendTestSet:(id)set;
-(void)setFriends:(id)friends;
-(void)setInternal:(id)internal withFriends:(id)friends;
// declared property setter: -(void)setLastAuthDate:(id)date;
// declared property setter: -(void)setLastAuthPlayerID:(id)anId;
// declared property setter: -(void)setLastUsernameAttempted:(id)attempted;
// declared property setter: -(void)setLoginAlertView:(id)view;
// declared property setter: -(void)setNewToGameCenter:(BOOL)gameCenter;
-(void)setPhoto:(id)photo withCompletionHandler:(id)completionHandler;
// declared property setter: -(void)setRootViewController:(id)controller;
-(void)setStatus:(id)status;
-(void)setStatus:(id)status withCompletionHandler:(id)completionHandler;
// declared property setter: -(void)setValidateAccountCompletionHandler:(id)handler;
// declared property setter: -(void)setValidatingAccount:(BOOL)account;
-(void)shouldAskToLinkAccountsForService:(unsigned)service handler:(id)handler;
-(void)showAccountViewControllerForMode:(int)mode;
-(void)showAlertForTag:(unsigned)tag;
-(void)showAuthenticateForInGameNavController:(id)gameNavController popOnAuthenticate:(BOOL)authenticate completionHandler:(id)handler;
-(void)showAuthenticateViewController;
-(void)showAuthenticateViewControllerForGameCenter;
-(void)showAuthorizeViewController;
-(void)showChangePasswordViewController;
-(void)showCreateAccountRestrictedAlert;
-(void)showEditAccountRestrictedAlert;
-(void)showSignInAccountRestrictedAlert;
-(void)showViewController:(id)controller wrapInNavController:(BOOL)navController;
-(void)signOutWithCompletionHandler:(id)completionHandler;
-(void)updateFromLocalPlayer:(id)localPlayer;
-(void)updateLinkedAccountsForService:(unsigned)service withAuthToken:(id)authToken handler:(id)handler;
// declared property getter: -(id)validateAccountCompletionHandler;
-(void)validateAccountWithCompletionHandler:(id)completionHandler;
// declared property getter: -(BOOL)validatingAccount;
@end

