/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKResponse.h"

@class NSObject, NSDictionary, GKMatchRequestInternal, NSArray, NSString, NSData;
@protocol OS_dispatch_group;

@interface GKMatchResponse : GKResponse {
@private
	int _state;
	NSString* _rid;
	NSData* _sessionToken;
	NSDictionary* _serverRequest;
	int _sequence;
	NSArray* _matches;
	NSObject<OS_dispatch_group>* _matchingGroup;
	NSArray* _relayPushes;
	GKMatchRequestInternal* _matchRequest;
	NSData* _cdxTicket;
}
@property(retain, nonatomic) NSData* cdxTicket;	// @synthesize=_cdxTicket
@property(retain) GKMatchRequestInternal* matchRequest;	// @synthesize=_matchRequest
@property(retain, nonatomic) NSArray* matches;	// @synthesize=_matches
@property(assign) NSObject<OS_dispatch_group>* matchingGroup;	// @synthesize=_matchingGroup
@property(retain, nonatomic) NSArray* relayPushes;	// @synthesize=_relayPushes
@property(retain, nonatomic) NSString* rid;	// @synthesize=_rid
@property(readonly, assign) int sequence;	// @synthesize=_sequence
@property(retain) NSDictionary* serverRequest;	// @synthesize=_serverRequest
@property(retain, nonatomic) NSData* sessionToken;	// @synthesize=_sessionToken
@property(assign, nonatomic) int state;	// @synthesize=_state
+(id)codedPropertyKeys;
-(int)_incrementSequence;
// declared property getter: -(id)cdxTicket;
-(void)dealloc;
-(BOOL)isCancelled;
-(BOOL)isFinished;
// declared property getter: -(id)matchRequest;
// declared property getter: -(id)matches;
// declared property getter: -(id)matchingGroup;
// declared property getter: -(id)relayPushes;
// declared property getter: -(id)rid;
// declared property getter: -(int)sequence;
// declared property getter: -(id)serverRequest;
// declared property getter: -(id)sessionToken;
// declared property setter: -(void)setCdxTicket:(id)ticket;
// declared property setter: -(void)setMatchRequest:(id)request;
// declared property setter: -(void)setMatches:(id)matches;
// declared property setter: -(void)setMatchingGroup:(id)group;
// declared property setter: -(void)setRelayPushes:(id)pushes;
// declared property setter: -(void)setRid:(id)rid;
// declared property setter: -(void)setServerRequest:(id)request;
// declared property setter: -(void)setSessionToken:(id)token;
// declared property setter: -(void)setState:(int)state;
// declared property getter: -(int)state;
-(BOOL)transitionToState:(int)state;
@end

