/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface GKMultiDecoratedLabel : XXUnknownSuperclass {
@private
	NSArray* _labels;
}
@property(readonly, assign, nonatomic) NSArray* labels;	// @synthesize=_labels
-(void)addLabel:(id)label;
-(void)dealloc;
// declared property getter: -(id)labels;
-(void)layoutSubviews;
@end

