/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GameKit-Structs.h"
#import "GKCollectionCellContents.h"

@class UIImage, UIButton, UILabel, NSString, UIProgressIndicator;

@interface GKParticipantCellContents : GKCollectionCellContents {
@private
	UIImage* _image;
	int _kind;
	UILabel* _titleLabel;
	UILabel* _statusLabel;
	UIProgressIndicator* _progressIndicator;
	UIButton* _cancelBox;
	UIButton* _addButton;
	CGRect _imageFrame;
}
@property(retain, nonatomic) UIButton* addButton;	// @synthesize=_addButton
@property(retain, nonatomic) UIButton* cancelBox;	// @synthesize=_cancelBox
@property(assign, nonatomic) BOOL cancelBoxVisible;	// @dynamic
@property(retain, nonatomic) UIImage* image;	// @synthesize=_image
@property(assign, nonatomic) CGRect imageFrame;	// @synthesize=_imageFrame
@property(assign, nonatomic) int kind;	// @synthesize=_kind
@property(retain, nonatomic) UIProgressIndicator* progressIndicator;	// @synthesize=_progressIndicator
@property(assign, nonatomic) BOOL progressIndicatorVisible;	// @dynamic
@property(retain, nonatomic) NSString* status;	// @dynamic
@property(retain, nonatomic) UILabel* statusLabel;	// @synthesize=_statusLabel
@property(retain, nonatomic) NSString* title;	// @dynamic
@property(retain, nonatomic) UILabel* titleLabel;	// @synthesize=_titleLabel
-(id)init;
// declared property getter: -(id)addButton;
-(void)addButtonPressed;
// declared property getter: -(id)cancelBox;
// declared property getter: -(BOOL)cancelBoxVisible;
-(void)cancelPressed;
-(void)dealloc;
-(id)description;
-(void)drawRect:(CGRect)rect;
// declared property getter: -(id)image;
// declared property getter: -(CGRect)imageFrame;
// declared property getter: -(int)kind;
-(void)layoutSubviews;
-(void)prepareForReuse;
// declared property getter: -(id)progressIndicator;
// declared property getter: -(BOOL)progressIndicatorVisible;
// declared property setter: -(void)setAddButton:(id)button;
// declared property setter: -(void)setCancelBox:(id)box;
// declared property setter: -(void)setCancelBoxVisible:(BOOL)visible;
// declared property setter: -(void)setImage:(id)image;
// declared property setter: -(void)setImageFrame:(CGRect)frame;
// declared property setter: -(void)setKind:(int)kind;
// declared property setter: -(void)setProgressIndicator:(id)indicator;
// declared property setter: -(void)setProgressIndicatorVisible:(BOOL)visible;
// declared property setter: -(void)setStatus:(id)status;
// declared property setter: -(void)setStatusLabel:(id)label;
// declared property setter: -(void)setTitle:(id)title;
// declared property setter: -(void)setTitleLabel:(id)label;
// declared property getter: -(id)status;
// declared property getter: -(id)statusLabel;
// declared property getter: -(id)title;
// declared property getter: -(id)titleLabel;
@end

