/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKGameTitleView.h"
#import "GameKit-Structs.h"

@class NSString, GKRatingControl, GKCoreTextLabel;

@interface GKPurchasableGameTitleView : GKGameTitleView {
@private
	float _ratingStarValue;
	int _ratingCount;
	NSString* _developerName;
	GKCoreTextLabel* _developerLabel;
	GKRatingControl* _ratingControl;
	GKCoreTextLabel* _ratingLabel;
	BOOL _hideRating;
}
@property(retain, nonatomic) GKCoreTextLabel* developerLabel;	// @synthesize=_developerLabel
@property(retain, nonatomic) NSString* developerName;	// @synthesize=_developerName
@property(assign, nonatomic) BOOL hideRating;	// @synthesize=_hideRating
@property(retain, nonatomic) GKRatingControl* ratingControl;	// @synthesize=_ratingControl
@property(assign, nonatomic) int ratingCount;	// @synthesize=_ratingCount
@property(retain, nonatomic) GKCoreTextLabel* ratingLabel;	// @synthesize=_ratingLabel
@property(assign, nonatomic) float ratingStarValue;	// @synthesize=_ratingStarValue
-(id)init;
-(void)dealloc;
// declared property getter: -(id)developerLabel;
// declared property getter: -(id)developerName;
// declared property getter: -(BOOL)hideRating;
-(CGRect)layoutDeveloperNameWithBounds:(CGRect)bounds;
-(void)layoutSubviews;
// declared property getter: -(id)ratingControl;
// declared property getter: -(int)ratingCount;
// declared property getter: -(id)ratingLabel;
// declared property getter: -(float)ratingStarValue;
// declared property setter: -(void)setDeveloperLabel:(id)label;
// declared property setter: -(void)setDeveloperName:(id)name;
// declared property setter: -(void)setHideRating:(BOOL)rating;
// declared property setter: -(void)setRatingControl:(id)control;
// declared property setter: -(void)setRatingCount:(int)count;
// declared property setter: -(void)setRatingLabel:(id)label;
// declared property setter: -(void)setRatingStarValue:(float)value;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

