/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GameCenterUIServiceViewControllerDelegate.h"
#import "GKRemoteViewController.h"
#import "GameKit-Structs.h"

@class GKGame, GKGameCenterViewController, NSString;

@interface GKRemoteGameCenterViewController : GKRemoteViewController <GameCenterUIServiceViewControllerDelegate> {
@private
	GKGameCenterViewController* _delegate;
	int _viewState;
	NSString* _leaderboardCategory;
	int _leaderboardTimeScope;
	BOOL _shouldDisplayChallengePlayButton;
}
@property(assign, nonatomic) GKGameCenterViewController* delegate;	// @synthesize=_delegate
@property(retain, nonatomic) GKGame* game;
@property(retain, nonatomic) NSString* leaderboardCategory;	// @synthesize=_leaderboardCategory
@property(assign, nonatomic) int leaderboardTimeScope;	// @synthesize=_leaderboardTimeScope
@property(assign, nonatomic) BOOL shouldDisplayChallengePlayButton;	// @synthesize=_shouldDisplayChallengePlayButton
@property(assign, nonatomic) int viewState;	// @synthesize=_viewState
-(BOOL)_dismissSelfAfterGettingShouldFinish;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)getMethodsImplementedByChallengeEventHandlerDelegate:(id)delegate;
// declared property getter: -(id)leaderboardCategory;
// declared property getter: -(int)leaderboardTimeScope;
-(id)observedKeyPaths;
-(void)playPressedForChallenge:(id)challenge;
-(id)proxy:(id)proxy detailedSignatureForSelector:(SEL)selector;
-(void)remoteControllerDidChangeViewState:(id)remoteController;
-(id)remoteProtocol;
-(void)remoteViewControllerIsCanceling;
-(void)remoteViewControllerIsFinishing;
-(void)setAPIControllerFlags:(XXStruct_3bUrSB)flags;
-(void)setCurrentViewState:(int)state;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setLeaderboardCategory:(id)category;
// declared property setter: -(void)setLeaderboardTimeScope:(int)scope;
-(void)setNilValueForKey:(id)key;
// declared property setter: -(void)setShouldDisplayChallengePlayButton:(BOOL)displayChallengePlayButton;
// declared property setter: -(void)setViewState:(int)state;
// declared property getter: -(BOOL)shouldDisplayChallengePlayButton;
// declared property getter: -(int)viewState;
-(id)whitelistedClassNames;
@end

