/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKSectionArrayDataSource.h"

@class NSMutableDictionary, NSMutableArray, GKTurnBasedMatchesSection;

@interface GKTurnBasedMatchesDataSource : GKSectionArrayDataSource {
@private
	GKTurnBasedMatchesSection* _invitationSection;
	GKTurnBasedMatchesSection* _yourTurnSection;
	GKTurnBasedMatchesSection* _otherTurnSection;
	GKTurnBasedMatchesSection* _finishedSection;
	NSMutableArray* _matchIDs;
	NSMutableDictionary* _players;
}
@property(retain, nonatomic) GKTurnBasedMatchesSection* finishedSection;	// @synthesize=_finishedSection
@property(retain, nonatomic) GKTurnBasedMatchesSection* invitationSection;	// @synthesize=_invitationSection
@property(readonly, assign, nonatomic) int loadedMatchCount;	// @dynamic
@property(retain, nonatomic) NSMutableArray* matchIDs;	// @synthesize=_matchIDs
@property(retain, nonatomic) GKTurnBasedMatchesSection* otherTurnSection;	// @synthesize=_otherTurnSection
@property(retain, nonatomic) NSMutableDictionary* players;	// @synthesize=_players
@property(retain, nonatomic) GKTurnBasedMatchesSection* yourTurnSection;	// @synthesize=_yourTurnSection
-(id)initWithController:(id)controller;
-(void)dealloc;
-(id)description;
// declared property getter: -(id)finishedSection;
// declared property getter: -(id)invitationSection;
-(void)loadMatchDetailsWithCompletionHandler:(id)completionHandler;
-(void)loadPlayersForMatches:(id)matches withCompletionHandler:(id)completionHandler;
// declared property getter: -(int)loadedMatchCount;
// declared property getter: -(id)matchIDs;
-(void)matchIDsLoaded:(id)loaded;
-(void)matchesLoaded:(id)loaded withCompletionHandler:(id)completionHandler;
// declared property getter: -(id)otherTurnSection;
// declared property getter: -(id)players;
-(void)refreshDataWithCompletionHandlerAndError:(id)completionHandlerAndError;
// declared property setter: -(void)setFinishedSection:(id)section;
// declared property setter: -(void)setInvitationSection:(id)section;
// declared property setter: -(void)setMatchIDs:(id)ids;
// declared property setter: -(void)setOtherTurnSection:(id)section;
// declared property setter: -(void)setPlayers:(id)players;
// declared property setter: -(void)setYourTurnSection:(id)section;
-(void)tableView:(id)view updateStatusViewAfterLoading:(id)loading withError:(id)error;
-(void)tableView:(id)view updateStatusViewBeforeLoading:(id)loading;
// declared property getter: -(id)yourTurnSection;
@end

