/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKFriendLeaderboardSection.h"


@interface InGameFriendLeaderboardSection : GKFriendLeaderboardSection {
}
-(float)heightForHeaderInTableView:(id)tableView;
-(void)refreshDataWithCompletionHandlerAndError:(id)completionHandlerAndError;
-(int)rowCountInTableView:(id)tableView;
@end

