/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MKLayer : XXUnknownSuperclass {
	CGRect _hitBounds;
	CGPoint _hitOffset;
	CGPoint _hitOutset;
}
@property(readonly, assign, nonatomic) CGRect hitBounds;	// @synthesize=_hitBounds
@property(assign, nonatomic) CGPoint hitOffset;	// @synthesize=_hitOffset
@property(assign, nonatomic) CGPoint hitOutset;	// @synthesize=_hitOutset
-(BOOL)containsPoint:(CGPoint)point;
// declared property getter: -(CGRect)hitBounds;
// declared property getter: -(CGPoint)hitOffset;
// declared property getter: -(CGPoint)hitOutset;
-(void)setBounds:(CGRect)bounds;
// declared property setter: -(void)setHitOffset:(CGPoint)offset;
// declared property setter: -(void)setHitOutset:(CGPoint)outset;
@end

