/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface MKUsageReport : XXUnknownSuperclass {
	NSString* _key;
	unsigned _count;
}
@property(assign, nonatomic) unsigned count;	// @synthesize=_count
@property(readonly, assign, nonatomic) NSString* key;	// @synthesize=_key
-(id)initWithKey:(id)key count:(unsigned)count;
-(void)add:(unsigned)add;
// declared property getter: -(unsigned)count;
-(void)dealloc;
// declared property getter: -(id)key;
// declared property setter: -(void)setCount:(unsigned)count;
@end

