/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray, MKAnnotationView, MKPinAnnotationView, MKAnnotationContainerViewInternal;

@interface MKAnnotationContainerView : XXUnknownSuperclass {
@private
	MKAnnotationContainerViewInternal* _internal;
	NSMutableArray* _orderedAnnotations;
}
@property(readonly, assign, nonatomic) NSArray* annotations;
@property(retain, nonatomic) MKAnnotationView* bubbleAnnotationView;
@property(readonly, assign, nonatomic) MKPinAnnotationView* bubblePin;
@property(assign, nonatomic) Class calloutViewClass;
@property(copy, nonatomic) NSArray* selectedAnnotations;
-(id)initWithFrame:(CGRect)frame;
-(void)_addCallout:(id)callout forAnnotationView:(id)annotationView anchorPoint:(CGPoint)point boundaryRect:(CGRect)rect animated:(BOOL)animated;
-(id)_addViewForAnnotation:(id)annotation;
-(void)_addViewsForAnnotations:(id)annotations animated:(BOOL)animated;
-(id)_annotationViewForSelectionAtPoint:(CGPoint)point avoidCurrent:(BOOL)current;
-(CGPoint)_bubbleAnchorPoint;
-(void)_calloutAccessoryControlTapped:(id)tapped;
-(void)_deselectAnnotationView;
-(void)_deselectAnnotationViewWithAnimation:(BOOL)animation;
-(void)_deselectAnnotationViewWithAnimation:(BOOL)animation tellDelegate:(BOOL)delegate;
-(void)_displayAnnotationsInMapRect:(XXStruct_Yvvv9D)mapRect includePending:(BOOL)pending animated:(BOOL)animated removeOffscreenAnnotations:(BOOL)annotations;
-(XXStruct_Yvvv9D)_displayRect;
-(void)_dropDraggingAnnotationViewAnimated:(BOOL)animated;
-(void)_dropPinsIfNeeded:(id)needed animated:(BOOL)animated;
-(void)_findNextView:(id*)view orientation:(int*)orientation context:(id)context;
-(void)_liftForDragging:(id)dragging mouseDownPoint:(CGPoint)point;
-(XXStruct_Yvvv9D)_mapRectWithFraction:(double)fraction ofVisible:(XXStruct_Yvvv9D)visible;
-(void)_notifyAddedAnnotationViews:(id)views animated:(BOOL)animated;
-(void)_refreshDisplayedAnnotations;
-(void)_registerObserverForAnnotation:(id)annotation;
-(void)_registerObserverForBubbleAnnotation:(id)bubbleAnnotation;
-(BOOL)_registeredForAddressBookChanges;
-(void)_removeAnnotationView:(id)view;
-(void)_removeAnnotationView:(id)view updateCollections:(BOOL)collections;
-(void)_removeAnnotationViews:(id)views;
-(void)_removeAnnotationViewsExcludingAnnotation:(id)annotation ofClassType:(Class)classType;
-(void)_removeBubbleWithAnimation:(BOOL)animation;
-(void)_removeBubbleWithAnimation:(BOOL)animation tellDelegate:(BOOL)delegate;
-(void)_replaceAnnotation:(id)annotation withAnnotation:(id)annotation2;
-(void)_resetAnnotationViewPerspective;
-(void)_scrollToBubble;
-(void)_setRegisteredForAddressBookChanges:(BOOL)addressBookChanges;
-(void)_setSelectedAnnotationView:(id)view bounce:(BOOL)bounce pressed:(BOOL)pressed scrollToFit:(BOOL)fit;
-(void)_setSelectedAnnotationView:(id)view bounce:(BOOL)bounce pressed:(BOOL)pressed scrollToFit:(BOOL)fit avoid:(CGRect)avoid;
-(void)_showBubbleForAnnotationView:(id)annotationView bounce:(BOOL)bounce scrollToFit:(BOOL)fit;
-(void)_showBubbleForAnnotationView:(id)annotationView bounce:(BOOL)bounce scrollToFit:(BOOL)fit avoid:(CGRect)avoid;
-(void)_unregisterObserverForAnnotation:(id)annotation;
-(void)_unregisterObserverForBubbleAnnotation:(id)bubbleAnnotation;
-(void)_updateAnnotationView:(id)view;
-(void)_updateAnnotationViewPerspective;
-(void)_updateBubble;
-(void)_updateOrientationOfViews:(id)views;
-(void)_updateOrientationOfViews:(id)views relative:(id)relative projectionView:(id)view;
-(void)_updateOrientationOfViewsCorrect:(id)viewsCorrect relative:(id)relative projectionView:(id)view;
-(void)_updateOrientationOfViewsFast:(id)viewsFast relative:(id)relative projectionView:(id)view;
-(void)_userLocationInView:(id)view frame:(CADoubleRect*)frame center:(CADoublePoint*)center accuracy:(float*)accuracy;
-(void)_userLocationInView:(id)view frame:(CADoubleRect*)frame center:(CADoublePoint*)center accuracy:(float*)accuracy location:(id)location;
-(BOOL)_userLocationPosition:(CADoublePoint*)position bounds:(CADoubleRect*)bounds accuracy:(float*)accuracy location:(id)location;
-(id)_viewForInternalAnnotation:(id)internalAnnotation;
-(id)_viewForUserLocationAnnotation:(id)userLocationAnnotation;
-(CGRect)_visibleCenteringRect;
-(CGRect)_visibleCenteringRectInView:(id)view;
-(CGRect)_visibleRect;
-(void)_willRemoveInternalAnnotationView:(id)view;
-(CGSize)accessoryPadding;
-(void)addAnnotation:(id)annotation;
-(void)addAnnotations:(id)annotations;
-(void)addManagedAnnotation:(id)annotation;
-(void)addOrderedAnnotations:(id)annotations;
-(void)addSubview:(id)subview;
-(id)addViewForManagedAnnotation:(id)managedAnnotation notifyDelegate:(BOOL)delegate;
-(void)annotationViewDidChangeZIndex:(id)annotationView;
-(id)annotationViewForPoint:(CGPoint)point;
-(id)annotationViews;
-(void)annotationViewsDidChangeZIndex:(id)annotationViews;
// declared property getter: -(id)annotations;
-(id)annotationsInMapRect:(XXStruct_Yvvv9D)mapRect;
// declared property getter: -(id)bubbleAnnotationView;
// declared property getter: -(id)bubblePin;
-(id)calloutAnnotationView;
-(id)calloutView;
-(void)calloutView:(id)view didMoveToAnchorPoint:(CGPoint)anchorPoint animated:(BOOL)animated;
-(void)calloutView:(id)view willMoveToAnchorPoint:(CGPoint)anchorPoint animated:(BOOL)animated;
// declared property getter: -(Class)calloutViewClass;
-(CGPoint)convertCoordinate:(CADoublePoint)coordinate toPointToView:(id)view;
-(CADoublePoint)coordinateForAnnotationView:(id)annotationView;
-(XXStruct_PallAB)currentComparisonContext;
-(void)dealloc;
-(id)delegate;
-(id)dequeueReusableAnnotationViewWithIdentifier:(id)identifier;
-(void)deselectAnnotation:(id)annotation animated:(BOOL)animated;
-(BOOL)didAddUserLocationView;
-(void)draggingTouchMovedToPoint:(CGPoint)point;
-(void)forEachAnnotation:(id)eachAnnotation;
-(BOOL)freezeUserLocationView;
-(BOOL)hasDroppingPins;
-(BOOL)hasPendingAnimations;
-(unsigned)indexForAnnotationView:(id)annotationView;
-(BOOL)isAnimationsEnabled;
-(CGAffineTransform)mapTransform;
-(unsigned)mapType;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)pinDidDrop:(id)pin animated:(BOOL)animated;
-(void)removeAnnotation:(id)annotation;
-(void)removeAnnotationViewsRotationAnimations;
-(void)removeAnnotations:(id)annotations;
-(void)resetBubble;
-(void)resetUserLocation;
-(void)restoreUserLocationViewUpdateMode;
-(id)searchResultPins;
-(void)selectAnnotation:(id)annotation animated:(BOOL)animated;
-(void)selectAnnotation:(id)annotation animated:(BOOL)animated avoid:(CGRect)avoid;
// declared property getter: -(id)selectedAnnotations;
-(void)setAnimationsEnabled:(BOOL)enabled;
-(void)setAnnotationViewsRotationRadians:(float)radians animation:(id)animation;
// declared property setter: -(void)setBubbleAnnotationView:(id)view;
// declared property setter: -(void)setCalloutViewClass:(Class)aClass;
-(void)setDelegate:(id)delegate;
-(void)setDidAddUserLocationView:(BOOL)addUserLocationView;
-(void)setMapTransform:(CGAffineTransform)transform;
-(void)setMapType:(unsigned)type;
// declared property setter: -(void)setSelectedAnnotations:(id)annotations;
-(void)setUserLocationView:(id)view;
-(void)setUserLocationViewUpdateMode:(int)mode;
-(void)setVisibleMapRect:(XXStruct_Yvvv9D)rect;
-(BOOL)showAddedAnnotationsAnimated:(BOOL)animated;
-(void)showAnnotationsInMapRect:(XXStruct_Yvvv9D)mapRect;
-(void)showBubbleAfterScroll;
-(void)updateAnnotationLocationsDuringAnimation:(BOOL)animation;
-(void)updateUserLocationView;
-(void)updateUserLocationView:(BOOL)view;
-(id)userLocation;
-(BOOL)userLocationAnnotationDidHide;
-(BOOL)userLocationAnnotationWillShow;
-(id)userLocationView;
-(int)userLocationViewUpdateMode;
-(id)viewForAnnotation:(id)annotation;
@end

