/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */



@protocol MKCacheableObject
@property(assign, nonatomic) unsigned _mapkit_cache_accessTime;
@property(readonly, assign, nonatomic) id _mapkit_cache_key;
// declared property getter: -(unsigned)_mapkit_cache_accessTime;
// declared property getter: -(id)_mapkit_cache_key;
@optional
-(void)compact;
@required
// declared property setter: -(void)set_mapkit_cache_accessTime:(unsigned)time;
@end

