/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "NSObject.h"


@protocol MKMapViewDelegate <NSObject>
@optional
-(void)mapView:(id)view annotationView:(id)view2 calloutAccessoryControlTapped:(id)tapped;
-(void)mapView:(id)view annotationView:(id)view2 didChangeDragState:(unsigned)state fromOldState:(unsigned)oldState;
-(void)mapView:(id)view didAddAnnotationViews:(id)views;
-(void)mapView:(id)view didAddOverlayViews:(id)views;
-(void)mapView:(id)view didChangeUserTrackingMode:(int)mode animated:(BOOL)animated;
-(void)mapView:(id)view didDeselectAnnotationView:(id)view2;
-(void)mapView:(id)view didFailToLocateUserWithError:(id)error;
-(void)mapView:(id)view didSelectAnnotationView:(id)view2;
-(void)mapView:(id)view didUpdateUserLocation:(id)location;
-(void)mapView:(id)view regionDidChangeAnimated:(BOOL)region;
-(void)mapView:(id)view regionWillChangeAnimated:(BOOL)region;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(id)mapView:(id)view viewForOverlay:(id)overlay;
-(void)mapViewDidFailLoadingMap:(id)mapView withError:(id)error;
-(void)mapViewDidFinishLoadingMap:(id)mapView;
-(void)mapViewDidStopLocatingUser:(id)mapView;
-(void)mapViewWillStartLoadingMap:(id)mapView;
-(void)mapViewWillStartLocatingUser:(id)mapView;
@end

