/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "MapKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UIView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface MKOrientationContext : XXUnknownSuperclass {
@private
	NSMutableArray* orientViews;
	NSArray* relativeViews;
	UIView* projectionView;
	CGRect* relativeViewFrames;
}
-(id)initWithViewsToOrient:(id)orient relativeViews:(id)views projectionView:(id)view;
-(void)_computeRelativeViewFrame:(id)frame;
-(void)_computeRelativeViewFrames;
-(void)dealloc;
-(void)invalidateView:(id)view;
@end

