/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MapKit.framework/MapKit
 */

#import "NSObject.h"


@protocol MKWorldGestureControllerDelegate <NSObject>
-(void)gestureControllerDidStopRotating:(id)gestureController willDecelerate:(BOOL)decelerate;
-(void)gestureControllerDidStopRotatingDecelerating:(id)gestureController;
-(void)gestureControllerWillStartRotating:(id)gestureController;
@end

