/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class QLDisplayBundle, UIActivityIndicatorView, NSString, UILabel;
@protocol QLProgressViewDelegate;

@interface QLProgressView : XXUnknownSuperclass {
	id<QLProgressViewDelegate> _delegate;
	int _backgroundColorType;
	QLDisplayBundle* _displayBundle;
	UIActivityIndicatorView* _progressIndicator;
	UILabel* _loadingTextLabel;
@private
	NSString* _loadintTextForMissingFiles;
}
@property(assign) id<QLProgressViewDelegate> delegate;	// @synthesize=_delegate
@property(retain) NSString* loadintTextForMissingFiles;	// @synthesize=_loadintTextForMissingFiles
-(id)initWithBackgroundColorType:(int)backgroundColorType loadintTextForMissingFiles:(id)missingFiles;
-(int)backgroundColorType;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)layoutSubviews;
// declared property getter: -(id)loadintTextForMissingFiles;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setLoadintTextForMissingFiles:(id)missingFiles;
-(void)touchesBegan:(id)began withEvent:(id)event;
@end

