/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/PassKit.framework/PassKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, WLImage, NSArray, WLBarcode;

@interface WLCardContent : XXUnknownSuperclass {
@private
	WLBarcode* _barcode;
	int _transitType;
	WLImage* _footerImage;
	NSArray* _storeIdentifiers;
	NSString* _logoText;
	NSString* _localizedDescription;
	NSArray* _frontFieldBuckets;
	NSArray* _backFieldBuckets;
}
@property(copy, nonatomic) NSArray* backFieldBuckets;	// @synthesize=_backFieldBuckets
@property(retain, nonatomic) WLBarcode* barcode;	// @synthesize=_barcode
@property(retain, nonatomic) WLImage* footerImage;	// @synthesize=_footerImage
@property(copy, nonatomic) NSArray* frontFieldBuckets;	// @synthesize=_frontFieldBuckets
@property(copy, nonatomic) NSString* localizedDescription;	// @synthesize=_localizedDescription
@property(copy, nonatomic) NSString* logoText;	// @synthesize=_logoText
@property(copy, nonatomic) NSArray* storeIdentifiers;	// @synthesize=_storeIdentifiers
@property(assign, nonatomic) int transitType;	// @synthesize=_transitType
+(BOOL)supportsSecureCoding;
-(id)initWithCardURL:(id)cardURL;
-(id)initWithCoder:(id)coder;
// declared property getter: -(id)backFieldBuckets;
// declared property getter: -(id)barcode;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(id)footerImage;
// declared property getter: -(id)frontFieldBuckets;
// declared property getter: -(id)localizedDescription;
// declared property getter: -(id)logoText;
// declared property setter: -(void)setBackFieldBuckets:(id)buckets;
// declared property setter: -(void)setBarcode:(id)barcode;
// declared property setter: -(void)setFooterImage:(id)image;
// declared property setter: -(void)setFrontFieldBuckets:(id)buckets;
// declared property setter: -(void)setLocalizedDescription:(id)description;
// declared property setter: -(void)setLogoText:(id)text;
// declared property setter: -(void)setStoreIdentifiers:(id)identifiers;
// declared property setter: -(void)setTransitType:(int)type;
// declared property getter: -(id)storeIdentifiers;
// declared property getter: -(int)transitType;
@end

