/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ABModel, AccountsManager, NSDictionary, NSMutableDictionary, NSArray;

@interface ABAccountsAndGroupDataSource : XXUnknownSuperclass <UITableViewDataSource> {
@private
	ABModel* _model;
	NSArray* _accountIdentifiers;
	NSArray* _accountDisplayNames;
	NSDictionary* _groupsByAccountIdentifier;
	NSMutableDictionary* _headerViewsBySection;
	BOOL _hidesSearchableSources;
	BOOL _hidesGlobalGroupWrapper;
	AccountsManager* _accountsManager;
}
@property(retain, nonatomic) AccountsManager* accountsManager;	// @synthesize=_accountsManager
@property(assign, nonatomic) BOOL hidesGlobalGroupWrapper;	// @synthesize=_hidesGlobalGroupWrapper
@property(assign, nonatomic) BOOL hidesSearchableSources;	// @synthesize=_hidesSearchableSources
@property(retain, nonatomic) ABModel* model;	// @synthesize=_model
-(id)init;
-(id)accountDisplayNameAtIndex:(int)index;
-(id)accountGroupWrappers;
// declared property getter: -(id)accountsManager;
-(void)cacheHeaderView:(id)view forSection:(unsigned)section;
-(id)cachedHeaderViewForSection:(unsigned)section;
-(void)cancelScheduledRefresh;
-(void)dealloc;
-(id)defaultGroupWrapper;
-(id)groupNameForIndexPath:(id)indexPath;
-(id)groupWrapperForIndexPath:(id)indexPath;
-(BOOL)hasMultipleAccountsOrGroups;
// declared property getter: -(BOOL)hidesGlobalGroupWrapper;
// declared property getter: -(BOOL)hidesSearchableSources;
-(id)indexPathForGroupWrapper:(id)groupWrapper;
// declared property getter: -(id)model;
-(int)numberOfAccounts;
-(int)numberOfGroupsForAccountIdentifier:(id)accountIdentifier;
-(int)numberOfGroupsInAccountAtIndex:(int)index;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)preferredTableViewStyle;
-(void)reloadData;
-(void)reloadDataIncludingAccountsManager:(BOOL)manager;
-(void)scheduleRefresh;
// declared property setter: -(void)setAccountsManager:(id)manager;
// declared property setter: -(void)setHidesGlobalGroupWrapper:(BOOL)wrapper;
// declared property setter: -(void)setHidesSearchableSources:(BOOL)sources;
// declared property setter: -(void)setModel:(id)model;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
@end

