/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import "AddressBookUI-Structs.h"
#import "ABMultiCellContentView_DisplayAlternate.h"

@class NSMutableArray, NSArray;

@interface ABMultiCellContentView_Address : ABMultiCellContentView_DisplayAlternate {
@private
	NSArray* _lineInfos;
	NSMutableArray* _lineSubviews;
	NSRange _streetRange;
	unsigned _entryFieldIndexOfFirstStreetField;
	NSMutableArray* _verticalDividers;
}
+(int)calculateStreetRowsForText:(id)text;
+(CGSize)layoutSubviewsForView:(id)view usingSize:(CGSize)size propertyGroup:(id)group info:(id)info styleProvider:(id)provider whenEditing:(BOOL)editing;
+(id)lineInfosForPropertyGroup:(id)propertyGroup info:(id)info;
+(unsigned)rowsForPropertyGroup:(id)propertyGroup info:(id)info;
+(id)streetTextForPropertyGroup:(id)propertyGroup info:(id)info;
-(void)addStreetFieldAnimated:(BOOL)animated;
-(void)dealloc;
-(unsigned)lineIndexOfStreetField:(id)streetField;
-(id)pickerView;
-(id)propertyKeyForTag:(int)tag;
-(void)reload;
-(void)reloadFromModel;
-(void)removeStreetFieldAtIndex:(unsigned)index animated:(BOOL)animated;
-(void)removeTextFieldAnimationDidStop:(id)removeTextFieldAnimation finished:(id)finished context:(void*)context;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)setPropertyGroupInfo:(id)info;
-(id)streetFieldAtLineIndex:(unsigned)lineIndex;
-(int)tagForPropertyKey:(id)propertyKey;
-(void)textFieldDidEndEditing:(id)textField;
-(void)textFieldTextDidChange:(id)textFieldText;
@end

