/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSManagedObjectContext, NSFetchRequest, _PFArray;

__attribute__((visibility("hidden")))
@interface _PFBatchFaultingArray : XXUnknownSuperclass {
@private
	int _cd_rc;
	unsigned _count;
	_PFArray* _array;
	unsigned* _entryFlags;
	NSManagedObjectContext* _moc;
	NSFetchRequest* _request;
	unsigned _batchSize;
	unsigned* _LRUBatches;
	PFBatchFaultingArrayFlags _flags;
}
+(BOOL)accessInstanceVariablesDirectly;
+(id)alloc;
+(id)allocWithZone:(NSZone*)zone;
+(void)initialize;
-(id)initWithPFArray:(id)pfarray andRequest:(id)request andContext:(id)context;
-(BOOL)_isDeallocating;
-(id)_newSubArrayInRange:(NSRange)range asMutable:(BOOL)aMutable;
-(BOOL)_tryRetain;
-(void)_turnAllBatchesIntoFaults;
-(id)arrayFromObjectIDs;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)count;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)dealloc;
-(id)description;
-(void)getObjects:(id*)objects;
-(void)getObjects:(id*)objects range:(NSRange)range;
-(unsigned)indexOfManagedObjectForObjectID:(id)objectID;
-(unsigned)indexOfObject:(id)object;
-(unsigned)indexOfObject:(id)object inRange:(NSRange)range;
-(unsigned)indexOfObjectIdenticalTo:(id)to;
-(unsigned)indexOfObjectIdenticalTo:(id)to inRange:(NSRange)range;
-(BOOL)isEqualToArray:(id)array;
-(id)managedObjectIDAtIndex:(unsigned)index;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)newArrayFromObjectIDs;
-(id)objectAtIndex:(unsigned)index;
-(oneway void)release;
-(id)retain;
-(unsigned)retainCount;
-(id)subarrayWithRange:(NSRange)range;
@end

