/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "NSPersistentStoreRequest.h"
#import "CoreData-Structs.h"
#import "NSCoding.h"
#import "NSFetchRequest.h"

@class NSPredicate, NSArray, NSEntityDescription;

@interface NSFetchRequest : NSPersistentStoreRequest <NSCoding> {
@private
	NSArray* _groupByProperties;
	NSPredicate* _havingPredicate;
	unsigned _offset;
	NSArray* _valuesToFetch;
	NSEntityDescription* _entity;
	NSPredicate* _predicate;
	NSArray* _sortDescriptors;
	unsigned _batchSize;
	unsigned long _fetchLimit;
	NSArray* _relationshipKeyPathsForPrefetching;
	fetchRequestFlags _flags;
}
+(BOOL)accessInstanceVariablesDirectly;
+(id)fetchRequestWithEntityName:(id)entityName;
+(void)initialize;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)initWithEntityName:(id)entityName;
-(id)_newValidatedProperties:(id)properties groupBy:(BOOL)by error:(id*)error;
-(id)affectedStores;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(id)entity;
-(id)entityName;
-(unsigned)fetchBatchSize;
-(unsigned)fetchLimit;
-(unsigned)fetchOffset;
-(id)groupByProperties;
-(unsigned)hash;
-(id)havingPredicate;
-(BOOL)includesPendingChanges;
-(BOOL)includesPropertyValues;
-(BOOL)includesSubentities;
-(BOOL)isEqual:(id)equal;
-(id)predicate;
-(id)propertiesToFetch;
-(id)propertiesToGroupBy;
-(id)relationshipKeyPathsForPrefetching;
-(unsigned)resultType;
-(BOOL)returnsDistinctResults;
-(BOOL)returnsObjectsAsFaults;
-(void)setAffectedStores:(id)stores;
-(void)setEntity:(id)entity;
-(void)setFetchBatchSize:(unsigned)size;
-(void)setFetchLimit:(unsigned)limit;
-(void)setFetchOffset:(unsigned)offset;
-(void)setGroupByProperties:(id)properties;
-(void)setHavingPredicate:(id)predicate;
-(void)setIncludesPendingChanges:(BOOL)changes;
-(void)setIncludesPropertyValues:(BOOL)values;
-(void)setIncludesSubentities:(BOOL)subentities;
-(void)setPredicate:(id)predicate;
-(void)setPropertiesToFetch:(id)fetch;
-(void)setPropertiesToGroupBy:(id)groupBy;
-(void)setRelationshipKeyPathsForPrefetching:(id)prefetching;
-(void)setResultType:(unsigned)type;
-(void)setReturnsDistinctResults:(BOOL)results;
-(void)setReturnsObjectsAsFaults:(BOOL)faults;
-(void)setShouldRefreshRefetchedObjects:(BOOL)refreshRefetchedObjects;
-(void)setSortDescriptors:(id)descriptors;
-(BOOL)shouldRefreshRefetchedObjects;
-(id)sortDescriptors;
@end

@interface NSFetchRequest (_NSCoreDataSPI)
@end

@interface NSFetchRequest (_NSInternalMethods)
-(void)_incrementInUseCounter;
-(BOOL)_isEditable;
-(void)_resolveEntityWithContext:(id)context;
-(void)_throwIfNotEditable;
-(void)_writeIntoData:(id)data propertiesDict:(id)dict uniquedPropertyNames:(id)names uniquedStrings:(id)strings uniquedData:(id)data5 uniquedMappings:(id)mappings entities:(id)entities;
-(BOOL)hasChanges;
-(unsigned)requestType;
-(id)stores;
@end

