/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/StoreKit.framework/StoreKit
 */

#import "SKPayment.h"

@class NSString, NSData;

@interface SKMutablePayment : SKPayment {
}
@property(copy, nonatomic) NSString* productIdentifier;	// @dynamic
@property(assign, nonatomic) int quantity;	// @dynamic
@property(copy, nonatomic) NSData* requestData;	// @dynamic
// declared property setter: -(void)setProductIdentifier:(id)identifier;
// declared property setter: -(void)setQuantity:(int)quantity;
// declared property setter: -(void)setRequestData:(id)data;
@end

