/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "EventKitUI-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UIColor;

__attribute__((visibility("hidden")))
@interface EKEventDetailAttendeesListView : XXUnknownSuperclass {
@private
	NSArray* _acceptedNames;
	NSArray* _maybeNames;
	NSArray* _declinedNames;
	NSArray* _noReplyNames;
	NSArray* _ungroupedNames;
	UIColor* textColor;
	UIColor* highlightedTextColor;
	BOOL highlighted;
	BOOL _groupsNames;
}
@property(retain, nonatomic) NSArray* acceptedNames;	// @synthesize=_acceptedNames
@property(retain, nonatomic) NSArray* declinedNames;	// @synthesize=_declinedNames
@property(assign, nonatomic) BOOL groupsNames;	// @synthesize=_groupsNames
@property(assign, nonatomic) BOOL highlighted;	// @synthesize
@property(retain, nonatomic) UIColor* highlightedTextColor;	// @synthesize
@property(retain, nonatomic) NSArray* maybeNames;	// @synthesize=_maybeNames
@property(retain, nonatomic) NSArray* noReplyNames;	// @synthesize=_noReplyNames
@property(retain, nonatomic) UIColor* textColor;	// @synthesize
@property(retain, nonatomic) NSArray* ungroupedNames;	// @synthesize=_ungroupedNames
-(void)_drawColumnOfStrings:(id)strings inRange:(NSRange)range startingAtPoint:(CGPoint)point givenWidth:(float)width;
-(float)_heightForGroupOfAttendeeNames:(id)attendeeNames;
// declared property getter: -(id)acceptedNames;
-(void)dealloc;
// declared property getter: -(id)declinedNames;
-(void)drawInvitees:(id)invitees withStatus:(id)status startingAtPoint:(CGPoint)point givenWidth:(float)width;
-(void)drawRect:(CGRect)rect;
// declared property getter: -(BOOL)groupsNames;
// declared property getter: -(BOOL)highlighted;
// declared property getter: -(id)highlightedTextColor;
-(BOOL)isHighlighted;
// declared property getter: -(id)maybeNames;
// declared property getter: -(id)noReplyNames;
// declared property setter: -(void)setAcceptedNames:(id)names;
// declared property setter: -(void)setDeclinedNames:(id)names;
// declared property setter: -(void)setGroupsNames:(BOOL)names;
// declared property setter: -(void)setHighlighted:(BOOL)highlighted;
// declared property setter: -(void)setHighlightedTextColor:(id)color;
// declared property setter: -(void)setMaybeNames:(id)names;
// declared property setter: -(void)setNoReplyNames:(id)names;
// declared property setter: -(void)setTextColor:(id)color;
// declared property setter: -(void)setUngroupedNames:(id)names;
-(CGSize)sizeThatFits:(CGSize)fits;
// declared property getter: -(id)textColor;
// declared property getter: -(id)ungroupedNames;
@end

