/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import "_NSCFURLProtocolBridge.h"

@class NSMutableArray, NSThread, NSCountedSet;

@interface _NSCFURLProtocolBridgeWithTrampoline : _NSCFURLProtocolBridge {
	NSMutableArray* _workQueue;
	NSCountedSet* _runloops;
	BOOL _canSignalDirectly;
	NSThread* _processThread;
}
-(id)initWithCFURLProtocol:(CFURLProtocolRef)cfurlprotocol request:(id)request protocolClass:(Class)aClass;
-(void)dealloc;
-(void)finalize;
-(void)processEventQ;
-(void)pushEvent:(id)event from:(const char*)from;
-(void)releaseWorkQueue;
-(void)schedule:(CFRunLoopRef)schedule mode:(CFStringRef)mode;
-(BOOL)shouldSignalDirectly;
-(void)unschedule:(CFRunLoopRef)unschedule mode:(CFStringRef)mode;
@end

