/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSDirectoryEnumerator.h"
#import "Foundation-Structs.h"


__attribute__((visibility("hidden")))
@interface NSURLDirectoryEnumerator : NSDirectoryEnumerator {
@private
	CFURLEnumeratorRef _enumerator;
	id _errorHandler;
	BOOL shouldContinue;
}
@property(copy) id errorHandler;	// @synthesize=_errorHandler
-(id)initWithURL:(id)url includingPropertiesForKeys:(id)keys options:(unsigned)options errorHandler:(id)handler;
-(void)dealloc;
-(id)directoryAttributes;
// declared property getter: -(id)errorHandler;
-(id)fileAttributes;
-(void)finalize;
-(unsigned)level;
-(id)nextObject;
// declared property setter: -(void)setErrorHandler:(id)handler;
-(void)skipDescendants;
-(void)skipDescendents;
@end

