/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import "NSObject.h"


@protocol EKCalendarItemEditorDelegate <NSObject>
@optional
-(void)editor:(id)editor didChangeHeightAnimated:(BOOL)animated;
-(void)editor:(id)editor didCompleteWithAction:(int)action;
-(void)editor:(id)editor prepareCalendarItemForEdit:(id)edit;
@end

