/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "OccurrenceCacheDataSourceProtocol.h"

@class NSArray, NSMutableDictionary, EKEventStore, NSSet;

@interface OccurrenceCacheDataSource : XXUnknownSuperclass <OccurrenceCacheDataSourceProtocol> {
	EKEventStore* _eventStore;
	NSSet* _calendars;
	NSArray* _cachedDays;
	NSMutableDictionary* _cachedOccurrences;
	int _cachedDaysSeed;
}
-(id)initWithEventStore:(id)eventStore calendars:(id)calendars;
-(id)_cachedDays;
-(int)cachedDayCount;
-(id)cachedOccurrenceAtIndexPath:(id)indexPath;
-(BOOL)cachedOccurrencesAreBeingGenerated;
-(int)countOfOccurrencesAtDayIndex:(int)dayIndex;
-(id)dateAtDayIndex:(int)dayIndex;
-(void)dealloc;
-(void)fetchDaysInBackgroundStartingFromSection:(int)section;
-(void)invalidate;
-(void)invalidateCachedOccurrences;
-(void)searchWithTerm:(id)term;
-(int)sectionForCachedOccurrencesOnDate:(id)cachedOccurrencesOnDate;
-(void)stopSearching;
-(BOOL)supportsFakeTodaySection;
-(BOOL)supportsInvitations;
@end

