/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/iAd.framework/iAd
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, ADXPCConnection;

@interface ADRemoteInvocationProxy : XXUnknownSuperclass {
@private
	ADXPCConnection* _connection;
	NSString* _messageName;
	NSString* _identifier;
	id _connectionDelegate;
}
@property(readonly, assign, nonatomic) BOOL available;
@property(retain, nonatomic) ADXPCConnection* connection;	// @synthesize=_connection
@property(assign, nonatomic) id connectionDelegate;	// @synthesize=_connectionDelegate
@property(copy, nonatomic) NSString* identifier;	// @synthesize=_identifier
@property(copy, nonatomic) NSString* messageName;	// @synthesize=_messageName
// declared property getter: -(BOOL)available;
// declared property getter: -(id)connection;
// declared property getter: -(id)connectionDelegate;
-(void)dealloc;
-(void)forwardInvocation:(id)invocation;
// declared property getter: -(id)identifier;
// declared property getter: -(id)messageName;
-(id)methodSignatureForSelector:(SEL)selector;
-(void)sendMessage:(id)message;
// declared property setter: -(void)setConnection:(id)connection;
// declared property setter: -(void)setConnectionDelegate:(id)delegate;
// declared property setter: -(void)setIdentifier:(id)identifier;
// declared property setter: -(void)setMessageName:(id)name;
@end

