/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MPQueueFeeder;

@interface MPQueueFeederState : XXUnknownSuperclass {
	MPQueueFeeder* _feeder;
	unsigned _currentItemIndex;
	double _currentTime;
	int _feederMode;
}
@property(assign, nonatomic) unsigned currentItemIndex;	// @synthesize=_currentItemIndex
@property(assign, nonatomic) double currentTime;	// @synthesize=_currentTime
@property(retain, nonatomic) MPQueueFeeder* feeder;	// @synthesize=_feeder
@property(assign, nonatomic) int feederMode;	// @synthesize=_feederMode
-(id)initWithStateOfAVController:(id)avcontroller;
// declared property getter: -(unsigned)currentItemIndex;
// declared property getter: -(double)currentTime;
-(void)dealloc;
-(id)description;
// declared property getter: -(id)feeder;
// declared property getter: -(int)feederMode;
// declared property setter: -(void)setCurrentItemIndex:(unsigned)index;
// declared property setter: -(void)setCurrentTime:(double)time;
// declared property setter: -(void)setFeeder:(id)feeder;
// declared property setter: -(void)setFeederMode:(int)mode;
@end

