/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UILabel, UIImageView, UIButton, UITableView, UIImage, UIActivityIndicatorView, UIFont, NSString;

@interface GKContentView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _messageLabel;
	UIImageView* _iconView;
	UIButton* _cancelButton;
	UIButton* _otherButton;
	UITableView* _table;
	UIImageView* _tableWellView;
	NSArray* _connectionButtons;
	UIActivityIndicatorView* _activityIndicator;
	BOOL _needsLayout;
}
@property(retain, nonatomic) UIActivityIndicatorView* activityIndicator;	// @synthesize=_activityIndicator
@property(retain, nonatomic) UIButton* cancelButton;	// @synthesize=_cancelButton
@property(readonly, assign, nonatomic) NSArray* connectionButtons;	// @synthesize=_connectionButtons
@property(assign, nonatomic) UIImage* icon;	// @dynamic
@property(retain, nonatomic) UIImageView* iconView;	// @synthesize=_iconView
@property(assign, nonatomic) NSString* message;	// @dynamic
@property(readonly, assign, nonatomic) UIFont* messageFont;	// @dynamic
@property(retain, nonatomic) UILabel* messageLabel;	// @synthesize=_messageLabel
@property(assign, nonatomic) int numberOfMessageLines;	// @dynamic
@property(assign, nonatomic) int numberOfTitleLines;	// @dynamic
@property(retain, nonatomic) UIButton* otherButton;	// @synthesize=_otherButton
@property(readonly, assign, nonatomic) UITableView* table;	// @dynamic
@property(assign, nonatomic) NSString* title;	// @dynamic
@property(readonly, assign, nonatomic) UIFont* titleFont;	// @dynamic
@property(retain, nonatomic) UILabel* titleLabel;	// @synthesize=_titleLabel
+(float)maxTextWidth;
-(id)initWithTitle:(id)title message:(id)message icon:(id)icon cancelButtonTitle:(id)title4 otherButtonTitle:(id)title5;
-(id)_createButton:(BOOL)button;
-(void)_createCancelButtonWithTitle:(id)title;
-(id)_createConnectionButtonWithType:(unsigned)type;
-(void)_createMessageLabelIfNeeded;
-(void)_createOtherButtonWithTitle:(id)title;
-(void)_createTitleLabelIfNeeded;
// declared property getter: -(id)activityIndicator;
// declared property getter: -(id)cancelButton;
// declared property getter: -(id)connectionButtons;
-(void)dealloc;
// declared property getter: -(id)icon;
// declared property getter: -(id)iconView;
-(void)layout;
-(void)layoutIfNeeded;
// declared property getter: -(id)message;
// declared property getter: -(id)messageFont;
// declared property getter: -(id)messageLabel;
// declared property getter: -(int)numberOfMessageLines;
// declared property getter: -(int)numberOfTitleLines;
// declared property getter: -(id)otherButton;
// declared property setter: -(void)setActivityIndicator:(id)indicator;
// declared property setter: -(void)setCancelButton:(id)button;
-(void)setConnectionButtonTypes:(unsigned)types;
// declared property setter: -(void)setIcon:(id)icon;
// declared property setter: -(void)setIconView:(id)view;
// declared property setter: -(void)setMessage:(id)message;
// declared property setter: -(void)setMessageLabel:(id)label;
// declared property setter: -(void)setNumberOfMessageLines:(int)messageLines;
// declared property setter: -(void)setNumberOfTitleLines:(int)titleLines;
// declared property setter: -(void)setOtherButton:(id)button;
// declared property setter: -(void)setTitle:(id)title;
// declared property setter: -(void)setTitleLabel:(id)label;
-(void)showActivityIndicator:(BOOL)indicator;
// declared property getter: -(id)table;
// declared property getter: -(id)title;
// declared property getter: -(id)titleFont;
// declared property getter: -(id)titleLabel;
@end

