/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GameKit.framework/GameKit
 */

#import "GKDataRequest.h"

@class GKScore;

@interface GKSubmitScoreDataRequest : GKDataRequest {
@private
	GKScore* _score;
}
@property(retain, nonatomic) GKScore* score;	// @synthesize=_score
-(void)dealloc;
-(id)key;
-(id)request;
// declared property getter: -(id)score;
// declared property setter: -(void)setScore:(id)score;
@end

