/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/GLKit.framework/GLKit
 */

#import "NSCoding.h"
#import "GLKit-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, EAGLContext;
@protocol GLKViewDelegate;

@interface GLKView : XXUnknownSuperclass <NSCoding> {
@private
	BOOL _inDraw;
	NSMutableDictionary* _drawableProperties;
	BOOL _shouldDeleteFramebuffer;
	unsigned _resolveFramebuffer;
	unsigned _resolveColorRenderbuffer;
	unsigned _multisampleFramebuffer;
	unsigned _multisampleColorRenderbuffer;
	unsigned _depthRenderbuffer;
	unsigned _stencilRenderbuffer;
	unsigned _depthStencilRenderbuffer;
	id<GLKViewDelegate> _delegate;
	EAGLContext* _context;
	int _drawableWidth;
	int _drawableHeight;
	int _drawableColorFormat;
	int _drawableDepthFormat;
	int _drawableStencilFormat;
	int _drawableMultisample;
	BOOL _enableSetNeedsDisplay;
	/*function-pointer*/ void* _drawRectIMP;
}
@property(retain, nonatomic) EAGLContext* context;	// @synthesize=_context
@property(assign, nonatomic) id<GLKViewDelegate> delegate;	// @synthesize=_delegate
@property(assign, nonatomic) unsigned depthRenderbuffer;	// @synthesize=_depthRenderbuffer
@property(assign, nonatomic) unsigned depthStencilRenderbuffer;	// @synthesize=_depthStencilRenderbuffer
@property(assign, nonatomic) /*function-pointer*/ void* drawRectIMP;	// @synthesize=_drawRectIMP
@property(assign, nonatomic) int drawableColorFormat;	// @synthesize=_drawableColorFormat
@property(assign, nonatomic) int drawableDepthFormat;	// @synthesize=_drawableDepthFormat
@property(readonly, assign, nonatomic) int drawableHeight;	// @synthesize=_drawableHeight
@property(assign, nonatomic) int drawableMultisample;	// @synthesize=_drawableMultisample
@property(retain, nonatomic) NSMutableDictionary* drawableProperties;	// @synthesize=_drawableProperties
@property(assign, nonatomic) int drawableStencilFormat;	// @synthesize=_drawableStencilFormat
@property(readonly, assign, nonatomic) int drawableWidth;	// @synthesize=_drawableWidth
@property(assign, nonatomic) BOOL enableSetNeedsDisplay;	// @synthesize=_enableSetNeedsDisplay
@property(assign, nonatomic) BOOL inDraw;	// @synthesize=_inDraw
@property(assign, nonatomic) unsigned multisampleColorRenderbuffer;	// @synthesize=_multisampleColorRenderbuffer
@property(assign, nonatomic) unsigned multisampleFramebuffer;	// @synthesize=_multisampleFramebuffer
@property(assign, nonatomic) unsigned resolveColorRenderbuffer;	// @synthesize=_resolveColorRenderbuffer
@property(assign, nonatomic) unsigned resolveFramebuffer;	// @synthesize=_resolveFramebuffer
@property(assign, nonatomic) BOOL shouldDeleteFramebuffer;	// @synthesize=_shouldDeleteFramebuffer
@property(assign, nonatomic) unsigned stencilRenderbuffer;	// @synthesize=_stencilRenderbuffer
+(Class)layerClass;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame context:(id)context;
-(BOOL)_canDrawContent;
-(BOOL)_controlsOwnScaleFactor;
-(void)_createFramebuffer;
-(void)_deleteFramebuffer;
-(void)_display:(BOOL)display;
-(void)_initCommon;
-(BOOL)_presentFramebuffer;
-(void)_resolveAndDiscard;
-(void)_setFramebuffer:(BOOL*)framebuffer;
-(void)bindDrawable;
// declared property getter: -(id)context;
-(void)dealloc;
// declared property getter: -(id)delegate;
-(void)deleteDrawable;
// declared property getter: -(unsigned)depthRenderbuffer;
// declared property getter: -(unsigned)depthStencilRenderbuffer;
-(void)display;
-(void)displayLayer:(id)layer;
// declared property getter: -(/*function-pointer*/ void*)drawRectIMP;
// declared property getter: -(int)drawableColorFormat;
// declared property getter: -(int)drawableDepthFormat;
// declared property getter: -(int)drawableHeight;
// declared property getter: -(int)drawableMultisample;
// declared property getter: -(id)drawableProperties;
// declared property getter: -(int)drawableStencilFormat;
// declared property getter: -(int)drawableWidth;
// declared property getter: -(BOOL)enableSetNeedsDisplay;
-(void)encodeWithCoder:(id)coder;
// declared property getter: -(BOOL)inDraw;
-(void)layoutSubviews;
// declared property getter: -(unsigned)multisampleColorRenderbuffer;
// declared property getter: -(unsigned)multisampleFramebuffer;
// declared property getter: -(unsigned)resolveColorRenderbuffer;
// declared property getter: -(unsigned)resolveFramebuffer;
-(void)setContentScaleFactor:(float)factor;
// declared property setter: -(void)setContext:(id)context;
// declared property setter: -(void)setDelegate:(id)delegate;
// declared property setter: -(void)setDepthRenderbuffer:(unsigned)renderbuffer;
// declared property setter: -(void)setDepthStencilRenderbuffer:(unsigned)renderbuffer;
// declared property setter: -(void)setDrawRectIMP:(/*function-pointer*/ void*)imp;
// declared property setter: -(void)setDrawableColorFormat:(int)format;
// declared property setter: -(void)setDrawableDepthFormat:(int)format;
// declared property setter: -(void)setDrawableMultisample:(int)multisample;
// declared property setter: -(void)setDrawableProperties:(id)properties;
// declared property setter: -(void)setDrawableStencilFormat:(int)format;
// declared property setter: -(void)setEnableSetNeedsDisplay:(BOOL)display;
// declared property setter: -(void)setInDraw:(BOOL)draw;
// declared property setter: -(void)setMultisampleColorRenderbuffer:(unsigned)renderbuffer;
// declared property setter: -(void)setMultisampleFramebuffer:(unsigned)framebuffer;
// declared property setter: -(void)setResolveColorRenderbuffer:(unsigned)renderbuffer;
// declared property setter: -(void)setResolveFramebuffer:(unsigned)framebuffer;
// declared property setter: -(void)setShouldDeleteFramebuffer:(BOOL)deleteFramebuffer;
// declared property setter: -(void)setStencilRenderbuffer:(unsigned)renderbuffer;
// declared property getter: -(BOOL)shouldDeleteFramebuffer;
-(id)snapshot;
// declared property getter: -(unsigned)stencilRenderbuffer;
@end

