/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableArray, NSDictionary, NSDate, CTPhoneNumber, NSString, NSMutableDictionary, NSArray;
@protocol NSCopying, CTMessageAddress;

@interface CTMessage : XXUnknownSuperclass {
	NSObject<NSCopying, CTMessageAddress>* _sender;
	NSMutableArray* _recipients;
	NSMutableArray* _items;
	NSDictionary* _rawHeaders;
	NSDate* _date;
	unsigned _messageId;
	int _messageType;
	CTPhoneNumber* _serviceCenter;
	NSString* _subject;
	NSString* _contentType;
	NSMutableDictionary* _contentTypeParams;
	unsigned _replaceMessage;
	NSString* _countryCode;
}
@property(copy, nonatomic) NSString* contentType;	// @synthesize=_contentType
@property(readonly, assign, nonatomic) NSString* countryCode;	// @synthesize=_countryCode
@property(readonly, assign) NSDate* date;	// @synthesize=_date
@property(readonly, assign) NSArray* items;	// @synthesize=_items
@property(assign, nonatomic) unsigned messageId;	// @synthesize=_messageId
@property(assign, nonatomic) int messageType;	// @synthesize=_messageType
@property(readonly, assign) NSDictionary* rawHeaders;	// @synthesize=_rawHeaders
@property(readonly, assign) NSArray* recipients;	// @synthesize=_recipients
@property(readonly, assign) unsigned replaceMessage;	// @synthesize=_replaceMessage
@property(copy, nonatomic) NSObject<NSCopying, CTMessageAddress>* sender;	// @synthesize=_sender
@property(copy, nonatomic) CTPhoneNumber* serviceCenter;	// @synthesize=_serviceCenter
@property(copy, nonatomic) NSString* subject;	// @synthesize=_subject
-(id)init;
-(id)initWithDate:(id)date;
-(void)addContentTypeParameterWithName:(id)name value:(id)value;
-(id)addData:(id)data withContentType:(id)contentType;
-(void)addEmailRecipient:(id)recipient;
-(id)addPart:(id)part;
-(void)addPhoneRecipient:(id)recipient;
-(void)addRecipient:(id)recipient;
-(id)addText:(id)text;
-(id)allContentTypeParameterNames;
// declared property getter: -(id)contentType;
-(id)contentTypeParameterWithName:(id)name;
// declared property getter: -(id)countryCode;
// declared property getter: -(id)date;
-(void)dealloc;
-(id)description;
// declared property getter: -(id)items;
// declared property getter: -(unsigned)messageId;
// declared property getter: -(int)messageType;
// declared property getter: -(id)rawHeaders;
// declared property getter: -(id)recipients;
-(void)removePartAtIndex:(unsigned)index;
-(void)removeRecipient:(id)recipient;
-(void)removeRecipientsInArray:(id)array;
// declared property getter: -(unsigned)replaceMessage;
// declared property getter: -(id)sender;
// declared property getter: -(id)serviceCenter;
// declared property setter: -(void)setContentType:(id)type;
-(void)setCountryCode:(id)code;
// declared property setter: -(void)setMessageId:(unsigned)anId;
// declared property setter: -(void)setMessageType:(int)type;
-(void)setRawHeaders:(id)headers;
-(void)setRecipient:(id)recipient;
-(void)setRecipients:(id)recipients;
-(void)setReplaceMessage:(unsigned)message;
// declared property setter: -(void)setSender:(id)sender;
// declared property setter: -(void)setServiceCenter:(id)center;
// declared property setter: -(void)setSubject:(id)subject;
// declared property getter: -(id)subject;
@end

