/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "QuartzCore-Structs.h"


__attribute__((visibility("hidden")))
@interface CASlotProxy : XXUnknownSuperclass {
@private
	Proxy* _proxy;
}
-(id)initWithName:(unsigned)name;
-(Object*)CA_copyRenderValue;
-(void)dealloc;
@end

