/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSSet;

@interface CAWindowServerDisplay : XXUnknownSuperclass {
@private
	void* _impl;
}
@property(copy) NSString* TVMode;
@property(copy) NSString* TVSignalType;
@property(assign) BOOL allowsVirtualModes;
@property(assign, getter=isBlanked) BOOL blanked;
@property(readonly, assign) CGRect bounds;
@property(readonly, assign) CAWindowServerDisplay* cloneMaster;
@property(readonly, assign) NSSet* clones;
@property(copy, nonatomic) NSString* colorMode;
@property(assign) float contrast;
@property(readonly, assign) NSString* deviceName;
@property(readonly, assign) unsigned displayId;
@property(assign) float idealRefreshRate;
@property(assign) BOOL invertsColors;
@property(assign) float maximumRefreshRate;
@property(assign) float minimumRefreshRate;
@property(assign, getter=isMirroringEnabled) BOOL mirroringEnabled;
@property(readonly, assign) NSString* name;
@property(copy) NSString* orientation;
@property(assign) float overscanAmount;
@property(readonly, assign) unsigned rendererFlags;
@property(assign) int tag;
@property(assign) BOOL usesPreferredModeRefreshRate;
// declared property getter: -(id)TVMode;
// declared property getter: -(id)TVSignalType;
-(id)_initWithCADisplayServer:(Server*)cadisplayServer;
-(void)addClone:(id)clone;
-(void)addClone:(id)clone options:(id)options;
// declared property getter: -(BOOL)allowsVirtualModes;
// declared property getter: -(CGRect)bounds;
-(unsigned)clientPortAtPosition:(CGPoint)position;
-(unsigned)clientPortOfContextId:(unsigned)contextId;
// declared property getter: -(id)cloneMaster;
// declared property getter: -(id)clones;
// declared property getter: -(id)colorMode;
-(unsigned)contextIdAtPosition:(CGPoint)position;
-(unsigned)contextIdHostingContextId:(unsigned)anId;
-(id)contextIdsWithClientPort:(unsigned)clientPort;
// declared property getter: -(float)contrast;
-(CGPoint)convertPoint:(CGPoint)point fromContextId:(unsigned)contextId;
-(CGPoint)convertPoint:(CGPoint)point toContextId:(unsigned)contextId;
-(void)dealloc;
-(id)description;
// declared property getter: -(id)deviceName;
// declared property getter: -(unsigned)displayId;
-(CGRect)frameOfContextId:(unsigned)contextId;
// declared property getter: -(float)idealRefreshRate;
-(void)invalidate;
// declared property getter: -(BOOL)invertsColors;
// declared property getter: -(BOOL)isBlanked;
// declared property getter: -(BOOL)isMirroringEnabled;
// declared property getter: -(float)maximumRefreshRate;
// declared property getter: -(float)minimumRefreshRate;
// declared property getter: -(id)name;
// declared property getter: -(id)orientation;
// declared property getter: -(float)overscanAmount;
-(void)removeAllClones;
-(void)removeClone:(id)clone;
// declared property getter: -(unsigned)rendererFlags;
// declared property setter: -(void)setAllowsVirtualModes:(BOOL)modes;
// declared property setter: -(void)setBlanked:(BOOL)blanked;
// declared property setter: -(void)setColorMode:(id)mode;
// declared property setter: -(void)setContrast:(float)contrast;
// declared property setter: -(void)setIdealRefreshRate:(float)rate;
// declared property setter: -(void)setInvertsColors:(BOOL)colors;
// declared property setter: -(void)setMaximumRefreshRate:(float)rate;
// declared property setter: -(void)setMinimumRefreshRate:(float)rate;
// declared property setter: -(void)setMirroringEnabled:(BOOL)enabled;
// declared property setter: -(void)setOrientation:(id)orientation;
// declared property setter: -(void)setOverscanAmount:(float)amount;
// declared property setter: -(void)setTVMode:(id)mode;
// declared property setter: -(void)setTVSignalType:(id)type;
// declared property setter: -(void)setTag:(int)tag;
// declared property setter: -(void)setUsesPreferredModeRefreshRate:(BOOL)rate;
// declared property getter: -(int)tag;
// declared property getter: -(BOOL)usesPreferredModeRefreshRate;
-(void)willUnblank;
@end

