/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

#import "QuickLook-Structs.h"
#import "QLPrintPageRenderer.h"

@class NSMutableArray, UIWebPaginationInfo, UIWebBrowserView;

@interface QLSpreadsheetPrintPageRenderer : QLPrintPageRenderer {
	UIWebBrowserView* _printView;
	UIWebPaginationInfo* _paginationInfo;
	BOOL _frameLoaded;
	NSMutableArray* _urls;
	unsigned _currentURLIndex;
	unsigned _currentPageIndex;
	int _totalPagesPrinted;
	BOOL _printingDone;
}
-(id)initWithWebBrowserView:(id)webBrowserView request:(id)request documentType:(id)type;
-(id)_documentURLs;
-(BOOL)_loadNextURL;
-(BOOL)_loadURLAtIndex:(unsigned)index;
-(void)dealloc;
-(void)drawContentForPageAtIndex:(int)index inRect:(CGRect)rect;
-(int)numberOfPages;
-(void)prepareForDrawingPages:(NSRange)drawingPages;
-(void)webView:(id)view didFailLoadWithError:(id)error forFrame:(id)frame;
-(void)webView:(id)view didFinishLoadForFrame:(id)frame;
@end

