/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

#import "QuickLook-Structs.h"
#import "RTF_OIXMLNode.h"


__attribute__((visibility("hidden")))
@interface RTF_OIXMLElement : RTF_OIXMLNode {
@private
	id _attributes;
	id _children;
	BOOL _hasMultipleAttributes;
	BOOL _hasMultipleChildren;
}
+(void)_initEmptyHTMLNames;
+(BOOL)isEmptyHTMLElement:(id)element;
-(id)initWithName:(id)name stringValue:(id)value;
-(void)_appendXMLStringToString:(CFStringRef)string;
-(void)addAttribute:(id)attribute;
-(void)addChild:(id)child;
-(int)attributeCount;
-(int)childrenCount;
-(id)closingTagString;
-(id)contentString;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(void)insertChild:(id)child atIndex:(unsigned)index;
-(id)objectValue;
-(id)openingTagString;
-(void)setObjectValue:(id)value;
-(id)stringValue;
@end

