/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVCaptureDevice.h"
#import "AVFoundation-Structs.h"

@class NSDictionary, NSString;

@interface AVCaptureFigAudioDevice : AVCaptureDevice {
	NSDictionary* _deviceProperties;
	BOOL _levelMeteringEnabled;
	BOOL _isConnected;
	NSString* _localizedName;
}
+(id)_devices;
-(id)init;
-(id)initWithProperties:(id)properties;
-(void)audioInputDeviceLocalizedNameDidChangeHandler:(id)audioInputDeviceLocalizedName;
-(void)audioInputDevicesDidChangeHandler:(id)audioInputDevices;
-(void)dealloc;
-(id)devicePropertiesDictionary;
-(BOOL)hasMediaType:(id)type;
-(BOOL)isConnected;
-(BOOL)isInUseByAnotherApplication;
-(id)localizedName;
-(id)modelID;
-(BOOL)startUsingDevice:(id*)device;
-(void)stopUsingDevice;
-(BOOL)supportsAVCaptureSessionPreset:(id)preset;
-(id)uniqueID;
@end

