/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVFoundation-Structs.h"
#import "AVAsset.h"
#import "AVURLAsset.h"

@class NSURL, AVURLAssetInternal, NSString, AVAssetCache;
@protocol AVURLAssetFailedURLRequestHandling;

@interface AVURLAsset : AVAsset {
@private
	AVURLAssetInternal* _asset;
}
@property(readonly, assign, nonatomic) NSURL* URL;
+(id)URLAssetWithURL:(id)url options:(id)options;
+(id)_avfValidationPlist;
+(void)_ensureAudiovisualTypes;
+(id)audiovisualMIMETypes;
+(id)audiovisualTypes;
+(void)initialize;
+(BOOL)isPlayableExtendedMIMEType:(id)type;
-(id)init;
-(id)initWithURL:(id)url options:(id)options;
// declared property getter: -(id)URL;
-(CFURLRef)_URL;
-(void)_addFigAssetNotifications;
-(id)_assetInspector;
-(id)_assetInspectorLoader;
-(id)_errorForFigNotificationPayload:(CFDictionaryRef)figNotificationPayload key:(CFStringRef)key;
-(OpaqueFigFormatReader*)_formatReader;
-(void)_removeFigAssetNotifications;
-(void)_setAssetInspectorLoader:(id)loader;
-(void)_tracksDidChange;
-(void)cancelLoading;
-(void)dealloc;
-(id)description;
-(void)finalize;
-(id)lyrics;
-(id)tracks;
@end

@interface AVURLAsset (AVAssetChapterInspection)
-(unsigned)_addChapterMetadataItem:(id)item withDuration:(XXStruct_pwHToB)duration timeRange:(XXStruct_yD8eWC)range toChapters:(id)chapters fromIndex:(unsigned)index;
-(id)_chapterGroupInfo;
-(id)availableChapterLocales;
-(id)chapterMetadataGroupsWithTitleLocale:(id)titleLocale containingItemsWithCommonKeys:(id)commonKeys;
@end

@interface AVURLAsset (AVURLAssetCache_Private)
@property(readonly, assign, nonatomic) AVAssetCache* assetCache;
@property(readonly, assign, nonatomic) NSString* cacheKey;
@property(readonly, assign, nonatomic) BOOL shouldMatchDataInCacheByURLPathComponentOnly;
@property(readonly, assign, nonatomic) BOOL shouldMatchDataInCacheByURLWithoutQueryComponent;
// declared property getter: -(id)assetCache;
// declared property getter: -(id)cacheKey;
-(id)downloadDestinationURL;
-(id)resolvedURL;
// declared property getter: -(BOOL)shouldMatchDataInCacheByURLPathComponentOnly;
// declared property getter: -(BOOL)shouldMatchDataInCacheByURLWithoutQueryComponent;
@end

@interface AVURLAsset (AVURLAssetFailedURLRequestHandling)
@property(assign, nonatomic, setter=setFailedURLRequestDelegate:) id<AVURLAssetFailedURLRequestHandling> failedURLRequestDelegate;
// declared property getter: -(id)failedURLRequestDelegate;
-(void)finishHandlingFailedURLRequestWithResponseProperties:(id)responseProperties;
// declared property setter: -(void)setFailedURLRequestDelegate:(id)delegate;
@end

